### ISSUE TITLE
Overlapping Projectile Images

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#1]
It's possible to cause multiple images to overlap at once by changing the projectile after firing.
As an example:
1. Click the slo-mo option (not required, just makes this easier).
2. Choose the Buick projectile and fire it.
3. In mid flight, change the type of projectile to the adult man and press fire again.
You can repeat step 3 for as many objects as you like and the images will continue to overlap.

![bad commute](https://cloud.githubusercontent.com/assets/5863899/5710228/91e914b0-9a5d-11e4-8597-e3eb05c75f2f.png)

Video:
https://drive.google.com/file/d/0B3HJopSo_QqLUVNsMzVNYUNuVk0/view?usp=sharing

Tested on both FF34 and Chrome 39
Version: 2.03.14 (72977)
Build Date: May 14, 2013
Flash Version: WIN 15,0,0,246
OS: Windows 8.1

**Comment by pixelzoom** [comment]
@phet-steele Looks like this report is for the Flash version, so I'm labeling with "legacy-bug".  Correct me if I got that wrong.

**Comment by ariel-phet** [comment]
HTML5 version shouldn't have this issue, closing
