### ISSUE TITLE
Increase size of halo

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#100]
@andrea-phet the yellow halo that appears when the tracer tool overlaps a timing dot is pretty subtle, and can be hard to see when under the crosshairs. Can you increase the size of halo a bit?

![image](https://user-images.githubusercontent.com/8419308/28430447-d32645b4-6d3d-11e7-9b76-c0c34d4ff302.png)

**Comment by andrea-phet** [comment]
How's that? @arouinfar 
![image](https://user-images.githubusercontent.com/7988696/29089120-8407e712-7c38-11e7-9f6a-01fb1f895a53.png)

**Comment by arouinfar** [comment]
Looks great @andrea-phet!
