### ISSUE TITLE
Muzzle flash should be responsive to pause/slow motion

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#101]
The team reviewed the muzzle flash during yesterday's design meeting. Overall, it looks great, but can look a bit odd when in slow motion or when a projectile is queued up (fired) while paused. @jbphet had some suggestions about how @andrea-phet could make the muzzle flash animation responsive to the sim speed and state, so we decided to go for it.

**Comment by andrea-phet** [comment]
@arouinfar could you review the above change?

**Comment by arouinfar** [comment]
Looks great, thanks.
