### ISSUE TITLE
ProjectileNode TODOs

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/projectile-motion#102]
Getting a view-coordinate copy of the DataPoint would be ideal, so viewPointProperty wouldn't be needed.

**Comment by andrea-phet** [comment]
Also, in this piece of code, a more robust system for only removing once (remove these listeners!) would be good:
```
// When the projectile lands, remove the force diagram
      if ( dataPoint.reachedGround ) {
        if ( !removed ) {
          removed = true;
          forcesBox.visible = false;
          freeBodyDiagram.visible = false;

```

**Comment by andrea-phet** [comment]
@jonathanolson , as these TODOs were put in along with performance enhancements, can you explain to me what they mean?

**Comment by jonathanolson** [comment]
Thew view-coordinate copy of a DataPoint part is because, instead of taking a DataPoint in model coordinates (currently the only ones) and from that creating a DataPoint in view coordinates (using the model-view transform), currently the model DataPoint is getting wrapped in a duck-typed object:
```js
    // {Property.<{viewPosition: {Vector2}, dataPoint: {DataPoint}}>}
    var viewPointProperty = new DerivedProperty( [ dataPointProperty ], function( dataPoint ) {
      return {
        viewPosition: modelViewTransform.modelToViewPosition( dataPoint.position ),
        dataPoint: dataPoint
      };
    } );
```
where ideally, you could have `viewDataPoint = modelDataPoint.transformed( ... )` and just use that object.

In that case, ProjectileNode only needs to know about a Property of the "view" DataPoint.

**Comment by jonathanolson** [comment]
For whether it reached the ground, usually there would be separate listeners for that (not included in the updateFreeBodyDiagram). I'd leave that to the code reviewer to decide, and wouldn't worry much about proactively changing things.

**Comment by andrea-phet** [comment]
Actually, I think how things are right now are fine, and are the safest way in terms of unlinking things to prevent memory leaks. Getting a view-coordinate copy would only involve changing position, while leaving other properties such as velocity untouched, so I think wrapping it up that way makes sense.

Another options would be to not have a viewPoint, and simply call modelViewTransform on the modelDataPoint.position when needed.

What do you think? @jonathanolson

**Comment by jonathanolson** [comment]
> Another options would be to not have a viewPoint, and simply call modelViewTransform on the modelDataPoint.position when needed.

I think this was being done many times before (which hurt performance). As long as it doesn't decrease performance.

Otherwise I'd leave it up to whoever is doing the code review. I'd have to dig in more to be able to really give an opinion.

**Comment by andrea-phet** [comment]
Okay. I'll stick with the viewPoint property as to avoid calling modelViewTransform too many times. As @pixelzoom has already performed the code review and didn't raise any issues about it, we are good to close this issue.
