### ISSUE TITLE
memory testing?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#105]
I'm about to start final code review #33, and it's unclear what memory testing this sim has had.  My concern is that addressing memory leaks can sometimes require major code changes, which then require code review.

@andrea-phet Has this sim been tested for memory leaks using heap snapshot? What were the results?

**Comment by phet-steele** [comment]
The extent of testing is here: #86

**Comment by pixelzoom** [comment]
Thanks @phet-steele!

**Comment by pixelzoom** [comment]
I verified the results in #86, this sim is not leaking memory. Closing.
