### ISSUE TITLE
incorrect string keys for screen names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#106]
Related to code review #103.

The strings for screen names in `projectile-motion-strings_en.json` are currently:

```js
  "lab.title": {
    "value": "Lab"
  },
  "intro.title": {
    "value": "Intro"
  },
  "drag.title": {
    "value": "Drag"
  },
  "vectors.title": {
    "value": "Vectors"
  },
```

As noted in the checklist item, "Screen names should use camelcase, like `screen.screenName`."  That is admittedly not very clear, and I'll update the checklist accordingly.   To clarify... The convention for screen names is to use `"screen.{{TITLE}}"` for the key.  So the above keys should be `"screen.lab"`, `"screen.intro"`, `"screen.drag"` and `"screen.vectors"` respectively.

**Comment by jbphet** [comment]
Looks good, closing.
