### ISSUE TITLE
Buick® is a registered trademark of General Motors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#107]
Noted during code review #103.

This sim uses the string "Buick". Buick® is a registered trademark of General Motors.See https://www.gm.com/copyright-trademark.html.  Has PhET obtained the rights to use? Has the use been cleared with CU legal?

**Comment by arouinfar** [comment]
>  Has PhET obtained the rights to use? Has the use been cleared with CU legal?

@pixelzoom my guess is no. The "Buick" string was ported from Flash, but I'd be fine with using "Car" instead.

**Comment by pixelzoom** [comment]
@andrea-phet If the string changes (e.g to "Car"), be sure to change the string key.  You might also want to rename "buick_1.png" and "buick_2.png".

**Comment by pixelzoom** [comment]
@arouinfar Unclear whether you made a decision here or passed that decision on to @ariel-phet. Please clarify.

**Comment by pixelzoom** [comment]
Also look for 'buick' or 'Buick' in the code.  I see 9 occurrences of 'buick' (case insensitive).

**Comment by arouinfar** [comment]
@pixelzoom Originally I was waiting for @ariel-phet to chime in, but I find it highly unlikely that PhET obtained the rights to use "Buick", so let's go ahead and kill it and replace with "Car".

**Comment by ariel-phet** [comment]
Agreed, "Car" is probably much safer and less culturally specific.

**Comment by andrea-phet** [comment]
Switched to "car."

**Comment by jbphet** [comment]
The license file needs to be updated.  

As a note, there are a number of strings in the "autoport" directory of babel that have the "buick" key.  These should probably NOT be ported into the sim, since the word "Buick" may have been translated differently than "car".

**Comment by andrea-phet** [comment]
Good catch, the above commit updates the license. What do we do about babel?

**Comment by pixelzoom** [comment]
I believe that you can ignore babel.  When porting a sim from Java/Flash, we decided a while back not to port its translations.  @jbphet please confirm.

**Comment by jbphet** [comment]
Honestly, I don't recall whether we decided that or not.  If so, we should just remove the autoport directory entirely from babel.  At any rate, I'm fine with ignoring babel and having translators start from scratch for this particular simulation since it has changed a lot from the original version.

**Comment by pixelzoom** [comment]
After discussion on Slack...  There is no need to port translations for this sim.  Keys have changed, and most strings have been revised in some way (e.g. capitalization).  So it would be better to have translators start from scratch.

I don't see "Buick" anywhere in the HTML5 code base, so this is done. Closing.
