### ISSUE TITLE
too much artwork in 1 .ai file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#108]
Related to code review #103, this checklist item:

> - [ ]  Is there a file in assets/ for every resource file in audio/ and images/? Note that there is _not necessarily_ a 1:1 correspondence between asset and resource files; for example, several related images may be in the same .ai file. Check license.json for possible documentation of why some reesources might not have a corresponding asset file.

The "_not necessarily_" bit in this checklist item is not a "pass" to put everything into one .ai file.  It's supposed to cover 2 situations: (1) "relate images", e.g., a human body that was broken into multiple PNG files for movable body parts, and (2) a PNG that was generated by a screenshot.  

With the exception of fire_button.ai, all assets for this sim are in a single Projectile_Motion_Artwork.ai file. I realize that this is probably what the artist(s) gave you. And I'll leave it up to @arouinfar or @ariel-phet to decide whether to change anything, because I think this a problem with how the artists are handling things, not the programmers.

Having everything in one .ai file is (in general) a problem.  If you want to change one piece of artwork, you will get an entirely new file.  And you can't just verify that what the artist gave you matches the associated PNG file -- you need to check every PNG file.  I can't tell you how many times I've been given a new .ai file that has irrevant changes in it, or is based on some stale .ai file that lives in Google docs or (worse) on the artists computer. 

Best practices for artwork are:

(1) One .ai file per PNG, or set of related PNGs.

(2)  Once the artwork (.ai) is checked into GitHub, other copies (e.g. Google doc, artist's computer) should be deleted. Any subsequent changes should be made using the file that is checked into GitHub.

**Comment by ariel-phet** [comment]
@arouinfar would it be reasonable for you to break these files up before Andrea returns?

**Comment by arouinfar** [comment]
It's on my to-do list for today @ariel-phet.

**Comment by arouinfar** [comment]
I've separated the Projectile_Motion_Artwork.ai file, but have left associated artwork grouped in the same file (e.g. David). I've emailed the .ai files to @andrea-phet to check in once she's back.

**Comment by pixelzoom** [comment]
The .ai files look great.  Closing.
