### ISSUE TITLE
branch: projectile-paths

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#109]
Related to code review #103, this item:

> - [ ] Are there git repository branches that are no longer used and should be pruned?

I'm going to update the code-review check list to note that all non-release branches should have an associated GitHub issue (which is why I'm creating this issue.) 

Please document the purpose of this branch.  Then if the branch is no longer needed, delete it.

**Comment by andrea-phet** [comment]
The purpose of this branch was to explore ways to draw the projectile paths that would maximize performance. As the work here has been incorporated into master, the branch can be deleted. @jonathanolson , since you created this branch, is this okay?

**Comment by jonathanolson** [comment]
Sorry about that, I'll remove it.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
