### ISSUE TITLE
typos and broken link in implementaton-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#110]
Related to code review #103.

While reviewing [implementaton-notes.md](https://github.com/phetsims/projectile-motion/blob/master/doc/implementaton-notes.md), I fixed some typos and a broken link. Review the change history to see what I did.  

This issue is an FYI.  Feel free to close after reviewing.

**Comment by pixelzoom** [comment]
I made 6 consecutive commits, between https://github.com/phetsims/projectile-motion/commit/904371ba9258a9440726a06fa19d16b4025e3296 and https://github.com/phetsims/projectile-motion/commit/41d313c3c33d9d73720128a2f423bfa8e42bae30.  I didn't link them to this issue, because I hadn't planned on creating this issue :)

**Comment by andrea-phet** [comment]
Looks good, closing.
