### ISSUE TITLE
controls in the "ground" are cramped

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#112]
Related to code review #103, this item:

> - [ ] Are pointer areas optimized, especially for touch? (run with query parameter showPointerAreas)

Below is a screenshot of  the Lab screen, which has the most controls, with `?dev&showPointerAreas`. 

My feedback:
(1) Controls in the ground feel generally cramped, too close to the navigation bar. 
(2) Play/pause and step buttons are dangerously close to the navigation bar.  The user may hit the Lab button.  And the step button's touch area is probably not being optimized because of that -- it should have a larger touch area.
(3) "Initial Speed" panel feels cramped, very close to navigation bar.

These issues could be addressed by making the ground a bit taller.  I realize that you're trying to maximize the "shoot space".  But I don't think loosing a couple of pixels for the sky will make a huge difference, and it sure would improve the usability and look of the controls that are in the "ground" area.

Assigning to @arouinfar because this is a design decision.
 

![screenshot_330](https://user-images.githubusercontent.com/3046552/28494692-25b60524-6ef3-11e7-952d-d7ccae706e3c.png)

**Comment by ariel-phet** [comment]
Self-assigning since I have a few thoughts here as well

**Comment by arouinfar** [comment]
Thanks your suggestions @pixelzoom! While I didn't witness any accidental screen-changing while stepping during interviews, I agree that there should generally be a bit more padding between the controls and the navbar. I've mocked up some changes to the grassy area on top of a screenshot of dev.8.

Proposed changes:
* Increase grass height by 10px
* Move Initial Speed panel up 5 px (now 10 px above navbar)
* Reduce width of Initial Speed panel by 20 px (remove 10 px from each side)
* Move fire/erase 10 px to the left to compensate for reducing width of Initial Speed 
* Fire/erase, speed/pause group, and reset all center-aligned to Initial Speed
* Normal/slow, pause, step moved to the right so that it's above an empty area of the navbar.

![image](https://user-images.githubusercontent.com/8419308/28589188-4560cda2-713a-11e7-8a16-0620f871a665.png)

Proposed changes overlayed on dev.8:
![image](https://user-images.githubusercontent.com/8419308/28589113-ea95c904-7139-11e7-9858-653816337976.png)

@ariel-phet can you review? Please let me know if you have any suggestions, and I'll mock them up.

**Comment by ariel-phet** [comment]
@arouinfar I think the main one is that in the Lab screen (worse case scenario) the "Initial Values"  panel could be tightented vertically a bit (a bit less padding top and bottom) to ease up some conflict with the panels and the ground. I think the drop down could be move up ever so slightly to buy a bit more room in that panel as well.

Here is a mockup for tweaks on dev.8 showing buying a bit more room with those panels. I certainly think shrinking the Initial Values one works well to buy real estate

![pm](https://user-images.githubusercontent.com/4051174/28591818-3be0802e-7144-11e7-84a4-0a6f14b1b0be.PNG)

**Comment by ariel-phet** [comment]
@arouinfar we could probably also buy a pixel or two by reducing the height of the grass above the road (I don't think much is needed there to give the right impression)

**Comment by arouinfar** [comment]
Thanks for mocking up the panels @ariel-phet! Your changes free up a lot of needed vertical space. I've added the updated "ground" controls to your mockup, and reduced the grass height by 1 px.
![image](https://user-images.githubusercontent.com/8419308/28595265-6d557536-7150-11e7-823d-5e344ba434b2.png)

**Comment by ariel-phet** [comment]
@arouinfar I think that all looks good. I actually like the slightly reduced grass height, gives a bit more of the "fading to the horizon" look.

Assigning to you and @andrea-phet to implement the changes when she returns

**Comment by arouinfar** [comment]
@phet-steele pointed out that normal/slow and pause/step are pretty far from the fire button in https://github.com/phetsims/projectile-motion/issues/112#issuecomment-317882371. These controls are often used with one another, and it's important to preserve the proximity. I agree, so I'm going to mock up a few more options.

**Comment by pixelzoom** [comment]
If the goal of the mockup in https://github.com/phetsims/projectile-motion/issues/112#issuecomment-317882371 was to move the play/pause/step controls away from the screen buttons...   That may work for English, but not necessarily for other locales.  Depending on the translation of the screen names, you have no idea where the screen buttons may end up.

**Comment by pixelzoom** [comment]
Positioning the controls in the ground seems to be a compromise based on avoid collision with the target's location value.  Besides that compromise, we typically put values _above_ things (e.g. ticks on sliders), otherwise your finger tends to obscure the value on mobile devices.  What if you investigated moving the target's location value (eg 5.0m) above the target?

**Comment by pixelzoom** [comment]
I said:
> What if you investigated moving the target's location value above the target?

But I see that would be a problem for large objects, they would obscure the location when they land.

![screenshot_333](https://user-images.githubusercontent.com/3046552/28675625-ab6be6c4-72a5-11e7-9015-598b0d41bf97.png)

**Comment by arouinfar** [comment]
> If the goal of the mockup in #112 (comment) was to move the play/pause/step controls away from the screen buttons... That may work for English, but not necessarily for other locales. Depending on the translation of the screen names, you have no idea where the screen buttons may end up.

To some extent the goal was to move them away from the icons, but primarily I thought it made the ground controls look less cluttered. The buttons have also been shifted up a bit, so I don't think we need to be overly worried about accidental screen switching. We can certainly have @phet-steele and the QA team keep an eye out for this when testing on an iPad.

**Comment by arouinfar** [comment]
I've made a few tweaks to improve the proximity with the fire button and the pause/step buttons, namely:
* Swap the Erase and Fire buttons
* Move Normal/Slow radio buttons to the right of pause/step (also better for i18n)
* Move pause/step/playback speed controls closer to fire button (40 px between fire and pause).

I realize that these changes result in the left side of the grass being much more occupied than the right side, but I think usability is more important than aesthetics. There's still quite a bit of vertical padding between the navbar and the pause/step/playback speed controls, so I'm not worried about accidental screen changing.

Here's an updated mockup, along with the changes overlayed on the latest dev:

![image](https://user-images.githubusercontent.com/8419308/28801593-8232eace-760f-11e7-803c-cbfc90df8d38.png)
![image](https://user-images.githubusercontent.com/8419308/28801620-97ec2934-760f-11e7-9bfb-c0f5bfe95109.png)

**Comment by andrea-phet** [comment]
Made the changes suggested above. Leaving @arouinfar assigned to look over.

**Comment by arouinfar** [comment]
Looks amazing @andrea-phet!
