### ISSUE TITLE
@author annotations with odd formatting

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#114]
Related to code review #30.

Some of the `@author` annotations are oddly formatted, like this:

```js
 * @author Andrea Lin( PhET Interactive Simulations )
```

I globally replaced these with:

```js
 * @author Andrea Lin (PhET Interactive Simulations)
```

Nothing for you to do here @andrea-phet. I mainly created this issue in case you have a template in your IDE that needs to be adjusted.

**Comment by andrea-phet** [comment]
Okay, will look into that.
