### ISSUE TITLE
reduce dimensions of PNG files?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#119]
Related to code review #103.

The PNG files appear to be much larger than how they appear in the sim.  So I'm guessing (but have not confirmed) that they are being scaled way down.   Looks like the scaling is being done by setting `maxHeight` in ProjectileObjectViewFactory `createObjectView`.   

Inspecting (for example) the 'piano', I see:

```
> transformedBallSize
66
> pianoImage.height
408 
> transformedBallSize / pianoImage.height
0.16
```

`transformedBallSize` is used as the value for `maxHeight`. So piano_1.png is being scaled by 0.16.

There are 2 problems with this:

(1) Any scale smaller than 0.5 typically looks crummy on some platforms (especially Firefox).

(2) Images that are unnecessarily large tend to bloat the deliverable .html file.

So... If you're scaling down by anything less than 0.5, I recommend that you reduce the dimensions of the PNG files.

**Comment by pixelzoom** [comment]
The images/ directory is 500K, so (after compression) this could be a big chunk of the 2MB html deliverable.

**Comment by andrea-phet** [comment]
The images right now are two times larger than what they need to be for a normal ipad resolution, so I think these dimensions work well for various devices. @jbphet and I looked at the images, and even though the entire folder is large, the size of the images themselves are reasonable compared to other sims. As for whether an image looks crummy, mipmaps could be used, but I'd prefer to avoid them because it increases the size of the deliverable. @arouinfar could you take a look at the images and see if any of them need to be fixed when scaled down?

**Comment by arouinfar** [comment]
@andrea-phet I reviewed the sim in small Firefox windows, and I think the projectiles look reasonable (even when small/zoomed out). There's a bit of aliasing on the cannon, though. How much is the cannon being scaled down? I can re-export it for you at a more reasonable size, if that's an issue.

**Comment by arouinfar** [comment]
After chatting with @andrea-phet, we've decided to try a slightly smaller cannon. Reassigning myself to re-export the cannon assets.

**Comment by arouinfar** [comment]
@andrea-phet I re-exported the cannon images at a slightly smaller (83%) resolution, as discussed. The .ai asset remains unchanged.

[cannon_base.png](https://user-images.githubusercontent.com/8419308/29047582-8345e2a2-7b89-11e7-8cdb-172decb54bda.png)
[cannon_barrel.png](https://user-images.githubusercontent.com/8419308/29047581-8344ce4e-7b89-11e7-8102-ee700852b063.png)

**Comment by andrea-phet** [comment]
Even with the smaller cannon images, it still looks weird on Firefox, so I decided to use mipmaps for just the cannon artwork (also the cannon on the fire button, which made it look better). It increases the size of the deliverable by 47 KB, which makes a total of 2MB, which is on the larger side but not out of the range. @arouinfar would you like to take a look and close?

**Comment by arouinfar** [comment]
@andrea-phet the cannon looks much better in Firefox now!
