### ISSUE TITLE
move image-creation functions to ProjectileObjectType

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#122]
Related to code review #103.

In ProjectileObjectViewFactory`createObjectView` and `createLandedObjectView`, you big `switch` statements that look like this:

```js
      switch( type ) {
        case 'cannonball':
          return new Circle( transformedBallSize / 2, { fill: 'black' } );
        case 'pumpkin':
          return new Image( pumpkinImage, { maxHeight: transformedBallSize } );
        case 'baseball':
          return new Image( baseballImage, { maxWidth: transformedBallSize } );
        case 'buick':
          return new Image( buickImage, { maxHeight: transformedBallSize * 0.9 } );
        case 'football':
          return new Image( footballImage, { maxHeight: transformedBallSize } );
        case 'human':
          return new Image( humanImage, { maxHeight: transformedBallSize * 1.9 } );
        case 'piano':
          return new Image( pianoImage, { maxWidth: transformedBallSize * 1.1 } );
        case 'golfBall':
          return new Circle( transformedBallSize / 2, { fill: 'white', stroke: 'gray' } );
        case 'tankShell':
          return new Image( tankShellImage, { maxHeight: transformedBallSize } );
        default:
          throw new Error( 'type is not right' );
      }
```

A better approach would be to `createObjectView` and `createLandedObjectView` functions to ProjectileObjectType.  Then define your objects like this in ProjectileObjectType:

```js
  ProjectileObjectType.CANNONBALL = new ProjectileObjectType(
    ...,
    function( maxHeight ) { return new Circle( maxHeight / 2, { fill: 'black' } ),
    function( maxHeight ) { return new Circle( maxHeight / 2, { fill: 'black' } )
  );

  ProjectileObjectType.PUMPKIN = new ProjectileObjectType(
   ...,
   function( maxHeight ) { return new Image( pumpkinImage, { maxHeight: maxHeight } ),
   function( maxHeight ) { return new Image( landedPumpkinImage, { maxHeight: maxHeight } )
  );
  ...
```

This prevents spreading string literals around ('cannonball', 'pumpkin',...) and puts the image-creation functions where they belong, with the object. 

You might also consider making `createLandedObjectView` optional, since many objects (cannonball, baseball, football, golfball, tankshell) appear to use the same image for both cases.

**Comment by andrea-phet** [comment]
The above commit separates out the node creations according to each benchmark, which makes creating a different landed object view option for certain benchmarks. I didn't want to put the image creation into ProjectileObjectType because ProjectileObjectType and ProjectileObjectViewFactor are a model and view pair, respectively. Assigning to @jbphet to review.

**Comment by pixelzoom** [comment]
I can understand wanting to keep the model and view separate.  But sometime we do put "view creation" function in the model, for convenience and clarity.  That said...

About this bit of code in `ProjectileNode`: 

```js
102  var projectileObjectView = ProjectileObjectViewFactory[ objectType.benchmark ]( diameter, modelViewTransform, false );
103  var landedObjectView = ProjectileObjectViewFactory[ objectType.benchmark ]( diameter, modelViewTransform, true );
```

My concern here is that that `{string} benchmark` must match the name of a function in  `ProjectileObjectViewFactory`.   That dependency is not obvious until you grok the above lines, and it means that all of the benchmark tokens are duplicated in 2 places: in  `ProjectileObjectType` (as strings) and in `ProjectileNode` (as function names). 

In general, I try to avoid the `foo[ 'string' ]` form of accessing fields, because it results in this type of dependency.  And this type of dependency tends to make code harder to read and maintain.

It's also odd that the functions in `ProjectileObjectViewFactory` have names like `cannonball` and `pumpkin`.  Since they are factory functions, they should be named `createCannonball` and `createPumpkin`.  

In the next comment, I'll describe an alternative.

**Comment by pixelzoom** [comment]
Sketch of alternative solution, showing deltas:

```js
var ProjectileObjectViewFactory = {
  ...
  createCannonball: function( diameter, modelViewTransform, landed ) { ... },
  createPumpkin: function( diameter, modelViewTransform, landed ) { ... },
  // etc. for other object types
};
```

```js
function ProjectileObjectType( ..., viewCreationFunction, options ) {
  ...
  this.viewCreationFunction = viewCreationFunction; // @public (read-only)
 ...
}
...
ProjectileObjectType.CANNONBALL = new ProjectileObjectType(
  ...
  ProjectileObjectViewFactory.createCannonball,
  ...
);
// etc. for other object types
```

```js
// ProjectileNode
102  var projectileObjectView = objectType.viewCreationFunction( diameter, modelViewTransform, false );
103  var landedObjectView = objectType.viewCreationFunction( diameter, modelViewTransform, true );
```

@andrea-phet Does the above make sense, and what do you think of it?

**Comment by andrea-phet** [comment]
Yes, that looks good.

**Comment by andrea-phet** [comment]
The above commit implements the alternative solution, with one difference in that viewCreationFunction is optional, as some such as Custom do not need one. Assigning back to @pixelzoom to review.

**Comment by pixelzoom** [comment]
Looks overall great.  But ProjectionNode.js line 101 should probably change from:

```js
if ( objectType && objectType.benchmark ) {
```

to 

```js
if ( objectType && objectType.viewCreationFunction ) {
```

**Comment by pixelzoom** [comment]
Looks great. Closing.
