### ISSUE TITLE
Height arrow cap is mangled a bit

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#123]
The top of my height arrow is pretty broken, anyone else?

<img width="205" alt="screen shot 2017-07-25 at 11 24 40 am" src="https://user-images.githubusercontent.com/5863899/28584990-02c1c0c2-712c-11e7-91cc-ea5fcac1fa2d.png">

Seen on macOS 10.12.5 Chrome. For phetsims/QA/issues/29.

**Comment by arouinfar** [comment]
Same here @phet-steele. The mangled arrow is also present in latest Firefox and Safari.

**Comment by andrea-phet** [comment]
Should be all good now. Assigning to @phet-steele to review.

**Comment by phet-steele** [comment]
> Should be all good now.

Yea it is!
