### ISSUE TITLE
Adjust scaling of velocity vector

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#125]
@kathy-phet reported:

>The other question I had was whether you had honed the scaling on the [velocity] vectors. I know there is such a large dynamic range but they often felt like it was hard to keep them on scale. I haven't spent enough time to have any concrete recommendations here. Just wondering. 

The velocity vectors do seem a bit big. Self-assigning for further review.

**Comment by arouinfar** [comment]
A vector with a magnitude of 1 m/s appears to be 30px at iPad resolution. If I recall correctly, at default zoom, 1 m = 30 px. Distance and velocity have different units and do not need be on the same scale.
![image](https://user-images.githubusercontent.com/8419308/28801902-ffa3f04c-7610-11e7-8117-c21eb7d31a54.png)

I think 1 m/s could be scaled down quite a bit so that it's barely visible. Perhaps 10 px = 1 m/s? @andrea-phet let's plan to work on this together. When you're back in town let's meet (in person or remotely) to find a size that looks more reasonable.

**Comment by andrea-phet** [comment]
Leaving assigned to @arouinfar to play with.

**Comment by arouinfar** [comment]
Looks good!
