### ISSUE TITLE
Assertion failed: timeToGround is NaN

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#128]
@andrea-phet, there is still some wonkiness with high drag forces. On the Lab screen, copy these parameters, pay attention to height and speed!

<img width="398" alt="screen shot 2017-07-25 at 3 33 40 pm" src="https://user-images.githubusercontent.com/5863899/28639400-59a214bc-7205-11e7-8200-f67e5228553e.png">

When the baseball lands, we get the following error:
```
Uncaught Error: Assertion failed: timeToGround is NaN
    at window.assertions.assertFunction (/assert/js/assert.js:21)
    at Trajectory.step (Trajectory.js?bust=1501096918911:170)
    at LabModel.stepModelElements (ProjectileMotionModel.js?bust=1501096918911:230)
    at EventTimer.step (EventTimer.js?bust=1501096918911:122)
    at LabModel.step (ProjectileMotionModel.js?bust=1501096918911:218)
    at Sim.stepSimulation (Sim.js?bust=1501096918911:830)
    at Sim.runAnimationLoop (Sim.js?bust=1501096918911:770)
```
This is NOT the only projectile that can get this error. I've at least seen the football and golfball hit it too, although with some hard-to-pin-down parameters.

Seen on macOS 10.12.5. Chrome. For phetsims/QA/issues/29.

URL: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.8/projectile-motion_en.html
Version: 1.0.0-dev.8 2017-07-21 20:58:03 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"fd28f6a0","branch":"master"},"babel":{"sha":"cd335880","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"80ecc40f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"db4de9f6","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"phet-core":{"sha":"d8bec6c1","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"projectile-motion":{"sha":"44c23ebc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"d4481c51","branch":"master"},"scenery-phet":{"sha":"6b27f596","branch":"master"},"sherpa":{"sha":"f1937ecb","branch":"master"},"sun":{"sha":"719b389c","branch":"master"},"tandem":{"sha":"29cd4f63","branch":"master"}}

**Comment by andrea-phet** [comment]
@phet-steele and I worked on this together, and we think the error is caused by a zero y acceleration when there is terminal velocity, so the above commit adds an algorithm for that.

**Comment by phet-steele** [comment]
I no longer see this in dev.9.
