### ISSUE TITLE
Consider dots every 0.1 secs

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/projectile-motion#130]
When I was playing with the sim quite a bit at AAPT, it seemed like it might be a bit easier to use with dots every 0.1 secs. 

In the act of collecting data, it was a bit easy to get lost in where the data collector was placed with the dots so closely spaced and every 0.1 secs makes for easier math. Is it relatively easy to see a version that has dots every 0.1 secs for us to play with and compare? 

In the act of noticing acceleration, having dots spaced every 0.1 secs it may be a bit easier to see the change in spacing because there will be a bigger differential.

**Comment by andrea-phet** [comment]
@kathy-phet, the latest on master has dots ever 0.1s instead of 0.05s.

**Comment by kathy-phet** [comment]
@arouinfar - I find this easier to make sense of when I'm pulling out the probe and going over the dots. For instance, every 0.1 sec on the default I travel 1.8 m which makes a lot of sense with the 18 m/s starting point. I don't miss the 0.05 sec dot myself. How do you find it?

**Comment by arouinfar** [comment]
@kathy-phet I think the 0.1 s intervals look pretty good, and I like that there's a bit less noise, in general. I think the only potential negative side effect is that it'll be a bit more likely to not have a dot at (or very near) the apex, but I'm not sure how critical that is. What do you think @kathy-phet?

![image](https://user-images.githubusercontent.com/8419308/29098078-9563480e-7c5a-11e7-8155-db45aa52f44b.png)

**Comment by arouinfar** [comment]
@ariel-phet do you have any objections to the 0.1 s interval?

I'll open a new issue for the further discussion of adding an apex dot.

**Comment by ariel-phet** [comment]
@kathy-phet @andrea-phet @arouinfar I think the 0.1 dots look good. Closing
