### ISSUE TITLE
[iPad2] Clipping when Air Resistance is off

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#131]
For https://github.com/phetsims/QA/issues/29.

On the Lab screen, if air resistance is off, the Altitude slider's left tweaker and the 'g' in Drag Coefficient are clipped a bit. Turning on Air Resistance fixes the problem.
![file_001](https://user-images.githubusercontent.com/8419308/28889054-0899e1fa-7780-11e7-8e78-b267cfd0b629.jpeg)
![file_000](https://user-images.githubusercontent.com/8419308/28889053-0894d714-7780-11e7-91e1-a75b2377b86a.jpeg)

The same issue effects the 'g' in Drag Coefficient on the Intro screen, but not on Vectors.

The only test device this was observed on was the iPad 2, but @phet-steele also saw it on his external monitor. Perhaps it's related to low resolution?

**Comment by andrea-phet** [comment]
@arouinfar , the above commits fix the original issues, could you review and close?

**Comment by arouinfar** [comment]
Reviewed with @andrea-phet and it looks good.
