### ISSUE TITLE
Muzzle flash animation looks delayed

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#133]
Looking at master, it seems like the muzzle flash is still timed to appear when the projectile exits the muzzle.  @andrea-phet would it be possible to trigger the animation to start when fire is pressed, and finish up by the appearance of the 4th tracking dot or so.

**Comment by andrea-phet** [comment]
The animation did start, it's just the flame is so small and the animation is slow at the beginning, so I made adjustments to make it bigger and make the animation finish faster (by the 4th tracking dot). @arouinfar , what do you think?

**Comment by ariel-phet** [comment]
Since @arouinfar is on vacation, I took a look on master. Looks good to me. Closing
