### ISSUE TITLE
Change default projectile on Intro Screen to Pumpkin

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#134]
In reviewing master with @kathy-phet, we noticed that the default projectile is not deflected much when turning on Air Resistance.
![image](https://user-images.githubusercontent.com/8419308/29139843-951939fc-7d05-11e7-8e4a-c7ae9b22d718.png)

The pumpkin has a much clearer difference.
<img width="833" alt="screen shot 2017-08-09 at 1 27 46 pm" src="https://user-images.githubusercontent.com/8419308/29141073-f4d823cc-7d09-11e7-9bd5-08f2ab63d94e.png">

@andrea-phet can you please make the pumpkin the default option on the Intro screen?

**Comment by ariel-phet** [comment]
Since @arouinfar is on vacation, I looked. Looks good to me. Closing
