### ISSUE TITLE
Normal/Slow radio buttons a bit large

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#136]
@andrea-phet the normal and slow motion radio buttons look a bit large. Can you make the radius of these radio buttons match the radius of for instance of the "Total" and "Components" radio buttons?

**Comment by ariel-phet** [comment]
@andrea-phet I also think all the checkboxes could be reduced in size by 1 pixel or so.

**Comment by phet-steele** [comment]
@ariel-phet the checkboxes look to be the same size as the tweaker arrows (maybe). I used the straight-edge of the tracer tool to basically confirm they are the same width at least. Should those be reduced in size too? I sort of like the look of them being the same, but it may not matter.

<img width="59" alt="screen shot 2017-08-11 at 10 29 45 am" src="https://user-images.githubusercontent.com/5863899/29222572-3d3ac3dc-7e80-11e7-9a2f-f0d639967ca9.png">

**Comment by andrea-phet** [comment]
@ariel-phet I made the normal and slow motion radio buttons match total and components radio buttons, reduced the checkboxes by 3 px, and scaled the arrow buttons to match. How does that look?

**Comment by phet-steele** [comment]
@ariel-phet, everything is still easy to press with touch after these changes.

**Comment by ariel-phet** [comment]
Looks great, closing
