### ISSUE TITLE
A handful of objects have the wrong rotation when fired at 0 degrees

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#137]
1. Intro or Lab screen.
2. This is easiest to see when the sim is paused...so pause it!
3. Set the cannon to 0 degrees.
4. Choose either the Tank shell, Football, Human, or Car and fire!

At that moment, those objects will be rotated downwards:

<img width="825" alt="screen shot 2017-08-11 at 10 40 36 am" src="https://user-images.githubusercontent.com/5863899/29223074-73317e98-7e82-11e7-9e60-32e1e4721c6b.png">
<img width="625" alt="screen shot 2017-08-11 at 10 42 53 am" src="https://user-images.githubusercontent.com/5863899/29223077-7337fa34-7e82-11e7-88fc-2bfec29a7c76.png">
<img width="194" alt="screen shot 2017-08-11 at 10 43 07 am" src="https://user-images.githubusercontent.com/5863899/29223075-7332d324-7e82-11e7-858f-c8a114b326ab.png">
<img width="246" alt="screen shot 2017-08-11 at 10 43 27 am" src="https://user-images.githubusercontent.com/5863899/29223076-7334ebc8-7e82-11e7-8ea6-8d304ef6241c.png">

At non-0 angles, the objects are rotated correctly (Car as an example):

<img width="805" alt="screen shot 2017-08-11 at 10 41 13 am" src="https://user-images.githubusercontent.com/5863899/29223090-81059036-7e82-11e7-942c-df8f2f4912ec.png">

Stepping or resuming corrects the rotation. Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/35.

URL: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.9/projectile-motion_en.html
Version: 1.0.0-dev.9 2017-08-11 01:23:16 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"2545ad65","branch":"master"},"babel":{"sha":"5e2929c9","branch":"master"},"brand":{"sha":"90738131","branch":"master"},"chipper":{"sha":"3042728b","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"e3c3c82f","branch":"master"},"kite":{"sha":"dc5c4382","branch":"master"},"phet-core":{"sha":"6bfeef5c","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"projectile-motion":{"sha":"f368607f","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"7414c4fa","branch":"master"},"scenery-phet":{"sha":"1c796ce1","branch":"master"},"sherpa":{"sha":"be8e800b","branch":"master"},"sun":{"sha":"b5554519","branch":"master"},"tandem":{"sha":"74233a04","branch":"master"}}

**Comment by andrea-phet** [comment]
Should be fixed now.

**Comment by phet-steele** [comment]
Fixed in dev.10.
