### ISSUE TITLE
Tracer tool is not precise enough to measure the apex

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#138]
@andrea-phet, don't get me wrong! We want the tracer tool to not be too precise so it is easy to measure dots from a decent distance away. However, when dots are very close together, it becomes impossible to measure the desired dot. Specifically, it is impossible to measure the apex in 99% of scenarios with tightly spaced dots.

1. Intro screen, aim cannon straight up.
2. Fire.
3. Good luck measuring the apex! (I can't).

I'm stuck measuring points around the apex, but can never get an apex reading. This behaviour improves as the angle gets smaller, but 85 degrees is still pretty tough. @ariel-phet @arouinfar I don't know what exactly to do about this. I feel we would need special case code for the apex dot....but it's sort of a catch 22. Too much precision in these cases make it harder to measure in other cases.

![prmo03](https://user-images.githubusercontent.com/5863899/29224551-0b331ac6-7e88-11e7-8b56-21911efc209d.gif)

Seen on macOS 10.12.6 Chrome. For phetsims/QA#35.

URL: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.9/projectile-motion_en.html
Version: 1.0.0-dev.9 2017-08-11 01:23:16 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"2545ad65","branch":"master"},"babel":{"sha":"5e2929c9","branch":"master"},"brand":{"sha":"90738131","branch":"master"},"chipper":{"sha":"3042728b","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"e3c3c82f","branch":"master"},"kite":{"sha":"dc5c4382","branch":"master"},"phet-core":{"sha":"6bfeef5c","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"projectile-motion":{"sha":"f368607f","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"7414c4fa","branch":"master"},"scenery-phet":{"sha":"1c796ce1","branch":"master"},"sherpa":{"sha":"be8e800b","branch":"master"},"sun":{"sha":"b5554519","branch":"master"},"tandem":{"sha":"74233a04","branch":"master"}}

**Comment by andrea-phet** [comment]
I made a change such that if the apex point is within the sensing radius around the tracer, the apex point will be highlighted. That effectively prioritizes the apex point, which means that the tracer would not sense other dots that are within sensing radius around the apex point. I think this trade off is worth it, @ariel-phet @phet-steele after playing with it, what do you think?

**Comment by phet-steele** [comment]
It is indeed a tradeoff since now I can't reliably get points around the apex. It might be worth it. Leaving @ariel-phet and @arouinfar to review/suggest anything.

**Comment by ariel-phet** [comment]
I think this solution is working nicely. The apex is sort of a "critical point" for physics problems so it seems worth prioritizing. In the normal use case of a parabolic trajectory I can get points near the apex fairly easily.
