### ISSUE TITLE
Top and bottom grass

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/projectile-motion#139]
Some documentation on when/if both of these are needed would be helpful. To me, it looks like the bottomGrass (which is visually on top!) is a smaller rectangle than topGrass (and bottomGrass could be potentially removed since there is nothing inbetween?)

**Comment by andrea-phet** [comment]
Good catch. Top grass and bottom grass used to be two different colors, but now that design team has decided they are the same color, they can just  be part of one grass.

**Comment by jonathanolson** [comment]
Looks good, thanks!
