### ISSUE TITLE
Screenshot for 1.0

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/projectile-motion#140]
@phet-steele will do when ready. @arouinfar please make any suggestions for what you would like it be.

**Comment by arouinfar** [comment]
@phet-steele @andrea-phet here are a few options. I quite like (1) and (2). Any thoughts?

1.  ![image](https://user-images.githubusercontent.com/8419308/29284520-5ee54808-80e8-11e7-820f-ba7019a1c570.png)
2.  <img width="1126" alt="screen shot 2017-08-14 at 11 45 10 am" src="https://user-images.githubusercontent.com/8419308/29284304-59952d1a-80e7-11e7-872b-5599f678adef.png">
3.  <img width="1126" alt="screen shot 2017-08-14 at 11 44 54 am" src="https://user-images.githubusercontent.com/8419308/29284301-599230e2-80e7-11e7-81ad-f39eca2b518b.png">
4.  <img width="1126" alt="screen shot 2017-08-14 at 11 44 25 am" src="https://user-images.githubusercontent.com/8419308/29284302-5993e04a-80e7-11e7-82df-ab26c634d4d1.png">

**Comment by andrea-phet** [comment]
Me too, 1 and 2 are really nice. I also like 4.

**Comment by andrea-phet** [comment]
Would 2 be too hectic if we included the stars?

**Comment by pixelzoom** [comment]
@phet-steele RC testing resulted in no UI changes (see https://github.com/phetsims/QA/issues/39) so I think you're cleared to create the screenshot whenever you have time.

**Comment by pixelzoom** [comment]
@phet-steele RC testing resulted in no UI changes (see https://github.com/phetsims/QA/issues/39) so I think you're cleared to create the screenshot whenever you have time. Please push to master and 1.0 branches.

**Comment by phet-steele** [comment]
Done!
