### ISSUE TITLE
should the tracer tool be draggable by its probe?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#141]
Discovered while making the screenshot shown in https://github.com/phetsims/projectile-motion/issues/135#issuecomment-322525352.

I tried to drag the tracer tool by it's probe, which I think is a natural thing to do if you want to put the probe on a specific location.  But I discovered that you can only move it by dragging the body of the tool.

In case I have the terminology wrong, this is what the code refers to as the tracer tool:

![screenshot_352](https://user-images.githubusercontent.com/3046552/29326699-d015f42a-81a9-11e7-8eea-61bed6542300.png)

**Comment by arouinfar** [comment]
@pixelzoom I really like this suggestion! It does seem like a natural place to drag the tool, so please go ahead and make this change @andrea-phet.

**Comment by pixelzoom** [comment]
@andrea-phet somewhat related to this, in TracerNode:

```js
111    // @public Should be added as a listener by our parent when the time is right
112    this.movableDragHandler = new MovableDragHandler( tracer.positionProperty, {
...
123    // When dragging, move the tracer tool
124    rectangle.addInputListener( this.movableDragHandler );
```

The comment on line 111 seems incorrect.  The listener is added on line 124, and `movableDragHandler` is only public so that events can be forwarded to it by ToolboxPanel.

**Comment by pixelzoom** [comment]
Here's the patch to implement this.  Deltas are indicated by + and - in the leftmost column.

---
Index: js/common/view/TracerNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/TracerNode.js	(revision 7af73b937d2e1caf814bed69f9ab6cb0d2ddeeab)
+++ js/common/view/TracerNode.js	(revision )
@@ -73,6 +73,11 @@
    * @constructor
    */
   function TracerNode( tracer, transformProperty, screenView, options ) {
+
+    options = _.extend( {
+      cursor: 'pointer'
+    }, options );
+
     var self = this;
     
     // @public is this being handled by user?
@@ -92,9 +97,7 @@
         fill: OPAQUE_BLUE,
         stroke: 'gray',
         lineWidth: 4,
-        opacity: 0.8,
-        pickable: true,
-        cursor: 'pointer'
+        opacity: 0.8
       }
     );
 
@@ -120,9 +123,6 @@
       }
     } );
 
-    // When dragging, move the tracer tool
-    rectangle.addInputListener( this.movableDragHandler );
-
     // crosshair view
     var crosshairShape = new Shape()
       .moveTo( -CIRCLE_AROUND_CROSSHAIR_RADIUS, 0 )
@@ -224,7 +224,6 @@
       self.tracer.updateData();
     } );
 
-    options = options || {};
     assert && assert( !options.children, 'this type sets its own children' );
 
     // Rendering order
@@ -239,6 +238,9 @@
 
     Node.call( this, options );
 
+    // When dragging, move the tracer tool
+    this.addInputListener( this.movableDragHandler );
+
     // visibility of the tracer
     tracer.isActiveProperty.link( function( active ) {
       self.visible = active;

**Comment by andrea-phet** [comment]
Oh, thanks @pixelzoom I didn't see your comment until after the commit above.

**Comment by andrea-phet** [comment]
Assigning to @arouinfar to review.

**Comment by arouinfar** [comment]
👍

**Comment by pixelzoom** [comment]
Reopening. 

Works great, but the implementation is a little non-standard.  Since the entire TracerNode is now draggable, it would be preferable to (1) add the drag handler to the entire node (after `Node.call`), instead of the probe and panel separately, (2) set `cursor: 'pointer'` on the TracerNode (via `options` passed to `Node.call`), rather than its components.

**Comment by pixelzoom** [comment]
It's also unnecessary to set `pickable: true` for `rectangle`.  Calling `addInputListener` automatically makes a Node pickable.

**Comment by andrea-phet** [comment]
There's just one thing: the halo that highlights the dot that the tracer tool is on is a child of TracerNode. I don't want that draggable, which is why I only pick circle and rectangle to drag.

**Comment by pixelzoom** [comment]
If you want to be totally safe and independent of rendering order, set `pickable: false` explicitly on `haloNode`.  But with the current rendering order, halo is always behind `circle`, which is filled with `TRANSPARENT_WHITE`.  So `haloNode` itself will not receive events.

**Comment by andrea-phet** [comment]
Oh yeah, good point.

**Comment by pixelzoom** [comment]
Looks great.  I restored the `!options.children` assertion in the above commit, you probably deleted that unintentionally.   Feel free to close after reviewing.

**Comment by andrea-phet** [comment]
Okay, closing.
