### ISSUE TITLE
Object snaps to apex point when stepped through an old trajectory, causing non-constant velocity

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#144]
1. Press fire to create a trajectory ***with an apex point***. Do this without AR so it is easier to verify the bug later. I recommend:
- Screen: Vectors
- Height: 4 m
- I. Speed: 15 m/s
- Angle: 5 degrees
2. Let this trajectory go to completion.
3. Zoom all the way in so this is easier.
4. Pause the sim and fire, with the same trajectory parameters.
5. Before the object gets too far, use the tape measurer to measure the x distance the object moves in ONE time step. Now, if I remember my physics, an object moving without AR will have a constant x velocity, meaning the object should travel the same x distance on every time step (assuming the time steps are equal, which they should be).

After one step, distance for me was 0.45 meters:
<img width="572" alt="screen shot 2017-08-17 at 3 52 35 pm" src="https://user-images.githubusercontent.com/5863899/29435554-b9b541d8-8364-11e7-83a2-a22052425b03.png">

6. Step the sim once more to verify that the object moved the same distance you measured earlier.

After second step, same distance traveled:
<img width="559" alt="screen shot 2017-08-17 at 3 52 59 pm" src="https://user-images.githubusercontent.com/5863899/29435555-b9b56712-8364-11e7-8005-ef2e8273b62e.png">

7. Keep stepping until the step prior to crossing the apex point (where one more step would send you past the apex). Get ready to measure how far the object travels on the next step!.....

Oh man...one more step here we go!
<img width="566" alt="screen shot 2017-08-17 at 3 53 40 pm" src="https://user-images.githubusercontent.com/5863899/29435556-b9b5b4ba-8364-11e7-8db6-5622addf4b43.png">

8. .....It didn't travel very far did it? Instead, the object snaps to the apex point. One more step and you'll see it will complete the total distance it should have gone. In other words, the x distance travelled was NOT constant with each time step.

Next step snaps to apex, not even close to the full 0.45 meters:
<img width="574" alt="screen shot 2017-08-17 at 3 53 54 pm" src="https://user-images.githubusercontent.com/5863899/29435558-b9b6c2ba-8364-11e7-96ce-dab58409f4f9.png">

Then next step finishes the prescribed distance:
<img width="552" alt="screen shot 2017-08-17 at 3 54 04 pm" src="https://user-images.githubusercontent.com/5863899/29435557-b9b66770-8364-11e7-8acb-5b5b270b4834.png">

I'll reiterate, this will NOT happen on a trajectory being drawn for the first time. You MUST be firing an object along an already drawn ("old") trajectory, so step 2 is mighty important (you might be able to repro this in mid-air, but I haven't tried).

Seen on Win 10 FF and macOS 10.12.6 Chrome. For phetsims/QA/issues/39.

URL: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-rc.1/projectile-motion_en.html
Version: 1.0.0-rc.1 2017-08-16 00:04:04 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"b7268ab0","branch":"HEAD"},"babel":{"sha":"d436176d","branch":"master"},"brand":{"sha":"90738131","branch":"HEAD"},"chipper":{"sha":"bccad091","branch":"HEAD"},"dot":{"sha":"f7d9de8b","branch":"HEAD"},"joist":{"sha":"7d518ed4","branch":"HEAD"},"kite":{"sha":"dc5c4382","branch":"HEAD"},"phet-core":{"sha":"6bfeef5c","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"projectile-motion":{"sha":"77666df9","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"41bc57fb","branch":"HEAD"},"scenery-phet":{"sha":"4a9502e1","branch":"HEAD"},"sherpa":{"sha":"7be57a56","branch":"HEAD"},"sun":{"sha":"7b2c6f33","branch":"HEAD"},"tandem":{"sha":"74233a04","branch":"HEAD"}}

**Comment by pixelzoom** [comment]
@andrea-phet slacked me that this is a quick fix, so I won't bother to investigate.  This will require another RC, but (like #143) not a full test matrix.  Be sure to make the change in master and 1.0 branches.

**Comment by andrea-phet** [comment]
I made a fix in master and 1.0. @phet-steele could you check?

**Comment by pixelzoom** [comment]
I inspected the implementation of this fix.  It is isolated to 1 file, consists of a couple of lines of code, and contains nothing that is platform dependent.  So it can be verified in 1.0.0-rc.2 with spot testing, full test matrix not required.

**Comment by pixelzoom** [comment]
This issue is ready for regression testing in 1.0.0-rc.2.

**Comment by phet-steele** [comment]
Fixed, closing.
