### ISSUE TITLE
measuring tape becomes difficult to access

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#145]
Related to https://github.com/phetsims/QA/issues/39

When using the zoom buttons, the measuring tape can become difficult to drag, requiring 2 steps to move it.

To reproduce:

1. Start the sim
2. Go to any screen (Intro screen is used in screenshots below)
3. Pull the measuring tape out of the toolbox, and position as shown:

![screenshot_360](https://user-images.githubusercontent.com/3046552/29467324-440c5e14-83fd-11e7-8fc9-105d6ee8d98f.png)

4. Press the "zoom in" (+) button.
5. Note that the measuring tape is now in the far upper-right corner, like this:

![screenshot_361](https://user-images.githubusercontent.com/3046552/29467323-41af6d3c-83fd-11e7-9699-b1d24a80b082.png)

6. Try to grab the measuring tape. The only piece that's grabbable at this point is the tip.  Drag it and you'll end up with something like this:

![screenshot_362](https://user-images.githubusercontent.com/3046552/29467372-85cfbe0e-83fd-11e7-853f-01afa75e8d18.png)

7. Now you can grab the body and move it, resulting in something like this:

![screenshot_363](https://user-images.githubusercontent.com/3046552/29467395-9e99ea18-83fd-11e7-951d-b0c36a7944b8.png)

**Comment by pixelzoom** [comment]
I don't think that the measuring tape's text should be made draggable.  That would require changes to common code, open a whole can of worms.  And it would be a workaround rather than a proper solution.  

PhET sims typically constrain objects so that they can't be dragged off of the screen (which this sim does).  And when a zoom feature is available, most (all?) PhET sims ensure that interactive objects remain accessible.  In this case, I don't consider the measuring tape to be properly accessible - a clearly visible portion of the measuring tape's body should remain visible, similar to what is currently done for the tracer tool.

**Comment by pixelzoom** [comment]
I said:
> PhET sims typically constrain objects so that they can't be dragged off of the screen - which this sim does nicely. 

Looks like this is actually _not_ the case for this sim, it's not handling dragging of the measuring tape properly.   At any of the 4 corners of the ScreenView's layoutBounds, I can drag the measuring tape so that only part of the '+' on the tape's body is visible, and (depending on orientation) part of the '+' on the tape's tip.  For example:

![screenshot_364](https://user-images.githubusercontent.com/3046552/29467990-b54a6fd8-83ff-11e7-9097-e7bd828cbce4.jpg)

**Comment by arouinfar** [comment]
> In this case, I don't consider the measuring tape to be properly accessible - a clearly visible portion of the measuring tape's body should remain visible, similar to what is currently done for the tracer tool.

I completely agree @pixelzoom. 

@andrea-phet please update the tape measure's behavior so that the its body is always constrained to the visible part of the sim to avoid the behavior described by @pixelzoom in https://github.com/phetsims/projectile-motion/issues/145#issue-251292683 and https://github.com/phetsims/projectile-motion/issues/145#issuecomment-323399449

**Comment by pixelzoom** [comment]
@arouinfar said:
> @andrea-phet please update the tape measure's behavior so that the its body is always constrained to the visible part of the sim

I think we're OK if even some _portion_ (clearly visible, easily grabbed) of the body is always visible, similar to the tracer tool.  @arouinfar do you agree?

**Comment by pixelzoom** [comment]
To further clarify...  Constraining the _entire_ body to remain visible may be problematic, since I don't believe that the bounds of the body are accessible via MeasuringTapeNode (a common-code component).

**Comment by arouinfar** [comment]
> I think we're OK if even some portion (clearly visible, easily grabbed) of the body is always visible, similar to the tracer tool. @arouinfar do you agree?

Agreed @pixelzoom. Apologies for the ambiguity in my earlier comment.

**Comment by pixelzoom** [comment]
@andrea-phet asked me to take a stab at fixing this, using existing features of `MeasuringTapeNode`.  I tried one approach (first set of commits), but then thought of a better way to handle this.  So review the last 2 commits above, ignore the others. 

Note that MeasuringTapeNode ensures that both its body _and_ tip remain visible inside the drag bounds. So if you grab the measuring tape by the body, and drag it towards the edge of the screen, you will see the tip retract as the tip reaches the edges of the drag bounds.  I cannot change this behavior without modifying MeasuringTapeNode.  And it seems reasonable in this context.

@andrea-phet @phet-steele please have a look.

**Comment by arouinfar** [comment]
> So if you grab the measuring tape by the body, and drag it towards the edge of the screen, you will see the tip retract as the tip reaches the edges of the drag bounds.

That sounds reasonable to me @pixelzoom.

**Comment by pixelzoom** [comment]
@arouinfar also feel free to take a look.

To clarify how I solved this... The measuring tape was previously constrained to the entire visible "play area".  I'm now reducing that bounds by 20 units on all 4 edges of the play area.  This ensures that a sizable portion of the measuring tape remains visible and grabbable.  That "20" value can be adjusted, but felt about right to me.

**Comment by andrea-phet** [comment]
Thanks @pixelzoom. Also, I like that the solution doesn't need to change common code.

**Comment by arouinfar** [comment]
I like it @pixelzoom! Looked good to @phet-steele too.

**Comment by pixelzoom** [comment]
Excellent. This will require a spot check in 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
@andrea-phet Leaving this assigned to you. When you create the GitHub issue for testing 1.0.0-rc.2, note that this issue needs to be regression tested in that issue.

**Comment by phet-steele** [comment]
@andrea-phet, don't mind me being nosey, but generally we keep tools (and everything else) behind the ResetAllButton so it can always be pressed. The above commit ruins that, should probably be changed.

**Comment by pixelzoom** [comment]
@phet-steele said:
> generally we keep tools (and everything else) behind the ResetAllButton so it can always be pressed. 

Not the case "generally".  See for example Function Builder (function cards), Beer's Law Lab (probes), and pH Scale (probe).

But yes, perhaps appropriate for this sim.

**Comment by pixelzoom** [comment]
On second thought, I think having the tools on top of everything is fine in this sim.

**Comment by pixelzoom** [comment]
On second thought, I think having the tools on top of everything is fine in this sim.  My recommendation is to leave "as is".

**Comment by pixelzoom** [comment]
The 3 reasons (in general) for not putting the Reset All button in front of interactive objects are:

(1) Reset All button may obscure the interactive object, making it impossible to access, and requiring a Reset All to continue.  For example, the charges in charges-and-field.

(2) Reset All button may be mistaken for a control on the interactive object. 

(3) Reset All button is shared by subtypes in the sim's ScreenView hierarchy.  This is typically the case for screens whose Reset All button is in a similar location, and resets a similar model and/or view.   Adding the Reset All button in the supertype prevents code duplication.  Since ScreenView subtypes typically require access to `this.layoutBounds`, the supertype constructor must be called before adding additional UI components, which results in the Reset All button being in a "lower" layer.  So while it's not impossible to put the Reset All button in the foreground in this scenario, it's a significant implementation complication, with questionable benefits.

**Comment by pixelzoom** [comment]
This issue is ready for regression testing in 1.0.0-rc.2.

**Comment by lmulhall-phet** [comment]
Fixed. Closing.
