### ISSUE TITLE
Tape measurer should not drop into tool box based on anything but the blue/yellow body

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#146]
@pixelzoom this is what you did yesterday at status meeting.

It is a bit unwieldy and, in my opinion, a poor UX to have the tape measurer drop into the carousel in its current implementation. Entirely demonstrated in the below video, dropping the body of the tool in a location that places the extendable end into the tool box will dismiss the tool, independent of the body's location:
![prmo04](https://user-images.githubusercontent.com/5863899/29468392-43f0aa80-8401-11e7-9b58-55428a223da8.gif)

This easily leads to undesirable behaviour. Ideally, the tool should only be dismissed if the BODY is released over the tool box. @arouinfar @pixelzoom @andrea-phet please feel free to give your opinions on this matter.

Seen on macOS 10.12.6 Chrome. For phetsims/QA#39.

URL: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-rc.1/projectile-motion_en.html
Version: 1.0.0-rc.1 2017-08-16 00:04:04 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"b7268ab0","branch":"HEAD"},"babel":{"sha":"d436176d","branch":"master"},"brand":{"sha":"90738131","branch":"HEAD"},"chipper":{"sha":"bccad091","branch":"HEAD"},"dot":{"sha":"f7d9de8b","branch":"HEAD"},"joist":{"sha":"7d518ed4","branch":"HEAD"},"kite":{"sha":"dc5c4382","branch":"HEAD"},"phet-core":{"sha":"6bfeef5c","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"projectile-motion":{"sha":"77666df9","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"41bc57fb","branch":"HEAD"},"scenery-phet":{"sha":"4a9502e1","branch":"HEAD"},"sherpa":{"sha":"7be57a56","branch":"HEAD"},"sun":{"sha":"7b2c6f33","branch":"HEAD"},"tandem":{"sha":"74233a04","branch":"HEAD"}}

**Comment by phet-steele** [comment]
Okay, doesn't have to be the end that is over the tool box. Any part of the tool can be over the tool box to make the tool eligible for dropping. Here, just the gray path is over the tool box when releasing the body:

![prmo05](https://user-images.githubusercontent.com/5863899/29468669-7755d386-8402-11e7-97bd-9967b6362df9.gif)

**Comment by pixelzoom** [comment]
I haven't looked closely at the code.  But I'm guessing that the measuring tape is put back in the toolbox if any portion of the MeasuringTapeNode bounds (which includes all part of the tool) overlaps the toolbox's bounds.   Unfortunately, MeasuringTapeNode (common code) does not currently have support for getting the bounds of just the body - that will require changes to common code (scenery-phet).  And changes to common code will require another RC with full test matrix.

I agree that this should be addressed, and it should be addressed by enhancing MeasuringTapeNode.  But unless there's another issue that requires a full RC test, I recommend deferring this to a further release.

**Comment by pixelzoom** [comment]
I said:
> I agree that this should be addressed, and it should be addressed by enhancing MeasuringTapeNode. But unless there's another issue that requires a full RC test, I recommend deferring this to a further release.

@arouinfar your opinion?

**Comment by arouinfar** [comment]
> I agree that this should be addressed, and it should be addressed by enhancing MeasuringTapeNode. But unless there's another issue that requires a full RC test, I recommend deferring this to a further release.

Sounds reasonable to me @pixelzoom! The tape measure is not a heavily-used tool, so this issue seems mildly annoying. While it should be addressed, I think it could be deferred to a maintenance release/after 1.0.

**Comment by pixelzoom** [comment]
@andrea-phet Hold off on fixing this one until 1.0.0-rc.1 testing is further along.  If there are no other issues that require a full re-test, then this issue will likely be deferred to a future release.

**Comment by phet-steele** [comment]
@pixelzoom said,
>Unfortunately, MeasuringTapeNode (common code) does not currently have support for getting the bounds of just the body...


I was testing charges-and-fields today. It has a measuring tape that behaves exactly as desired in this issue. The implementation in `ChargesAndFieldsScreenView.js` that is responsible for the behavior is at line 312:
```js
measuringTapeNode.isBaseUserControlledProperty.link( function( isBaseUserControlled ) {
      var tapeBaseBounds = measuringTapeNode.localToParentBounds( measuringTapeNode.getLocalBaseBounds() );
      if ( !isBaseUserControlled && toolboxPanel.bounds.intersectsBounds( tapeBaseBounds.eroded( 5 ) ) && isDisplayed( toolboxPanel ) ) {
        model.measuringTape.isActiveProperty.set( false );
      }
    } );
```

I followed this bread crumb to scenery-phet where I saw this public function in `MeasureingTapeNode.js` at line 445:
```js
getLocalBaseBounds: function() {
      return this.baseImage.bounds.copy();
    },
```
Would this function not do the trick, or at least could we adapt the implementation charges-and-fields uses?

**Comment by pixelzoom** [comment]
I stand corrected, MeasuringTapeNode has `getLocalBaseBounds`, which is what is being used in charges-and-fields.  This could presumably be used in projectile-motion, with no common-code changes required.

**Comment by pixelzoom** [comment]
This was a 1-line fix that I'm sure @andrea-phet would have ably handled. But I went ahead and did it.  @phet-steele please verify, @andrea-phet please review the above commit.

**Comment by andrea-phet** [comment]
Likes good to me.

**Comment by pixelzoom** [comment]
Via slack, @phet-steele said he looked at this and approves. 

This issue is ready for regression testing in 1.0.0-rc.2.

**Comment by phet-steele** [comment]
Fixed, closing. Thanks @pixelzoom!
