### ISSUE TITLE
User suggestion: measure should snap to path points

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#148]
> There is no problem but I just wanted to say that when you drag the things onto the screen they should "snap" to the grid lines. As in the dots should immediatley move to a lattice point when you let go of the mouse.

This may be a necessary feature for future keyboard navigation of the sim.

**Comment by arouinfar** [comment]
@oliver-phet are you sure this is for Projectile Motion? Sounds more like a Charges and Fields issue...

**Comment by oliver-phet** [comment]
whoops! https://github.com/phetsims/charges-and-fields/issues/134
