### ISSUE TITLE
User suggestion: Control energy rather than initial speed

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#149]
> The new version is nice, yet I think none accounts for the physical fact that different masses should be projected with different initial speed. 
Thus, I guess that being able to control the energy supply instead of the initial speed would be a good idea to explore.
At this point selecting different objects is fine, as long as they have the same masses.
I usually make my students aware of the small inconsistency.

**Comment by arouinfar** [comment]
@oliver-phet the HTML5 behavior is in line with Flash. The design is meant to support learning goals around controlling the initial conditions, and in typical physics problems, the initial speed (not energy) of the projectile is one of those initial conditions. 

> none accounts for the physical fact that different masses should be projected with different initial speed

Sounds like the user is interested in the mechanics of a cannon itself. They are correct -- all things being equal, shooting two cannonballs with different mass would have different initial speeds.

> At this point selecting different objects is fine, as long as they have the same masses. I usually make my students aware of the small inconsistency.

One of the learning goals for projectile motion is that, in the absence of air resistance, and given the same initial height and speed, projectiles with different masses will have the exact same path. The behavior of the sim is not incorrect, but perhaps divergent from the user's specific goals. 

An initial kinetic energy slider would perhaps be appropriate on a screen focused on energy conservation, but that is beyond the scope of the learning goals of the sim.

Back to @oliver-phet to reply to the user and close.

**Comment by oliver-phet** [comment]
Reply to user sent. Closing.
