### ISSUE TITLE
Use `this` where appropriate

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#15]
It would be better to use `this` instead of `self` where possible to make the code clearer.  For instance:

``` js
  /**
   * @param {Score} scoreModel - model of the target and scoring algorithms
   * @param {ModelViewTransform2} modelViewTransform
   * @constructor
   */
  function TargetNode( scoreModel, modelViewTransform ) {
    var self = this;
    Node.call( self );
```

**Comment by pixelzoom** [comment]
To clarify...  There's nothing inherently wrong with using `self` as a general alias for `this`.  But PhET convention is to use `self` only when it's necessary, typically in a closure.

**Comment by samreid** [comment]
@andrea-phet the convention for PhET GitHub issues is that after the developer addresses the issue, the issue should be reassigned back to the original reporter (with a ready-for-review label) so the original reporter can double check everything or see if any related issues come to mind.  This process works nicely for design team issues as well as code review issues.

**Comment by samreid** [comment]
I checked the remaining `self` references and they all seem good (I did see one commented out `self` but it is marked with a TODO).  Closing.
