### ISSUE TITLE
User reported issue: freeze/restart

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#155]
Originally created here: https://github.com/phetsims/phet-ios-app/issues/290#issuecomment-333663773

We have replicated on KP's iPad 4 (using the app, Chrome, and Safari)

> I bought the iPad app for my Projectile Motion simulation (among other things), but the simulation crashes every time and reload especially when I'm changing the angles.

Here is the device output:

Test device: iPad 4

Operating System: iOS10.3

Browser: Safari

Problem description: For projectile motion, it crashes when changing angles. 

Steps to reproduce:

Severity:

Screenshots: crash, so blank page and reloaded back to start. 

Troubleshooting information (do not edit):
Name: ‪Pendulum Lab‬
URL: https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_en.html
Version: 1.0.0 2017-09-13 20:14:34 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
Language: en-GB
Window: 980x643
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX554-129)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"24c942a4","branch":"HEAD"},"babel":{"sha":"01028f3d","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"c6ebc753","branch":"HEAD"},"dot":{"sha":"db33a2c7","branch":"HEAD"},"joist":{"sha":"c3db16bc","branch":"HEAD"},"kite":{"sha":"dc5c4382","branch":"HEAD"},"pendulum-lab":{"sha":"5f8a5792","branch":"HEAD"},"phet-core":{"sha":"6bfeef5c","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"5f5f8611","branch":"HEAD"},"scenery-phet":{"sha":"7b214b9d","branch":"HEAD"},"sherpa":{"sha":"8a5d6d7f","branch":"HEAD"},"sun":{"sha":"9820ea30","branch":"HEAD"},"tandem":{"sha":"37243b99","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@jonathanolson please review and advise:

The above issue was found to be reproducible in the PhET iOS App and on mobile Safari with an important caveat:

- So far, only iPad 4, iOS 10.3.3

An iPad Air 2 with the same iOS and the same Webkit version would NOT show the problem.

To reproduce:

1. Load the sim and _extremely quickly_ enter the Drag screen and move the target (or change the cannon angle). Waiting even a few seconds to do both of these will not throw an error.

When doing this, the error that is given is:

```
TypeError: mutableBounds.constrainBounds is not a function. (In ‘mutableBounds.constrainBounds( this.node._clipArea.bounds )‘, ‘mutableBounds.constrainBounds’ is 7.950983319972023e+78)
    applyAreasAndTransform (Picker.js:425)
    validateTouchExclusive (Picker.js:401)
    validateTouchExclusive (Picker.js:393)
    hitTest (Picker.js:119)
    branchChangeEvents (Input.js:674)
    validatePointers (Input.js:733)
    updateDisplay (Display.js:316)
    stepSimulation (Sim.js:849)
    runAnimationLoop (Sim.js:772)
    runAnimationLoop
```

Note, we also made this happen in bending-light by:

- Loading the sim and _extremely quickly_ entering the Intro screen and wiggling the laser.

**Comment by jonathanolson** [comment]
@phet-steele, can you test http://www.colorado.edu/physics/phet/dev/olsonjb/projectile-motion-freeze.html while tethered, and see if it throws an error (as discussed before)?

Contains the swapped code:
```js
get constrainBounds() {
  return function( bounds ) {
    return this.setMinMax(
      Math.max( this.minX, bounds.minX ),
      Math.max( this.minY, bounds.minY ),
      Math.min( this.maxX, bounds.maxX ),
      Math.min( this.maxY, bounds.maxY )
    );
  };
},
set constrainBounds( value ) {
  if ( typeof value !== 'function' ) {
    throw new Error( 'constrainBounds should not be set to a non-function' );
  }
},
```

**Comment by phet-steele** [comment]
@ariel-phet @oliver-phet I worked with JO and SR to arrive at the workaround above and verified it fixed the issue then.

@ariel-phet how would you like to proceed? Should we do a maintenance version? Do we need to submit a bug report to apple? Not sure how much that will help.

**Comment by ariel-phet** [comment]
@phet-steele a maintenance version would be appropriate in this case. Agreed that probably not worth the apple bug report. 

@jonathanolson is this a maintenance release that would not be too onerous to perform?

**Comment by jonathanolson** [comment]
> @jonathanolson is this a maintenance release that would not be too onerous to perform?

If it needs to hit phet-io, it's more time-consuming (and I'd probably want to start looking into automated deploys to phet-io). If it's not phet-io, it's in fairly stable code.

**Comment by ariel-phet** [comment]
@jonathanolson I don't see why this would need to hit phet-io unless this an LoL sim.

@phet-steele any insight?

**Comment by phet-steele** [comment]
> @jonathanolson I don't see why this would need to hit phet-io unless this an LoL sim.
> 
> @phet-steele any insight?

This sim has no phet-io version, and LoL (which this sim has been tested for) has nothing to do with phet-io (it's in joist).

@jonathanolson this can be treated like a normal phet maintenance release, though should probably wait and get changes from phetsims/joist/issues/447.

**Comment by jonathanolson** [comment]
Oh, I just realized (I think) you mean the common-code fix would only be deployed as a maintenance release for this sim?

Generally a maintenance release for a single sim is fine even with phet-io.

I've added this to my list.

**Comment by pixelzoom** [comment]
While working on https://github.com/phetsims/projectile-motion/issues/158, I was asked to roll this fix into a maintenance release.  This resulted in a lot of head scratching and I ultimately bailed. 

See https://github.com/phetsims/projectile-motion/issues/155#issuecomment-335059559. @jonathanolson why on earth did you build something with a bogus version id (1.1.0-dev.0) and manually copy it to your own private directory on spot?  Why didn't you publish a dev version for testing?

**Comment by pixelzoom** [comment]
Since there have been changes in master, I've labeled this as "in progress" so that other developers don't accidentally cherry pick this to a maintenance release.

**Comment by pixelzoom** [comment]
#158 maintenance release is in progress, and will not include this issue. Please hold off on this issue until #158 is closed.

**Comment by jonathanolson** [comment]
> See #155 (comment). @jonathanolson why on earth did you build something with a bogus version id (1.1.0-dev.0) and manually copy it to your own private directory on spot? Why didn't you publish a dev version for testing?

I didn't create 1.1.0-dev.0, it was done in https://github.com/phetsims/projectile-motion/commit/066431def207365ca81dded1a9532e2647ea947f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2.

For debugging things that potentially affect multiple simulations like this, I usually prefer to create standalone test versions (uploaded to my directory in spot) instead of bumping the version a ton of times and deploying with things like `--mangle=false` or `--uglify=false`.

I thought it was generally "unacceptable" to do a dev deploy with nonstandard options like above?

**Comment by pixelzoom** [comment]
> I didn't create 1.1.0-dev.0, it was done in 066431d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2.

package.json was reset when the 1.0 release branch was created, standard procedure.  You published 1.1.0-dev.0 - open the About dialog of your private version to confirm.

> I thought it was generally "unacceptable" to do a dev deploy with nonstandard options like above?

No idea that you used non-standard options, nothing in the issue to indicate that.   And I don't see a problem with that as long as it's noted in the issue.  Or if you're going to use your own procedure, at least note it and explain why.

**Comment by pixelzoom** [comment]
I also don't see a problem with publishing multiple dev versions to resolve an issue.  Imo it's preferable to using your own undocumented procedure.

**Comment by jonathanolson** [comment]
> No idea that you used non-standard options, nothing in the issue to indicate that. And I don't see a problem with that as long as it's noted in the issue. Or if you're going to use your own procedure, at least note it and explain why.

> I also don't see a problem with publishing multiple dev versions to resolve an issue. Imo it's preferable to using your own undocumented procedure.

So for all 12 of the versions I put up in an hour, I should be incrementing versions, committing temporary "guess" commits (having to get temporary hack tests to lint properly, and using throws instead of debugger), noting all of the options I used to build in the issue for every version?

That will definitely slow down debugging when the test device can't be on the same network as the development device.

**Comment by pixelzoom** [comment]
> So for all 12 of the versions I put up in an hour,

No idea that you put up 12 version in an hour. No idea how you were going about testing or troubleshooting this.  Which is why I choose to let you continue to handle it.   You put a link to exactly 1 version in this issue - what's the problem with publishing that as a dev version? That shouldn't affect your ability to iterate on your own, using whatever procedure you feel is most efficient.

**Comment by jbphet** [comment]
The fix for this is incorporated into https://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.2-rc.1/projectile-motion_en.html.  @phet-steele - please verify before we go live with this version.

**Comment by phet-steele** [comment]
Didn't break in the above link. Next step is to @oliver-phet to email, but not yet.

**Comment by jbphet** [comment]
The fix for this problem recommended by @jonathanolson was included in v1.0.2, which is now live on the web site.  I'm not sure what additional followup is necessary, so I'm assigning to @oliver-phet and @phet-steele to figure that out.

**Comment by oliver-phet** [comment]
@phet-steele has this fix been tested/verified?

**Comment by phet-steele** [comment]
> @phet-steele has this fix been tested/verified?

Yes, in rc.1, not in production. But the fix is included in production now, so we should be safe.

**Comment by oliver-phet** [comment]
User notified. Closing for now.
