### ISSUE TITLE
use MeasuringTapeNode's "transparent rectangle behind readout" feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#156]
Related to https://github.com/phetsims/scenery-phet/issues/339#issuecomment-333937396.

While adding a "white background" feature to MeasuringTapeNode, I noticed that MeasuringTapeNode makes `labelText` public, and projectile-motion uses it. 

@pixelzoom said:
>  Looks to me like projectile-motion is stroking the text for the same reason that we're trying to add a transparent background behind the value.   @arouinfar as lead designer for projectile-motion, do you recall if this is why the text is being stroked? And would it be OK to get rid of that and use a transparent white background?

@arouinfar replied:
> in Projectile Motion, the stroke around the `MeasuringTapeNode` readout was added as a band-aid because there was no support for a transparent background (see the 2nd screenshot in https://github.com/phetsims/scenery-phet/issues/339#issue-261781595). The stroke around the text can be killed and replaced with a transparent white background.

**Comment by pixelzoom** [comment]
I integrated the new "transparent rectangle behind readout" feature into this sim. Sample screenshot below. The rectangle color is currently ''rgba( 255, 255, 255, 0.2 )'' - white with 20% transparency. @arouinfar please review in master, let me know if you'd like anything changed.

![screenshot_404](https://user-images.githubusercontent.com/3046552/31145183-49da3002-a840-11e7-8fb2-21ca94f33881.png)

**Comment by pixelzoom** [comment]
@arouinfar Or perhaps you'd prefer the same color that's used by the cannon? The background rectangles for the cannon are `'rgba( 255, 255, 255, 0.6 )'` - white with 60% transparency.

**Comment by pixelzoom** [comment]
Changed to 60% transparency, back to @arouinfar.   Let me know if you'd like this in a 1.0.1 maintenance release, would be relatively easy because it's only 1 file that's changed.

**Comment by arouinfar** [comment]
Thanks, looks great @pixelzoom! 

Let's publish this as a maintenance release, as it significantly improves the tape measure's readability along the road, which is a common area for the tape measure to be used.

**Comment by pixelzoom** [comment]
Duh, I forgot that this also involves changes to MeasuringTapeNode. Looks like there have been no significant changes except for the https://github.com/phetsims/scenery-phet/issues/339. So we're in luck, but it will be a little more involved.

**Comment by pixelzoom** [comment]
Ah, that was so much fun (not).

Deployed in maintenance release 1.0.1.

**Comment by arouinfar** [comment]
Thanks @pixelzoom!!
