### ISSUE TITLE
Add Graphic Arts credits

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#157]
In reviewing master for #156, I noticed that the graphic artists had not been credited.  It would be nice to roll this in with the upcoming maintenance release. @pixelzoom can you please add the following to the credits:

Graphic Arts: Mariah Hermsmeyer, Cheryl McCutchan

**Comment by arouinfar** [comment]
@phet-steele has told me I can make these commits myself, so I'll go ahead and add the graphic arts credits to master and 1.0 under his guidance.

**Comment by arouinfar** [comment]
The changes look good in master, so closing.

**Comment by pixelzoom** [comment]
Deployed in maintenance release 1.0.1.
