### ISSUE TITLE
maintenance release with LoL patch

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#159]
See https://github.com/phetsims/joist/issues/450

We need to publish a maintenance release of this simulation which cherry picks https://github.com/phetsims/joist/commit/63046a699e8e3994f9c40f8d93482a497f0316b3

@jbphet you are listed as responsible dev, please proceed and let me know have questions or need assistance.

**Comment by phet-steele** [comment]
Don't forget #158 and #155! (when they are ready)

**Comment by pixelzoom** [comment]
#158 maintenance release is in progress, and will not include #155 or this issue.  Please hold off on this issue until #158 is closed.

**Comment by phet-steele** [comment]
@pixelzoom I merely wrote them for record keeping, not to do them RIGHT NOW (hence "when they are ready"). This really should just be renamed to be a batch issue.

**Comment by pixelzoom** [comment]
@samreid 1.1.0 would be a new release branch, requiring an entire RC cycle. Did you mean a 1.0 maintenance release?

**Comment by phet-steele** [comment]
yup!

**Comment by pixelzoom** [comment]
1.0.2 is going to be for #158.  Changing title to something more generic to avoid confusion.

**Comment by phet-steele** [comment]
> 1.0.2 is going to be for #158. Changing title to something more generic to avoid confusion.

Why can't 1.0.2 include changes for all three things? joist, 158, and 155?

**Comment by pixelzoom** [comment]
> Why can't 1.0.2 include changes for all three things? joist, 158, and 155?

Because I have time to address only #155, I'm not familiar with #158 and ran into issues while trying to include it (see https://github.com/phetsims/projectile-motion/issues/159#issuecomment-340072175), and joist should be a batch maintenance release.

**Comment by samreid** [comment]
I thought we decided batches were too difficult and better to do individual maintenance release where possible?  This affects 5 sims or so, some of which are already queued for QA.

**Comment by pixelzoom** [comment]
I don't care how it's done, will let y'all work that out.  I just noted if it's a maintenance release, then it's going to be 1.0.x, not 1.1.0.

**Comment by samreid** [comment]
Please see also https://github.com/phetsims/joist/issues/449#issuecomment-340263119, we are considering picking up some other commits for this maintenance release.

**Comment by jbphet** [comment]
@samreid said:

> I thought we decided batches were too difficult and better to do individual maintenance release where possible? This affects 5 sims or so, some of which are already queued for QA.

I don't recall deciding that.  The bulk process is a bit klunky, and for 5 sims we should probably just do them individually, but for much more than that a bulk release should be a consideration.

@samreid - what are the sims?  If by some odd coincidence they are all using the same version of joist a bulk release would actually be easier.

**Comment by jbphet** [comment]
The request for the patch seems unnecessary.  I started on the process, but as far as I can tell, the 1.0 branch of projectile motion does not have this problem.  I've done a bit of forensics, and it looks like the problem was introduced on Sep 11 2017 in https://github.com/phetsims/joist/commit/081275093e195f68aafec59773f9b45c94abc9e0#diff-926731e25b6af1f38bfcaa33e939b9b1, but the version of joist currently on the 1.0 branch is https://github.com/phetsims/joist/commit/7d518ed4f4067e7e6910adf491edba3aa05ac13e, which predates that.  I had @phet-steele test the live version of the sim and he confirmed that it doesn't have the problem.

@samreid - please verify my conclusions and close if appropriate.  Also, any other requests for this patch should be checked, since this ended up wasting developer time.

**Comment by samreid** [comment]
My apologies, I incorrectly thought this LOL pause bug had been around for a long time, I'll review the other sims and see if they are truly affected.

Regarding https://github.com/phetsims/projectile-motion/issues/159#issuecomment-340263176 @kathy-phet said: 

> It's not a high priority, but if it can be done without much difficulty, it seems worthwhile. Not time sensitive either.

So I'll create a separate issue for that.
