### ISSUE TITLE
User question: terminal velocity

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#16]
User question received Sep 25, 2016:

> Hello and thanks for your softwares
> I use your projectile simulation and i want to make sure you calculate terminal speed on it or not?! as we know while free fall there are max velocity when drag force and gravity force are equal. do you calculate terminal velocity on your projectile simulation?
> Regards

**Comment by ariel-phet** [comment]
Terminal velocity is a natural consequence of the model used, so yes, with air resistance on and the right conditions, object will have a terminal velocity

**Comment by oliver-phet** [comment]
Do we know if it is possible in the sim for a projectile to reach terminal velocity? I'm guessing this user would like to use the sim to demonstrate.

**Comment by ariel-phet** [comment]
Here is an example that shows terminal velocity (lots of other combos would do it, but here is an exaggerated one) Notice that the marks on the path (which happen every 1 second) are evenly spaced.

![capture](https://cloud.githubusercontent.com/assets/4051174/18848835/76ade4b6-83ed-11e6-930a-8b9e12de3fec.PNG)
