### ISSUE TITLE
Maintenance release with joist#449 commits

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#161]
See https://github.com/phetsims/joist/issues/449

@zepumph added a feature that adds the screen name to the title when launched with a single ?screens=x value.

When I asked if maintenance releases with this feature were desired, @kathy-phet repsonded:

> It's not a high priority, but if it can be done without much difficulty, it seems worthwhile. Not time sensitive either.

I checked that this feature is not present in the public version 1.0.1.

**Comment by jbphet** [comment]
@zepumph mentioned this to me already, and I spoke with @kathy-phet yesterday and she requested that I do indeed try to get this into the maintenance release.  It's on the list for this release, see https://github.com/phetsims/projectile-motion/issues/160#issue-269777253.

**Comment by jbphet** [comment]
This change was included in the 1.0.2 maintenance release, available here: https://phet.colorado.edu/sims/html/projectile-motion/1.0.2/projectile-motion_en.html

Here is a screenshot demonstrating the feature in action:
![pj-single-screen](https://user-images.githubusercontent.com/3082831/32907840-c19c11aa-cabe-11e7-9fd8-410df973dd2b.PNG)

**Comment by jbphet** [comment]
@samreid - good to close?

**Comment by samreid** [comment]
Thanks @jbphet.  @arouinfar what do we do to deliver this to LOL?

**Comment by arouinfar** [comment]
@samreid I don't think we need to do anything. We provided LoL with the link to the "latest", but they haven't actually integrated anything yet.

**Comment by samreid** [comment]
OK thanks, closing.
