### ISSUE TITLE
User request: ability for <25° at 0m cannon height

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#163]
> Hi Phet,
> 
> I have been a long time fan of your resources as they've been very useful for students to explore during and after lab experiences. Currently my class is looking to investigate the launch angle that will determine the maximum range.
> 
> In the simulation, I specify for them to lower the launch height to 0 meters since we want the vertical displacement to be zero. However, when we do this, the launch angle defaults to 25 degrees.
> 
> Is there a way to adjust for this in the next build of the simulation? Ideally I'd like to be able to launch it at 5 degrees and increment it by 5 degrees when the cannon is at the 0 meter mark.
> 
> Thanks for the help!
>

**Comment by arouinfar** [comment]
I think this would be worth looking into next time we revisit this sim. It looks like it could be possible to reduce the cannon's angle to 15 or 20 degrees and still have enough clearance for the barrel.

![image](https://user-images.githubusercontent.com/8419308/38329998-a9cd6572-380c-11e8-80ef-7090907f0531.png)

**Comment by oliver-phet** [comment]
Another user emailed with a similar request:

> Is it intentional that you can no longer do low angles for a cannon on the ground?  Without raising the cannon, the angle is limited to >25°.  This makes it difficult to have students discover the symmetry of the range formula, since almost a third of the angles will not have complements that are accessible.
> 
> Of course, one could raise the cannon but then you have to have students measure the "range" as the distance where it crosses the new horizontal starting level, a complication that obviates the use of the simulation to build intuition.
> 
> I understand the urge to verisimilitude, but there should be some way to access all angles.  (For example, one could easily dig a pit to have a cannon launch from the ground no matter what angle.)

**Comment by jbphet** [comment]
This sim is being revisited for phet-io instrumentation.  This issue is unassigned and isn't getting any attention, so we should decide if this is worth doing now.  Tagging @ariel-phet and @arouinfar to decide, @zepumph so that he is aware of the decision, since he would be the one to implement it.

**Comment by ariel-phet** [comment]
@zepumph @arouinfar this seems like a worthwhile change to me, especially since it would appear to be a common teacher request.

My suggestion would be that when the cannon goes below ground the "post" it sits on is turned into a more oblong pit than now currently exists (so a longer major axis of the oval that represents the pit) such that the cannon can reach an angle of 5 degrees at zero height of launch.

**Comment by arouinfar** [comment]
Looks like @ariel-phet and I were working on this simultaneously. I'm currently tinkering in my local copy, I'll write up my thoughts shortly. But to put things briefly...
* Reducing the minimum angle at 0 m to 15* is a one-line change to [ANGLE_RANGE_MINS](https://github.com/phetsims/projectile-motion/blob/master/js/common/view/CannonNode.js#L57) and would not require any further design changes.
![image](https://user-images.githubusercontent.com/8419308/66959811-68419f80-f028-11e9-9e9f-5e1107693455.png)
* It is also trivial to change the [ellipse dimensions](https://github.com/phetsims/projectile-motion/blob/master/js/common/view/CannonNode.js#L47-L48), so long as the change is symmetric.

**Comment by arouinfar** [comment]
> My suggestion would be that when the cannon goes below ground the "post" it sits on is turned into a more oblong pit than now currently exists (so a longer major axis of the oval that represents the pit) such that the cannon can reach an angle of 5 degrees at zero height of launch.

To reach an angle of 5*, the ellipse needs to stretch quite a bit, and if we leave the cannon centered, the ellipse would escape out of the dev bounds. I think it might also look pretty strange to change the ellipse dimensions depending on the cannon's height.

![image](https://user-images.githubusercontent.com/8419308/66962039-3da61580-f02d-11e9-8ce9-f6bc1478b0c3.png)
![image](https://user-images.githubusercontent.com/8419308/66962050-45fe5080-f02d-11e9-82a0-6781a9d86376.png)

An alternative would be to shift the cannon a bit to the left, so it's not sitting directly on the center of the post. To allow for an angle of 5*, we would still need to have a slightly wider ellipse, but not much. I was able to roughly move the cannon in my local copy, but we also would need to move the crosshairs and origin in the model to the left.

![image](https://user-images.githubusercontent.com/8419308/66961687-72fe3380-f02c-11e9-8d0f-4104d82f13a7.png)

Current look in master:
![Projectile Motion screenshot](https://user-images.githubusercontent.com/8419308/66961740-90330200-f02c-11e9-915f-4ac591de0e90.png)

Moving cannon off-center and slightly elongating the ellipse 
![Projectile Motion screenshot (1)](https://user-images.githubusercontent.com/8419308/66961739-90330200-f02c-11e9-80a1-cb2d3441194a.png)

**Comment by arouinfar** [comment]
@ariel-phet what do you think about shifting the cannon so it's slightly left of center? The crosshairs and origin would also need to move a bit to the left to stay coordinated with the cannon position.

**Comment by ariel-phet** [comment]
@arouinfar I think that is a nice change. There is really no special reason to have the cannon centered on the "pedestal" and this tweak accomplishes the goal nicely.

**Comment by arouinfar** [comment]
Thanks @ariel-phet.

@zepumph can you please shift the cannon, crosshairs, and origin of the projectile to the left side of the pedestal? The final screenshot in https://github.com/phetsims/projectile-motion/issues/163#issuecomment-542908020 was made a bit carelessly in my local copy. I shifted the `centerX` coordinate of the cannon base to -75, but I wasn't sure how to shift the rest with it.

```js
    const cannonBaseBottom = new Image( cannonBaseBottomImage, { top: 0, centerX: 0 } );
    cannonBase.addChild( cannonBaseBottom );
    const cannonBaseTop = new Image( cannonBaseTopImage, { bottom: 0, centerX: 0 } );
    cannonBase.addChild( cannonBaseTop );
```

Additionally, here are the changes to the ellipse geometry and angle range we'll need to make in CannonNode.js.
```js
  const ELLIPSE_WIDTH = 420; // empirically determined in view coordinates
  const ELLIPSE_HEIGHT = 40; // empirically determinedin view coordinates
```

```js
  const ANGLE_RANGE_MINS = [ 5, -5, -20, -40 ];
```

**Comment by zepumph** [comment]
The change is implemented above. To do this, we had to alter the origin for the view. So the change was less about moving the cannon over, but instead about shifting over the view elements that were no longer aligned with the cannon (see usages of `centerXOfCylinder`).  Here is the view now. In terms of space between dev bounds and the cylinder, It was a bit manual to try to keep the same margin, but I used the published version and think it is pretty spot on (1.5 model meters to the right of the origin). I used the target node as a ruler of sorts. Please review.

 ![image](https://user-images.githubusercontent.com/6856943/67135076-7aefdc00-f1c2-11e9-9de6-59e1479064f7.png)

**Comment by zepumph** [comment]
If you want to play with this more, I think it should be as easy as adjusting the VIEW_ORIGIN x in ProjectilMotionConstants, and then changing the `1.5` in `centerXOfCylinder`.

**Comment by arouinfar** [comment]
The cannon is looking really good underground.
![image](https://user-images.githubusercontent.com/8419308/67249412-d3beaf00-f424-11e9-9f05-406066c3e60a.png)

I think the cannon is just a bit too far on the left side of the pedestal, and the height leader line is also encroaching on it a bit. I couldn't quite figure out how to move the cannon right a bit without shifting everything else, but I did eventually find a look I'm happy with in terms of relative placement of the objects. Unfortunately, the polished version is colliding with the layoutBounds. It'd be great if we could just shift this as a unit to the right a bit more.

| master | polished | polished with ?dev |
| --- | --- | --- |
|![image](https://user-images.githubusercontent.com/8419308/67315010-f0a9bf80-f4c2-11e9-8adc-a170b411c1af.png) | ![image](https://user-images.githubusercontent.com/8419308/67314927-cbb54c80-f4c2-11e9-9843-a30a87649d3c.png) | ![image](https://user-images.githubusercontent.com/8419308/67315302-86dde580-f4c3-11e9-9d2f-7547f24e5136.png) |

@zepumph here are the changes I made to achieve the desired look. Perhaps they'll be a useful starting point for you.

ProjectileMotionConstants.js 
```js
VIEW_ORIGIN: new Vector2( 50, 510 ),
```

CannonNode.js
```js
const HEIGHT_LEADER_LINE_POSITION = -1.4; // in model coords
```

```js
const centerXOfCylinder = transformProperty.get().modelToViewX( 1.3 ); // in view coords
```

**Comment by zepumph** [comment]
I committed fixes for the zoom bugs, and I made the alterations that @arouinfar recommended above as best I could. Please review. 

- [ ] There was a bug with how the angle drag was occurring until this commit. This commit fixed it, but I'd still like to take a look at improving it (I marked a TODO in the code too).

**Comment by arouinfar** [comment]
@zepumph the canon position is looking awesome, thanks!

**Comment by arouinfar** [comment]
Reassigning back to @zepumph because of the outstanding TODO.

**Comment by zepumph** [comment]
Should be all set now. I updated the cursors (related somewhat to https://github.com/phetsims/scenery/issues/1013), and fixed some of the transform conversions. Closing
