### ISSUE TITLE
ComboBoxes are added incorrectly

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#164]
Noted while investigating phetsims/sun#237 ...

There is a misunderstanding in IntroProjectilePanel and LabProjectilePanel about the function of the ComboBox's `listParent`.   These lines are incorrect in both panels:

```js
    // then add it to its appropraite parent
    comboBoxListParent.addChild( projectileChoiceComboBox );
```

`projectileChoiceComboBox` should be a child of `content`, the panel's content.  And it looks like a VStrut can be removed from content.

This is likely causing the problem reported in  phetsims/sun#237. 

@andrea-phet Let me know if you have questions about this.

**Comment by pixelzoom** [comment]
You can also delete `layoutComboBox`, `this.projectileChoiceComboBox` and `this.controlsVerticalSpace` (the last of which is unrelated, but doesn't appear to be used anywhere.)

**Comment by andrea-phet** [comment]
@pixelzoom, do my commits above correctly add the combo boxes?

Also, the drifting still occurs. I think what is happening is that whenever the window is resized, the combo box list remains in the same place with regards to screen view coordinates. It's the panels that are moving with window resize, which causes the combo box list to "drift" away from the panel.

**Comment by pixelzoom** [comment]
Commits look good.   You can delete `IntroScreenView.layout`, since it doesn't do anything other than chain to the supertype.

Thanks for the explanation about why the list gets disconnected from the combobox.  That makes total sense.   One way to solve this would be to dismiss (hide) the list when a ScreenView's `layout` function is called.  But ComboBox currently does not provide a way to do that - see https://github.com/phetsims/sun/issues/366 for proposed enhancement to ComboBox.

**Comment by andrealin** [comment]
Implemented enhancement in https://github.com/phetsims/sun/issues/366 and used it to fix the bug in projectile motion.

**Comment by andrealin** [comment]
Assigning to @pixelzoom to review and close. In the commits above, I deleted `IntroScreenView.layout` as you suggested in https://github.com/phetsims/projectile-motion/issues/164#issuecomment-397707922. I also used the new implementations related to https://github.com/phetsims/sun/issues/366 to hide the combobox list whenever the window is resized.

**Comment by pixelzoom** [comment]
👍
