### ISSUE TITLE
Convert TWEEN to Twixt

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#166]
As discussed in https://github.com/phetsims/joist/issues/387#issuecomment-419600722, it would be nice to use Twixt instead of TWEEN.  This sim has 1 occurrence of `new TWEEN.Tween(...)`.  Assigning to the responsible dev.  After completing this issue, check if the hold on https://github.com/phetsims/joist/issues/387 can be removed (if this was the last "Convert from TWEEN to Twixt" issue).

**Comment by jbphet** [comment]
Should be done.  @samreid - you assigned me several of these.  It seemed pretty straightforward once I got familiar with the `Animation` type.  Do you want to review this and the others as I bang them out, or shall I just close once handled?

**Comment by samreid** [comment]
Good question.  Perhaps it would be best to have someone familiar with `Animation` (such as @jonathanolson or @pixelzoom) review our first one or two conversions to make sure we are doing well.

**Comment by jbphet** [comment]
Thanks for the review, closing.
