### ISSUE TITLE
should "superscript 2" be handled differently?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#168]
Noted while I was working on https://github.com/phetsims/scenery-phet/issues/446#issuecomment-450394096 ...

projectile-motion-strings_en.json contains this string:

```js
  "metersPerSecondSquared": {
    "value": "m/s²"
  },
```

I'm not sure if this pasting the Unicode "superscript 2" directly into the string value is a good idea.  A couple of other options: (1) use the Unicode escape "m/s\u00b2", (2) use "m/s<sup>2</sup>" with RichText.

**Comment by zepumph** [comment]
I think that changing this to use the unicode version seems right to me. I'll do that now.

**Comment by zepumph** [comment]
@pixelzoom does that seem better to you (I also did that for degree).

**Comment by pixelzoom** [comment]
Yes, that seems better.  But note that the degrees symbol is in MathSymbols.js, and we haven't been making it translatable in other sims (most recently Vector Addition).

**Comment by zepumph** [comment]
Sounds good. I'll make another issue.
