### ISSUE TITLE
should values be right aligned?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#169]
Noted while I was working on phetsims/scenery-phet#446 (comment) ...

Numeric values with units are displayed throughout this sim using NumberDisplay and NumberControl.  And they all appear to use `align: 'center'` for the value alignment.  Using `align: 'right'` would look better, since the units wouldn't shift around.  Examples:

![screenshot_950](https://user-images.githubusercontent.com/3046552/50523356-f5f9d180-0a8c-11e9-9c01-ada7fea61d72.png)

![screenshot_951](https://user-images.githubusercontent.com/3046552/50523358-f85c2b80-0a8c-11e9-9c79-c960d586b88d.png)

**Comment by arouinfar** [comment]
Good catch @pixelzoom. Right alignment for these values would definitely look nicer.

Not sure if this would be better to re-assign to @pixelzoom or @jbphet, but feel free to unassign/defer until this sim gets worked on again.

**Comment by pixelzoom** [comment]
According to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md), @jbphet is responsible for this sim, so I'm going to unassign myself.

**Comment by jbphet** [comment]
This does seem like an improvement, but it was far more fiddly and time consuming than I'd hoped.  I have something implemented, so @arouinfar - please review https://phet-dev.colorado.edu/html/projectile-motion/1.1.0-dev.2/phet/projectile-motion_en_phet.html and let me know if you think any further changes are necessary.

Also, please also opine on whether you feel we should do a maintenance release to get this published.  If not, it may be a long time before this goes live.

**Comment by pixelzoom** [comment]
@jbphet looks like you used the wrong issue number in the commits. I've tagged them above.

**Comment by pixelzoom** [comment]
@jbphet said:
> This does seem like an improvement, but it was far more fiddly and time consuming than I'd hoped. ...

Can you comment on why that was the case?  It should be as simple as using NumberDisplay with `align: 'right'`.   Was there a problem with NumberDisplay, or was there something odd done in the sim that required more work?

**Comment by jbphet** [comment]
> Can you comment on why that was the case?

Sure.  Several of the cases were not using `NumberDisplay`, they were creating their own background and putting the number over it.  `TracerNode.createInformationBox` is once such example, and there are several others.  In fact, there seemed to be similar methods in several places, which looked like there was some code duplication that could potentially be consolidated, or maybe they should all use `NumberDisplay` instead.  That seemed like a potential time sink, though, and I didn't want to get into it for a sim that has been working well and just needed a visual adjustment.  In the `TracerNode` case, I thought it looked bad to have both the 'no value' readout and the number-with-labels readout right justified, so the code was further complicated (though not much) by handling of that case.  The usage of default values was also a little different from what I've seen before.  All those little things added up to more time than I originally thought it would take.  You'd think I'd know better by now.

Thanks for fixing the commits, not sure how I messed that up...

**Comment by pixelzoom** [comment]
> In the TracerNode case, I thought it looked bad to have both the 'no value' readout and the number-with-labels readout right justified, so the code was further complicated (though not much) by handling of that case. 

These options to NumberDisplay should have done the job:

```
align: 'right',
noValueAlign: 'center'
```

I don't see `noValueAlign` used in projectile-motion.  Did you implement a custom solution?

**Comment by pixelzoom** [comment]
> `TracerNode.createInformationBox` is once such example. ...

I just had a look at this.  Highly recommended to replace with NumberDisplay.

**Comment by jbphet** [comment]
I agree that using `NumberDisplay` is ultimately the way to go.  I made a call to adjust rather than rewrite in the interest of time.  How about we create another issue and assign to @andrealin to do such an update?  I believe she is going to be working with us for a couple of weeks at the beginning of the summer.

**Comment by arouinfar** [comment]
@jbphet the updated tracer and numberControl readout alignments look good in 1.1.0-dev.2! Thanks for making these changes. I'm not sure that these changes would be critical enough for a maintenance release, so I'll defer to @ariel-phet.

**Comment by ariel-phet** [comment]
@jbphet @arouinfar @pixelzoom. A nice improvement, but not worthy of a maintenance release. Removing assignees.

**Comment by zepumph** [comment]
https://github.com/phetsims/projectile-motion/issues/173 has been created and completed, the values look very nice as right aligned, we decided against an MR. I'm going to close this issue, as this improvement will go out upon next release. Please reopen if you agree.
