### ISSUE TITLE
CT: this.projectileChoiceComboBox.hideListFromClick is not a function

### ISSUE THREAD

**Issue by jbphet** [phetsims/projectile-motion#170]
This sim is failing continuous test (CT) at the moment.  It appears that this is due to the removal of the method `hideListFromClick` from the combo box.  It looks like this is due to some refactoring work that was being done by @pixelzoom.  That method is no longer present in ComboBox, but is mentioned in some comments that would seem to imply that the method should be there.  They look like this (from ComboBox.js):

```js
    //TODO sun#314 if "Most often should be called from hideListFromClick" then why is this called 6 times from other places, which hideListFromClick is called once?
    /**
     * Hides the combo box list. Most often should be called from hideListFromClick
     * @private
     */
```

@pixelzoom - can you take a look?

**Comment by pixelzoom** [comment]
`hideListFromClick` was apparently added to pop the list down when the browser is window is resized, see https://github.com/phetsims/sun/issues/366.    We should now be able to simply call `hideList`.  I'll investigate.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  I confirmed that it's sufficient to call ComboBox `hideList`, and I tested that it properly pops down the list when the browser window is resized.   Also tested projectile-motion with `?ea&fuzz`.

Closing.
