### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#175]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Arrows on the ends of sliders could have larger pointer areas

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56238616-1f466980-604c-11e9-80b1-ad23945915fa.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56238617-1f466980-604c-11e9-8e6d-a002f68deece.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56238618-1f466980-604c-11e9-9d83-9fe4439521ac.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/41024075/56238619-1f466980-604c-11e9-89b3-033af8ae1664.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56238621-1f466980-604c-11e9-9b06-a43ff3cc1e25.png)

**Comment by arouinfar** [comment]
Thanks @KatieWoe. Looks like another place we can utilize the asymmetric pointer area dilation added in https://github.com/phetsims/scenery-phet/issues/489.

@jbphet here's a mockup showing updated touch areas in green.
![image](https://user-images.githubusercontent.com/8419308/56303409-152e7480-60f9-11e9-8a09-0c8a48c7d0bf.png)

**Comment by SaurabhTotey** [comment]
I have set all touch dilation X and Y values to 20. Here is what it looks like right now in master.
<img width="1440" alt="dragscreen" src="https://user-images.githubusercontent.com/22577113/60215823-c3efdf00-9825-11e9-87b7-04073df73e0f.png">
<img width="1440" alt="labscreen" src="https://user-images.githubusercontent.com/22577113/60215827-c5b9a280-9825-11e9-83f0-62f86e46861b.png">

**Comment by arouinfar** [comment]
Thanks @SaurabhTotey! It looks like I overlooked the tweakers on the Initial Speed NumberControl in my mockup in https://github.com/phetsims/projectile-motion/issues/175#issuecomment-484157020. Can you apply the same dilation to all NumberControl tweakers in the sim?

**Comment by SaurabhTotey** [comment]
Sure thing! I applied the increased touch dilation to the initial speed number control as well now. Here is what it looks like in master.

<img width="1440" alt="introscreen" src="https://user-images.githubusercontent.com/22577113/60216436-475e0000-9827-11e9-841e-9d4039837210.png">

This is how it looks like on all screens.

**Comment by KatieWoe** [comment]
They don't seem to have changed on master for me for some reason.
![notbigger](https://user-images.githubusercontent.com/41024075/60217383-d53aea80-9829-11e9-9f57-7fc9b6c67b76.png)

**Comment by SaurabhTotey** [comment]
Hmm... That is odd. Have you git pulled and are you up to date with e825cf44f5cb5ff8fab4211c5e8528828d3ee396? I seem to have pushed changes from my end, and the changes seem to exist on this repository. However, this may entirely be my mistake.

**Comment by KatieWoe** [comment]
I pulled a few minutes after https://github.com/phetsims/projectile-motion/issues/175#issuecomment-506053910.  I'll try again just in case.

**Comment by KatieWoe** [comment]
Never mind, it looks ok now.  I must have pulled too earlier.

**Comment by arouinfar** [comment]
Looks great, thanks @SaurabhTotey!
