### ISSUE TITLE
User suggestion: bring back David's fig leaf

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#176]
In https://github.com/phetsims/projectile-motion/issues/158 we made the decision to keep David's pants on. The HTML5 version of the sim is being used by younger learners, and the fig leaf easter egg was too distracting for some classrooms.

That said, I have heard from many teachers at conferences such as NSTA, ISTE, and AAPT who lament the loss of this easter egg. 

Perhaps a compromise would be to hide this feature behind a query parameter?

Obviously this is not a high priority issue, but perhaps something we could consider the next time this sim gets some developer attention. What do you think @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar we had discussed something like shooting his shorts off and there would be a speedo...or perhaps he could have sunglasses and those would shoot off?

I think what teachers are lamenting is the ability for something to happen when you shoot David, not necessarily the fig leaf in particular. 

I would be fine with something, but I think the fig leaf is (sadly) too problematic.

**Comment by arouinfar** [comment]
> I would be fine with something, but I think the fig leaf is (sadly) too problematic.

I don't agree that the fig leaf would be problematic behind a query parameter. If the teacher wants the fig leaf, they can use the query parameter. If the fig leaf is too risqué for their classroom, they don't have to use the query parameter. The only place it would be advertised is in the Teacher Tips (on the 3rd page), which requires a teacher account to access. 

Since we already have the artwork for the fig leaf, it could easily be rolled into the work currently going on in the sim. If we want to go with a different easter egg, we would need to work with a graphic artist on updating the artwork.

I'd also like to get @kathy-phet's opinion on this, so I'll tag for design meeting.

**Comment by arouinfar** [comment]
This issue is stale, but we discussed and ultimately decided that the fig leaf would not be appropriate, as it's not particularly readable as a fig leaf at the small resolution. We could consider alternative easter eggs, but this sim is already plenty whimsical so it's not the best use of resources at this time. Closing.
