### ISSUE TITLE
What is needed before next release?

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#178]
RE https://github.com/phetsims/projectile-motion/issues/177, I want to make sure I understand what of the current issues in this repo should be done before we publish this sim for phet-io.

**Comment by jbphet** [comment]
I just went through the list of open issues and made some updates.  My recommendation is to make sure that issue https://github.com/phetsims/projectile-motion/issues/169 will go out with any new releases. I've asked about https://github.com/phetsims/projectile-motion/issues/163, and you should go with whatever the designers/management decides on that one.

The remaining issues seem like more than we probably want to bite off right now, given that the primary goal right now is to get this instrumented for phet-io.

**Comment by zepumph** [comment]
Thanks @jbphet, I feel like the appropriate gears are in motion now. Closing.
