### ISSUE TITLE
convert from PropertySet to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#18]
PropertySet is deprecated and should be replaced by Property, see phetsims/axon#102. Since this sim hasn't been published yet, this should be done before RC testing and publishing.

**Comment by pixelzoom** [comment]
@andrea-phet Related to #22 (high-level review), I recommend doing this conversion before you proceed with any further development.   Let me know if you need advice on how to approach this conversion.

**Comment by andrea-phet** [comment]
@pixelzoom I saw DerivedProperty on the code review checklist, and it seems somewhat relevant to this issue. What is a DerivedProperty and do you think I could have use for it?

**Comment by pixelzoom** [comment]
A DerivedProperty is a Property that is derived from 1 or more other Properties (its dependencies).  A DerivedProperty cannot be set directly. It values updates when one of its dependencies changes. 

For example, suppose that you have a sim that allows the student to change mass and acceleration, and observe the resulting force.  The model would look like:

```js
this.massProperty = new Property( 0 );
this.accelerationProperty = new Property( 0 );
this.forceProperty = new DerivedProperty( [ this.massProperty, this.accelerationProperty ],
  function( mass, acceleration ) {
    return mass * acceleration;
  } );
```

While I don't see any obvious cases where DerivedProperty should be used in this sim, that doesn't mean there aren't any :)  If you think you might have a use for this, let me know and I'll be happy to review.

**Comment by andrea-phet** [comment]
Tips for making this go faster and also catching everything? @pixelzoom

**Comment by pixelzoom** [comment]
@andrea-phet asked:
> Tips for making this go faster and also catching everything?

Unfortunately, conversion is a manual process, and it's easy to make mistakes that result in weird (or worse, silent) errors.

I'll use `ProjectileMotionModel`as an example to demonstrate the general conversion process.  Its PropertySet has many entries, and each one needs to be converted to an individual Property.

If the file you're converting doesn't already have a `reset` function, create one.  You won't be able to use `PropertySet.reset` anymore, and will need to call `reset` for each Property that you create.  `ProjectileMotionModel` already has a `reset` function, so nothing to do there.  But for `Score` and other PropertySet subtypes, you'll need to implement `reset`.

I recommend that you start by converting one Property at a time. Once you get the hang of it, you might feel comfortable doing a few at a time, especially if they are related.  

So let's convert one Property... The first Property in `ProjectileMotionModel` is:

```js
35 cannonHeight: 0, // meters
```

Remove it from the PropertySet, and create an explicit Property, like this:

```js
// {Property.<number>} height of the cannon, in meters
this.cannonHeightProperty = new Property( 0 );
```

Add the Property to `reset`:

```js
this.cannonHeightProperty.reset();
```

Next, search the code for uses of the Property.  In this case, search for ".cannonHeight" -- note the "." at the beginning of the search string. ".cannonHeight" has 5 occurrences. Look for occurrences that do not have the "Property" suffix - these are the uses that you need to convert.   There is 1 occurrence that requires conversion, in Trajectory:

```js
255        && this.yProperty.initialValue === model.cannonHeight
```

Add the "Property" suffix and (if applicable) `get` or `set` (or `value`, if you're using that convention):

```js
255        && this.yProperty.initialValue === model.cannonHeightProperty.get()
```

Test, commit, then move on to the next Property in the PropertySet.

When the entire PropertySet has been converted to individual Properties, then you can remove the PropertySet.  In `ProjectileMotionModel`, this means:

• delete `var PropertySet = require( 'AXON/PropertySet' );`
• delete `PropertySet.call(...);`
• delete `PropertySet.prototype.reset.call( this );`
• change `inherit( PropertySet, ProjectileMotionModel,...` to `inherit( Object, ProjectileMotionModel,...`

Let me know if you have any questions.  If this isn't clear, I'd be happy to go demonstrate a conversion via Skype screen sharing.

**Comment by andrea-phet** [comment]
@pixelzoom I think I found a use for DerivedProperty for air density, which is solely linked to whether air resistance is turned on and altitude. Could you review https://github.com/phetsims/projectile-motion/commit/add3b6f596f40e5f8a9d0e8694a76499e2dc778a ?

**Comment by pixelzoom** [comment]
@andrea-phet  Yes, `airDensityProperty` looks like an appropriate use of `DerivedProperty`.  It looks like you can now delete `ProjectileMotionModel.updateAirDensity`, it's not used anywhere.

**Comment by andrea-phet** [comment]
Assigning to @pixelzoom to review and close.

**Comment by pixelzoom** [comment]
I randomly selected a few commits to inspect, looks like you mastered this conversion process :)  I also ran with with `?ea&fuzzMouse` and saw no problems.  Nicely done, closing. 

That said... Don't be disappointed if you encounter a bug or two related to this conversion at some point in the future. I've converted a dozen or so sims, and I've definitely messed it up.
