### ISSUE TITLE
PhET-iO spec from client

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#190]
Related for #177:

General Elements: 
- [x] Each item in the grey and black bar at the bottom should be hideable. 
- [x] Ability to hide tabs (only one will be used at a time).
      	* using `?screens`
- [x] Ability to hide David statue image.
   		* `projectileMotion.introScreen.view.davidNode.visibleProperty`
- [x] Ability to hide reset button. 
- [x] Ability to preset the zoom and fix. 
		*  emit `projectileMotion.introScreen.view.zoomInButton.firedEmitter`
		    and hide the buttons
- [x] Zooming features should be hideable.
       	*  `projectileMotion.introScreen.view.zoomInButton.visibleProperty` 
           `projectileMotion.introScreen.view.zoomOutButton.visibleProperty`
- [x] Ability to preset the initial speed and hide the slider and arrows.
- [x] Ability to preset and fix the height of the cannon.
       	*  `projectileMotion.introScreen.model.cannonHeightProperty`
- [x] Ability to preset the angle of the cannon.
		*  `projectileMotion.introScreen.model.cannonAngleProperty`
- [x] Ability to preset and fix target to a spot. 
- [x] Ability to hide target.
    	*  `projectileMotion.introScreen.view.targetNode.visibleProperty`
- [x] :star: Measurement tools should be selectable and hideable. 
	*  "selecteable?": set the measuringTapeNode visible, then `phetio.phetioClient.invoke( 'projectileMotion.introScreen.model.measuringTape.basePositionProperty', 'setValue', [{x:2,y:2}]);` model `isActiveProperty` `base/tipPositionProperties.`
	*  hide panel: projectileMotion.introScreen.view.toolboxPanel.visibleProperty
          - [x]   instrument the icons for visibility too.

Intro:
- [x] Air resistance should be hideable (including drag coefficient text property value).
     * `projectileMotion.introScreen.view.projectilePanel.airResistanceCheckbox.visibleProperty` and `projectileMotion.introScreen.view.projectilePanel.dragCoefficientControlBox.visibleProperty`
- [x] Ability to preset the projectile item from the drop-down menu (and hide the rest). 
     * Hide choices with `projectileMotion.introScreen.view.projectilePanel.projectileChoiceComboBox.listBox.*.visibleProperty`
     * Select current choice with `projectileMotion.introScreen.model.selectedProjectileObjectTypeProperty`
- [x] Every item in the vectors panel (and the entire panel) should be hideable. 
     * Whole panel: `projectileMotion.introScreen.view.vectorsPanel.visibleProperty`
    * Individual checkboxes like: `projectileMotion.introScreen.view.visibilityProperties.componentsVelocityVectorsOnProperty`
     * titles like `projectileMotion.introScreen.view.vectorsPanel.velocityVectorsTitleNode.visibleProperty`

Vectors: 
- [x] Air resistance should be selectable and hideable. 
- [x] :star: Ability to hide the drag coefficient text property value. 
    * Let's talk about this more, the text has a number in it, and is set up to be overwritten if the drag coefficient changes. As far as I can see, on this screen it doesn't ever change, so maybe editing it as text could be fine, but with a strong recommendation to look at the dragCoefficientProperty for changes?
    * We don't want the textProperty to be instrumented
- [x] Ability to change the air resistance text property value. 
    * `projectileMotion.vectorsScreen.view.projectilePanel.airResistanceText.textProperty`
- [x] Ability to set to the total option and hide the components option. 
    * set the "total" options, see #195 to make this easier
   * It is most preferable to hide the whole group, instead of leaving one visible, with projectileMotion.vectorsScreen.view.vectorsPanel.totalOrComponentsRadioButtonGroup.visibleProperty`. If needed to toggle for one item, see `projectileMotion.vectorsScreen.view.vectorsPanel.totalOrComponentsRadioButtonGroup.components.visibleProperty`.
- [x] :star: Vector options should be selectable and hideable. 
      * selectable through the appropriate view properties (may change in https://github.com/phetsims/projectile-motion/issues/195)
     * hideable with checkboxAndIcon nodes like `projectileMotion.vectorsScreen.view.vectorsPanel.accelerationCheckboxAndIcon.visibleProperty`. I tried to combine the icon into the checkbox, so that we could just interface with the checkbox like for airResistance, but couldn't make it work easily.
     - [x] we can get rid of the checkboxAndIcon instrumentation, and just put the icon in the text Node given to checkbox. 

Drag: 
- [x] :star: Every item in the vectors panel (and the entire panel) should be hideable. 
    * same as in vectors screen. See `forceCheckboxAndIcon` type Nodes. This pattern may change though, let's talk about it at the design meeting.

**Comment by zepumph** [comment]
I made it through the "general elements" section. 

> Measurement tools should be selectable and hideable.


I think this is done, though I'm not sure I understand what "selectable" means. I believe I need a designer here.

**Comment by zepumph** [comment]
I've finished the first pass at the list. Let's discuss at the design meeting, especially the started items.

**Comment by zepumph** [comment]
Everything has been implemented here. @arouinfar, I was unable to find a way to consistently, and maintainably align the vector-related checkbox icons on the right side of the panel now that they are part of the checkbox text content. As a result, I decided to space them just right of the longest text. I could move them over more than that, but I felt like closer to the checkbox was better than somewhere in the middle of the panel.

How does that look to you?
![Uploading image.png…]()

**Comment by arouinfar** [comment]
@zepumph thanks for investigating. I think the alignment in https://github.com/phetsims/projectile-motion/issues/190#issuecomment-546525766 looks a bit odd -- either the icons should be on the far right side of the panel or consistently spaced from the end of the accompanying string. The former looks a bit more like a legend, and the latter is a more typical alignment used in sims (which is what I would prefer). 

@zepumph I'd vote for placing the icons at the end of the string, and not worrying about keeping them aligned with one another. The amount of padding after "Acceleration Vectors" looks good to me.

**Comment by zepumph** [comment]
Hows that?

**Comment by arouinfar** [comment]
The Vectors and Drag screens look good to me @zepumph 
![image](https://user-images.githubusercontent.com/8419308/68347991-eb00cc00-00b5-11ea-819f-750bf14e670d.png)
![image](https://user-images.githubusercontent.com/8419308/68347998-f2c07080-00b5-11ea-841c-8f362f21afd9.png)

Are you planning to take the same approach on the Intro screen too?
![image](https://user-images.githubusercontent.com/8419308/68348014-053aaa00-00b6-11ea-86b9-f4e08bf1499d.png)

**Comment by zepumph** [comment]
I wasnt' sure, and was going to ask (but then forgot). Implemented above. Anything else? Feel free to close.

![image](https://user-images.githubusercontent.com/6856943/68348455-59d62900-00a6-11ea-8e67-dd8d72af30b4.png)

**Comment by arouinfar** [comment]
Looks good @zepumph, I'll go ahead and close.
