### ISSUE TITLE
Replace usages of _.defaults with PHET_CORE/merge

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#194]
Though this is a fine pattern, it is atypical to use for our options, and merge is preferred, if only because it is a pattern used across the whole project. For example I had never seen this function until beginning to work on this sim, and I had to look it up. While that isn't inherently enough to warrant a conversion, I think it would help clean up the code.

**Comment by samreid** [comment]
It seems better to use merge for sim options.
