### ISSUE TITLE
VectorVisibilityProperties and subtypes needs a bit of work

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#195]
VectorVisibilityProperties has the following properties:

```
totalVelocityVectorOnProperty
componentsVelocityVectorsOnProperty
totalForceVectorOnProperty
componentsForceVectorsOnProperty
totalAccelerationVectorOnProperty
componentsAccelerationVectorsOnProperty
```

This can be simplified into 4:
* total vs components Property, which is already in two subtypes called `vectorsDisplayProperty`
* forceVectorOnProperty
* veloctityVectorOnProperty
* accelerationVectorOnProperty

Then items that were just linking to a single property before, can like to the `vectorsDisplayProperty` and the other one, and to the logic accordingly.

Having written this out, there may be a 30% chance or so that this is a step in the wrong direction.

That said it still is worth investigation. Especially since all 6 of the above are colocated on subtypes like DragVectorVisibilityProperties that already have a `vectorsDisplayProperty`.

**Comment by zepumph** [comment]
This is potentially a by product of using a custom control box instead of `NumberControl`, let's see if https://github.com/phetsims/projectile-motion/issues/197 doesn't solve this.

**Comment by zepumph** [comment]
Here are the properties needed for each screen:

Intro:

totalVelocityVectorOnProperty
componentsVelocityVectorsOnProperty
totalForceVectorOnProperty
componentsForceVectorsOnProperty

Vectors:

velocityVectorsOnProperty
accelerationVectorsOnProperty
forceVectorsOnProperty
vectorsDisplayProperty (total/components)

Drag:

velocityVectorsOnProperty
forceVectorsOnProperty
vectorsDisplayProperty


And that is all. So I will make enough stuff optional such that we don't have to deal with creating and instrumenting everything every time.

**Comment by zepumph** [comment]
Part of this work was a good bit of refactoring in ProjectileNode. In my opinion there was too much in the constructor, and much of it wasn't needed for every single instance created (often depending on the screen and the values in VectorVisibilityProperties. So I pulled out drawing of each type of arrows (vector/acceleration crossed with total/component) into their own prototype method, and found that FreeBodyDiagram (for total/component force) lent itself nicely to its own class. That was about 25% of the logic for the file, and it makes me happy to have split that up.

After the refactor it was easy enough to optionally instrument/create certain Properties in the VectorVisibilityProperties base class, which cleaned up studio. Then in ProjectileNode, checking for the existence of optional Properties allowed us to exclude the drawing of unneeded vectors for that ProjectileNode instance.

I would hope that this refactor gets reviewed as part of a post-phet-io code review. So I'll leave this open and marked as "ready-for-review"

**Comment by zepumph** [comment]
I just renamed a few tandems in correlation to these changes, and I'm tacking the change on here.

**Comment by pixelzoom** [comment]
@zepumph you labeled this ready-for-review, but it's unassigned.  Should it be assigned to someone? If not, can you add a comment indicating when it should be reviewed, and label it deferred?

**Comment by zepumph** [comment]
Unassigning for now. When work picks up again in projectile motion, I will want to review this issue's work, and see if there is anything more to do here.

**Comment by zepumph** [comment]
I just gave this a review, this fully feels in the right direction, with new methods and a composed class that pulls a bunch out of ProjectileNode. @arouinfar and I have also further worked on the PhET-iO look of these view Properties. Ready to close.
