### ISSUE TITLE
Refactor custom "boxes" to NumberControl?

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#197]
During PhET-iO meeting, we were curious why custom "boxes" with a NumberDisplay and HSlider were not NumberControls. Speaking with @arouinfar and @kathy-phet, they didn't care about having the tweaker buttons, though they aren't really needed. This consistency would improve having a consistent API for PhET-iO, as well as potentially making it easier to support interactive descriptions.

Also, how hard would it be to make the number tweakers optional in NumberControl? Is that a worth-while investigation?

@pixelzoom, you paired with @andrealin a fair bit for this sim. Do you remember why NumberControl was not used for these custom "boxes"?

**Comment by pixelzoom** [comment]
Examples please.

**Comment by arouinfar** [comment]
@pixelzoom these are the controls in question. You can find them on the Vectors and Drag screens.

![image](https://user-images.githubusercontent.com/8419308/67603696-d4ae5400-f736-11e9-8af6-138c9c4811c3.png)

**Comment by pixelzoom** [comment]
Based on @arouinfar's screenshot, and searching around a bit... I determined by "custom boxes", @zepumph must be referring to the `createCustomParameterControlBox` method in `LabProjectilePanel`.   That's how I spent the first 15 minutes on this issue.  Now I'll work on responding to the question.

**Comment by pixelzoom** [comment]
WebStorm "Show History for Selection" shows no evidence of me having worked on `createCustomParameterControlBox`, and I don't recall collaborating on it with @andrealin.  I suspect that she wasn't aware of the ability to create a custom `layoutFunction` for `NumberControl` that would exclude the spinners.  And it looks to me like that would be a fine solution.  I don't see a predefined `layoutFunction` that excludes spinners, so I think that it would be fine to either create a sim-specific function, or add one to `NumberControl` (following the documentation pattern for other such functions).

**Comment by zepumph** [comment]
Thanks, I didn't even think about how a layoutFunction could hide the tweakers for us. I like that solution a lot, and will start first trying to add it to be a general one to NumberControl.

**Comment by zepumph** [comment]
I made the conversion in the Vectors screen above, it was pretty straight forward and I really like it for phet brand. 

> I suspect that she wasn't aware of the ability to create a custom layoutFunction for NumberControl that would exclude the spinners.

For PhET-iO brand, this isn't ideal, because the tweakers are still created, and so still show up in studio. I may poke around in NumberControl and see how hard it would be to optionally remove the tweaker buttons (I will be adverse to rabbit holes here), and will report back!.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/scenery-phet/issues/549 I added an option to remove the tweakers. 

Then over here it was straight forward to make the conversion in the drag screen as well from "control box" to NumberControl. The code in the drag screen and vectors screen were basically the exact same, so I was able to factor this out into a new type. 

@pixelzoom could you review this work, along with https://github.com/phetsims/scenery-phet/issues/549.

**Comment by zepumph** [comment]
I tested this by looking at before and after, and not noticing any layout changes (save a few pixels on the drag screen). The main points to review would be to look at the conversion and creation of TweakerlessNumberControl. Then you can play around in studio and see that there are no arrow buttons in ti.

**Comment by pixelzoom** [comment]
I reviewed the commits.  I understand why you renamed the option `excludeTweakers`.  But I think your first instinct, to name it `includeArrowButtons`, was the correct choice. It's more consistent with both the API and implementation -- option `arrowButtonOptions` is part of the API, and the buttons are `ArrowButtons` (not TweakerButtons, which don't exist).  I'm also not a fan of options that specify whether to "exclude", I much prefer "include" (similar to disable vs enable, invisible vs visible, and other boolean states).

I'll also point out that we've encountered situations where NumberControl's title is also undesired -- most recently in gas-properties (see `temperatureLayoutFunction` in `InjectionTemperatureAccordionBox`) and another case that I recall @samreid asking about not too long ago, where I think he used a similar custom `layoutFunction`.  These cases will presumably have a similar PhET-iO issue, so should we handle it similarly? It will be more complicated, since it involves changing `NumberControl`'s constructor signature -- `{string} title` is a required constructor parameter, and would need to move to options.

Back to @zepumph.

**Comment by pixelzoom** [comment]
It looks like energy-skate-park/PhysicalNumberControl has a layoutFunction that conditionally hides tweakers (sic) and NumberDisplay.  So should we also deal with making the NumberDisplay option, via `includeNumberDisplay`? 

I'm also starting to wonder...  NumberControl was not specified as having optional subcomponents, and there was a goal of unifying the approach for this type of control.  First that diverged with the introduction of `layoutFunction`.  Now it's diverging further.  Have we lost sight of the original goals? Do we really need so many variations? Are subjective requirements creeping in that might change if designers knew what the limitations of NumberControl are?

**Comment by pixelzoom** [comment]
Oops. I put NumberControl review comments in this issue by mistake. I've moved them to https://github.com/phetsims/scenery-phet/issues/549.

**Comment by pixelzoom** [comment]
As I said over in phetsims/scenery-phet#549, I'm not a fan of this "tweaker" terminology. It doesn't match the terminology used in NumberControl, and there's in fact nothing in NumberControl to limit the arrow buttons to "tweaking".   So instead of `TweakerlessNumberControl`, I'd rather see `ArrowlessNumberControl`. But this is sim-specific code which I'm less apt to have to look at, so I'll defer to the responsible dev, @jbphet.

As for how this working in projectile-motion....  If it were me, I would have encouraged adding the arrow buttons to the NumberControls in the first 3 screens, especially since the same controls (i.e. Diameter, Mass) have arrow button in the _Lab_ screen.  Yes, I see that the Lab screen snaps to different internvals, but that doesn't affect the usefulness of the arrow buttons.  Imo it would have been a nice usability improvement, and would have made this issue unnecessary.  Having to move the slider feels less convenient.   And there also seems to be a bug with the slider - clicking on the track doesn't work.  @arouinfar your thoughts?

**Comment by pixelzoom** [comment]
Looking at `TweakerlessNumberControl` more closely, I see some potential issues.

- [ ] NumberControl and its superclass have no `width` options, so what is this doing?

```js
78 width: options.containerWidth - 3 * options.xMargin //  left, right, and sliderPadding *2
```

- [ ] Options are merged in 2 separate calls.  It would be nice to avoid this, since (in general) we've identified it as an anti-pattern.

- [ ] The args to the 2nd `merge` are backwards, it allows the more general settings to override the settings that are specific to `TweakerlessNumberControl`. Relevant code:

```js
options = merge( {
        // ... values specific to TweakerlessNumberControl
      }, {
        numberDisplayOptions: ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS,
        titleNodeOptions: parameterLabelOptions
      }
```

If someone changes `NUMBER_DISPLAY_OPTIONS`, they may inadvertently change how TweakerlessNumberControl behaves. The order should be:

```js
options = merge( {
        numberDisplayOptions: _merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS ),
        titleNodeOptions: parameterLabelOptions
      }, {
        // ... values specific to TweakerlessNumberControl
      } );
```

In general... More general/reusable options should be first in the `merge` call,

**Comment by zepumph** [comment]
I renamed to `ArrowlessNumberControl`, as that seemed safe and simple, though @jbphet please let me know if you would like it to be another type. 

> And there also seems to be a bug with the slider; clicking on the track doesn't work. For example, I should be able to click on the '5' tick on the mass slider, and the value should move to 5. 

I am able to click on the track, but it is an incredibly narrow pickable width (seems to be independent of trackLineWidth).

>Options are merged in 2 separate calls. It would be nice to avoid this, since (in general) we've identified it as an anti-pattern.

I think I agree with you in general, but here it feels pretty clean to merge first the options that then inform other overrideable options. How would you do it instead?

**Comment by pixelzoom** [comment]
> I am able to click on the track, but it is an incredibly narrow pickable width (seems to be independent of trackLineWidth).

Ah yes, so am I.   Forget I saw it, or adjust pointer areas, up to you.

> I think I agree with you in general, but here it feels pretty clean to merge first the options that then inform other overrideable options. How would you do it instead?

See patch below.  The other problem that this addresses is that you want `maxWidth` to be computed, not overridable by the client. 

<details>
<summary>Patch</summary>

```
Index: js/common/view/ArrowlessNumberControl.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/ArrowlessNumberControl.js	(revision b403dc38e537235d9d0e0cdab325e498685627df)
+++ js/common/view/ArrowlessNumberControl.js	(date 1573078031280)
@@ -37,27 +37,16 @@
      * @returns {VBox}
      */
     constructor( labelString, unitsString, valueProperty, range, round, options ) {
+
       options = merge( {
         containerWidth: 200,
         textDisplayWidth: 20,
-        xMargin: 8
-      }, options );
-
-      // local vars used for layout and formatting
-      const textDisplayWidth = options.textDisplayWidth * 1.2;
-      const parameterLabelOptions = merge( {}, LABEL_OPTIONS, {
-        maxWidth: options.containerWidth - 3 * options.xMargin - textDisplayWidth
-      } );
-
-      options = merge( {
-        numberDisplayOptions: merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS ), // we don't own this constant
-        titleNodeOptions: parameterLabelOptions
-      }, {
-        numberDisplayOptions: {
+        xMargin: 8,
+        numberDisplayOptions: merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS, {
           valuePattern: StringUtils.fillIn( pattern0Value1UnitsWithSpaceString, { units: unitsString } ),
-          decimalPlaces: null,
-          maxWidth: textDisplayWidth
-        },
+          decimalPlaces: null
+        } ),
+        titleNodeOptions: merge( {}, LABEL_OPTIONS ),
         sliderOptions: {
           constrainValue: value => Util.roundToInterval( value, round ), // two decimal place accuracy
           majorTickLength: 12,
@@ -79,6 +68,12 @@
         } )
       }, options );
 
+      assert && assert( options.numberDisplayOptions.maxWidth === undefined, 'ArrowlessNumberControl sets numberDisplayOptions.maxWidth' );
+      options.numberDisplayOptions.maxWidth = options.textDisplayWidth * 1.2;
+
+      assert && assert( options.titleNodeOptions.maxWidth === undefined, 'ArrowlessNumberControl sets titleNodeOptions.maxWidth' );
+      options.titleNodeOptions.maxWidth = options.containerWidth - 3 * options.xMargin - options.numberDisplayOptions.maxWidth;
+
       super( labelString, valueProperty, range, options );
     }
   }
```

</details>

**Comment by pixelzoom** [comment]
Here's the full file with patch applied, if that's easier to look over.

<details>
<summary> ArrowlessNumberControl.js</summary>

```js
// Copyright 2019, University of Colorado Boulder

/**
 * A specific NumberControl for this sim that doesn't have tweaker buttons.
 *
 * @author Andrea Lin (PhET Interactive Simulations)
 * @author Michael Kauzmann (PhET Interactive Simulations)
 */
define( require => {
  'use strict';

  // modules
  const Dimension2 = require( 'DOT/Dimension2' );
  const merge = require( 'PHET_CORE/merge' );
  const NumberControl = require( 'SCENERY_PHET/NumberControl' );
  const projectileMotion = require( 'PROJECTILE_MOTION/projectileMotion' );
  const ProjectileMotionConstants = require( 'PROJECTILE_MOTION/common/ProjectileMotionConstants' );
  const StringUtils = require( 'PHETCOMMON/util/StringUtils' );
  const Text = require( 'SCENERY/nodes/Text' );
  const Util = require( 'DOT/Util' );

  const pattern0Value1UnitsWithSpaceString = require( 'string!PROJECTILE_MOTION/pattern0Value1UnitsWithSpace' );

  // constants
  const LABEL_OPTIONS = ProjectileMotionConstants.PANEL_LABEL_OPTIONS;

  class ArrowlessNumberControl extends NumberControl {

    /**
     * Auxiliary function that creates a NumberControl
     * @param {string} labelString - label for the parameter
     * @param {string} unitsString - units
     * @param {Property.<number>} valueProperty - the Property that is set and linked to
     * @param {Range} range - range for the valueProperty value
     * @param {Number} round - for minor ticks
     * @param {Object} [options]
     * @returns {VBox}
     */
    constructor( labelString, unitsString, valueProperty, range, round, options ) {

      options = merge( {
        containerWidth: 200,
        textDisplayWidth: 20,
        xMargin: 8,
        numberDisplayOptions: merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS, {
          valuePattern: StringUtils.fillIn( pattern0Value1UnitsWithSpaceString, { units: unitsString } ),
          decimalPlaces: null
        } ),
        titleNodeOptions: merge( {}, LABEL_OPTIONS ),
        sliderOptions: {
          constrainValue: value => Util.roundToInterval( value, round ), // two decimal place accuracy
          majorTickLength: 12,
          minorTickLength: 5,
          minorTickSpacing: round,
          tickLabelSpacing: 2,
          trackSize: new Dimension2( options.containerWidth - 2 * options.xMargin - 30, 0.5 ),
          thumbSize: new Dimension2( 13, 22 ),
          thumbTouchAreaXDilation: 6,
          thumbTouchAreaYDilation: 4, // smaller to prevent overlap with above number spinner buttons
          majorTicks: [
            { value: range.min, label: new Text( range.min, LABEL_OPTIONS ) },
            { value: range.max, label: new Text( range.max, LABEL_OPTIONS ) }
          ]
        },
        includeArrowButtons: false,
        layoutFunction: NumberControl.createLayoutFunction4( {
          sliderPadding: options.xMargin / 2
        } )
      }, options );

      assert && assert( options.numberDisplayOptions.maxWidth === undefined, 'ArrowlessNumberControl sets numberDisplayOptions.maxWidth' );
      options.numberDisplayOptions.maxWidth = options.textDisplayWidth * 1.2;

      assert && assert( options.titleNodeOptions.maxWidth === undefined, 'ArrowlessNumberControl sets titleNodeOptions.maxWidth' );
      options.titleNodeOptions.maxWidth = options.containerWidth - 3 * options.xMargin - options.numberDisplayOptions.maxWidth;

      super( labelString, valueProperty, range, options );
    }
  }

  return projectileMotion.register( 'ArrowlessNumberControl', ArrowlessNumberControl );
} );
```

</details>

**Comment by zepumph** [comment]
That makes sense, and would work, but it means that that isn't an option. I don't see a reason to convert to a pattern that would then disallow something as optional as `maxWidth` to not be provided if needed by another usage.
Maybe the best way would be to only include the optional items that rely on other options in the second block, like so:

<details> <summary>options needing other options in second block</summary>

```js
// Copyright 2019, University of Colorado Boulder

/**
 * A specific NumberControl for this sim that doesn't have tweaker buttons.
 *
 * @author Andrea Lin (PhET Interactive Simulations)
 * @author Michael Kauzmann (PhET Interactive Simulations)
 */
define( require => {
  'use strict';

  // modules
  const Dimension2 = require( 'DOT/Dimension2' );
  const merge = require( 'PHET_CORE/merge' );
  const NumberControl = require( 'SCENERY_PHET/NumberControl' );
  const projectileMotion = require( 'PROJECTILE_MOTION/projectileMotion' );
  const ProjectileMotionConstants = require( 'PROJECTILE_MOTION/common/ProjectileMotionConstants' );
  const StringUtils = require( 'PHETCOMMON/util/StringUtils' );
  const Text = require( 'SCENERY/nodes/Text' );
  const Util = require( 'DOT/Util' );

  const pattern0Value1UnitsWithSpaceString = require( 'string!PROJECTILE_MOTION/pattern0Value1UnitsWithSpace' );

  // constants
  const LABEL_OPTIONS = ProjectileMotionConstants.PANEL_LABEL_OPTIONS;

  class ArrowlessNumberControl extends NumberControl {

    /**
     * Auxiliary function that creates a NumberControl
     * @param {string} labelString - label for the parameter
     * @param {string} unitsString - units
     * @param {Property.<number>} valueProperty - the Property that is set and linked to
     * @param {Range} range - range for the valueProperty value
     * @param {Number} round - for minor ticks
     * @param {Object} [options]
     * @returns {VBox}
     */
    constructor( labelString, unitsString, valueProperty, range, round, options ) {

      options = merge( {
        numberDisplayOptions: merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS ) // we don't own this constant
      }, {
        containerWidth: 200,
        textDisplayWidth: 20,
        xMargin: 8,
        numberDisplayOptions: {
          valuePattern: StringUtils.fillIn( pattern0Value1UnitsWithSpaceString, { units: unitsString } ),
          decimalPlaces: null
        },
        sliderOptions: {
          constrainValue: value => Util.roundToInterval( value, round ), // two decimal place accuracy
          majorTickLength: 12,
          minorTickLength: 5,
          minorTickSpacing: round,
          tickLabelSpacing: 2,
          thumbSize: new Dimension2( 13, 22 ),
          thumbTouchAreaXDilation: 6,
          thumbTouchAreaYDilation: 4, // smaller to prevent overlap with above number spinner buttons
          majorTicks: [
            { value: range.min, label: new Text( range.min, LABEL_OPTIONS ) },
            { value: range.max, label: new Text( range.max, LABEL_OPTIONS ) }
          ]
        },
        includeArrowButtons: false
      }, options );

      // local vars used for layout and formatting
      const textDisplayWidth = options.textDisplayWidth * 1.2;
      const parameterLabelOptions = merge( {}, LABEL_OPTIONS, {
        maxWidth: options.containerWidth - 3 * options.xMargin - textDisplayWidth
      } );

      // Options that use other options for their default values
      options = merge( {
        titleNodeOptions: parameterLabelOptions
      }, {
        sliderOptions: {
          trackSize: new Dimension2( options.containerWidth - 2 * options.xMargin - 30, 0.5 ),
        },
        layoutFunction: NumberControl.createLayoutFunction4( {
          sliderPadding: options.xMargin / 2
        } ),
        numberDisplayOptions: {
          maxWidth: textDisplayWidth
        }
      }, options );

      super( labelString, valueProperty, range, options );
    }
  }

  return projectileMotion.register( 'ArrowlessNumberControl', ArrowlessNumberControl );
} );

```

</details>


Personally, I really don't like this. I think my favorite thus far is currently what's committed. If we disallow multiple merge blocks, it seems like we don't have a pattern for options relying on other options. This, especially noting the hierarchical power of `merge`, seems problematic. @pixelzoom should we try to discuss this at options/config meetings coming up?

**Comment by pixelzoom** [comment]
> That makes sense, and would work, but it means that that isn't an option. 

If you want `maxWidth`s to be overridable, then replace the assertion with expressions that set defaults if they aren't provided, i.e.:


```js
if ( options.numberDisplayOptions.maxWidth === undefined ) {
  options.numberDisplayOptions.maxWidth = options.textDisplayWidth * 1.2;
}

if ( options.titleNodeOptions.maxWidth === null ) {
  options.titleNodeOptions.maxWidth = options.containerWidth - 3 * options.xMargin - options.numberDisplayOptions.maxWidth;
}
```
<br>

> Personally, I really don't like this. I think my favorite thus far is currently what's committed.

Sorry, but I disagree, what's currently committed is a mess.  There are so many other problems with it:

* And most importantly, it requires me to inspect and mentally merge multiple object literals in order to figure out what is going on here. 
* It obfuscates what is really being done, which is to set `maxWidth` for the title and NumberDisplay.
* The second `merge` call sets `numberDisplayOptions` twice.
* `const textDisplayWidth = options.textDisplayWidth * 1.2` hijacks an option name, and gives it an entirely different value.
* ...

**Comment by pixelzoom** [comment]
> That makes sense, and would work, but it means that that isn't an option. 

If you want `maxWidth`s to be overridable, then replace the assertion with expressions that set defaults if they aren't provided, i.e.:


```js
if ( options.numberDisplayOptions.maxWidth === undefined ) {
  options.numberDisplayOptions.maxWidth = options.textDisplayWidth * 1.2;
}

if ( options.titleNodeOptions.maxWidth === null ) {
  options.titleNodeOptions.maxWidth = options.containerWidth - 3 * options.xMargin - options.numberDisplayOptions.maxWidth;
}
```
<br>

> Personally, I really don't like this. I think my favorite thus far is currently what's committed.

Sorry, but I disagree, what's currently committed is a mess.  There are so many other problems with it:

* Most importantly, it requires me to inspect and mentally merge multiple object literals in order to figure out what is going on here. 
* It obfuscates the reason for using multiple `merge` calls, which is to set `maxWidth` for the title and NumberDisplay.  And which (as I've demonstrated) can be done more clearly without multiple `merge` calls.
* The second `merge` call sets `numberDisplayOptions` twice, for apparently no reason.
* `const textDisplayWidth = options.textDisplayWidth * 1.2` hijacks an option name, and gives it an entirely different value.
* ...

**Comment by pixelzoom** [comment]
Looks like I didn't address this use of `options.xMargin` in my patch:

```js
        layoutFunction: NumberControl.createLayoutFunction4( {
          sliderPadding: options.xMargin / 2
        } )
```

It would be addressed the same way as `maxWidth` was addressed:

```js
// Provide default for layoutFunction
if ( options.layoutFunction === null ) {
  options. layoutFunction = NumberControl.createLayoutFunction4( {
          sliderPadding: options.xMargin / 2
        } );
}
```

Or now that we have 3 defaults that need to be filled in after the first `merge`, use another `merge`:

```js
// Fill in defaults for things that are dependent on other option values.
// All of these can be overridden by the client, so put default first in the merge call.
const numberDisplayMaxWidth = options.textDisplayWidth * 1.2;
options = merge( {
  numberDisplayOptions: {
    maxWidth: numberDisplayMaxWidth
  },
  titleNodeOptions: {
    maxWidth: options.containerWidth - 3 * options.xMargin - numberDisplayMaxWidth
  },
  layoutFunction: NumberControl.createLayoutFunction4( {
    sliderPadding: options.xMargin / 2
  } )
}, options );
```

**Comment by arouinfar** [comment]
It looks like @zepumph and @pixelzoom have already made a lot of progress on this issue. I realize my opinions may be a bit moot now, but since I was asked...

Personally, I don't think that tweaker buttons add anything to the UX of the snappy slider. They are a bit redundant, but they also don't hurt anything. Since these sliders appear on other screens as full-fledged NumberControls with tweakers, you could argue it's more consistent to have them in this sim. 

However, I can think of other simulations where we really wouldn't need the tweakers to accompany a snappy slider + readout, particularly in situations where there may be space constraints, so I am glad we now have an ArrowlessNumberControl.

And yes, not being able to click on the slider track to move the thumb definitely sounds like a bug to me.

**Comment by pixelzoom** [comment]
@arouinfar said:
> However, I can think of other simulations where we really wouldn't need the tweakers to accompany a snappy slider + readout, particularly in situations where there may be space constraints, so I am glad we now have an ArrowlessNumberControl.

ArrowlessNumberControl is not in common code, it's specific to Projectile Motion.

**Comment by pixelzoom** [comment]
@arouinfar said:
> And yes, not being able to click on the slider track to move the thumb definitely sounds like a bug to me.

We determined that you can click in the track.  It's just difficult because the pointer areas for the track are very small.  Up to you whether to address it.

**Comment by arouinfar** [comment]
> We determined that you can click in the track. It's just difficult because the pointer areas for the track are very small. Up to you whether to address it.

Thanks for the clarification. I don't think this is critical to address, but I'll defer to @zepumph.

**Comment by pixelzoom** [comment]
More on `options`...

When I proposed having ArrowlessNumberControl take control of `maxWidth` for title and NumberDisplay, @zepumph said:
> That makes sense, and would work, but it means that that isn't an option.

Looking at all call sites for `new ArrowlessNumberControl`, I see no cases that provide maxWidths. And in fact you've add option `textDisplayWidth` as a means of controlling those maxWidths.

I also see that for all instances of `ArrowlessNumberControl`, the 3 problematic options (`containerWidth`, `textDisplayWidth`, `xMargin`) have identical values, taken from ProjectileMotionConstants.RIGHTSIDE_PANEL_OPTIONS  (`minWidth`, `textDisplayWidth`, `xMargin` respectively).  

So I'm trying to understand the justification for having this much complication in ArrowlessNumberControl.  It's a sim-specific component, and you want all of these components to be styles the same.  So you could replace these options with local constants in ArrowlessNumberControl, and problem solved.

**Comment by pixelzoom** [comment]
Here's a compromise that I think might address both of our concerned. Happy to discuss.

<details>
<summary>Patch</summary>

```
Index: js/common/view/ArrowlessNumberControl.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/ArrowlessNumberControl.js	(revision b403dc38e537235d9d0e0cdab325e498685627df)
+++ js/common/view/ArrowlessNumberControl.js	(date 1573231489509)
@@ -37,27 +37,28 @@
      * @returns {VBox}
      */
     constructor( labelString, unitsString, valueProperty, range, round, options ) {
+
+      // options used to compute other option values
       options = merge( {
         containerWidth: 200,
         textDisplayWidth: 20,
         xMargin: 8
       }, options );
 
-      // local vars used for layout and formatting
-      const textDisplayWidth = options.textDisplayWidth * 1.2;
-      const parameterLabelOptions = merge( {}, LABEL_OPTIONS, {
-        maxWidth: options.containerWidth - 3 * options.xMargin - textDisplayWidth
-      } );
-
+      // compute maxWidth for subcomponents
+      const numberDisplayMaxWidth = options.textDisplayWidth * 1.2;
+      const titleMaxWidth = options.containerWidth - 3 * options.xMargin - numberDisplayMaxWidth;
+      
+      // now specify the rest of the options
       options = merge( {
-        numberDisplayOptions: merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS ), // we don't own this constant
-        titleNodeOptions: parameterLabelOptions
-      }, {
-        numberDisplayOptions: {
+        titleNodeOptions: merge( {}, LABEL_OPTIONS, {
+          maxWidth: titleMaxWidth
+        } ),
+        numberDisplayOptions: merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS, {
           valuePattern: StringUtils.fillIn( pattern0Value1UnitsWithSpaceString, { units: unitsString } ),
           decimalPlaces: null,
-          maxWidth: textDisplayWidth
-        },
+          maxWidth: numberDisplayMaxWidth
+        } ),
         sliderOptions: {
           constrainValue: value => Util.roundToInterval( value, round ), // two decimal place accuracy
           majorTickLength: 12,
```

</details>

<details>
<summary>ArrowlessNumberControl.js</summary>

```js
// Copyright 2019, University of Colorado Boulder

/**
 * A specific NumberControl for this sim that doesn't have tweaker buttons.
 *
 * @author Andrea Lin (PhET Interactive Simulations)
 * @author Michael Kauzmann (PhET Interactive Simulations)
 */
define( require => {
  'use strict';

  // modules
  const Dimension2 = require( 'DOT/Dimension2' );
  const merge = require( 'PHET_CORE/merge' );
  const NumberControl = require( 'SCENERY_PHET/NumberControl' );
  const projectileMotion = require( 'PROJECTILE_MOTION/projectileMotion' );
  const ProjectileMotionConstants = require( 'PROJECTILE_MOTION/common/ProjectileMotionConstants' );
  const StringUtils = require( 'PHETCOMMON/util/StringUtils' );
  const Text = require( 'SCENERY/nodes/Text' );
  const Util = require( 'DOT/Util' );

  const pattern0Value1UnitsWithSpaceString = require( 'string!PROJECTILE_MOTION/pattern0Value1UnitsWithSpace' );

  // constants
  const LABEL_OPTIONS = ProjectileMotionConstants.PANEL_LABEL_OPTIONS;

  class ArrowlessNumberControl extends NumberControl {

    /**
     * Auxiliary function that creates a NumberControl
     * @param {string} labelString - label for the parameter
     * @param {string} unitsString - units
     * @param {Property.<number>} valueProperty - the Property that is set and linked to
     * @param {Range} range - range for the valueProperty value
     * @param {Number} round - for minor ticks
     * @param {Object} [options]
     * @returns {VBox}
     */
    constructor( labelString, unitsString, valueProperty, range, round, options ) {

      // options used to compute other option values
      options = merge( {
        containerWidth: 200,
        textDisplayWidth: 20,
        xMargin: 8
      }, options );

      // compute maxWidth for subcomponents
      const numberDisplayMaxWidth = options.textDisplayWidth * 1.2;
      const titleMaxWidth = options.containerWidth - 3 * options.xMargin - numberDisplayMaxWidth;
      
      // now specify the rest of the options
      options = merge( {
        titleNodeOptions: merge( {}, LABEL_OPTIONS, {
          maxWidth: titleMaxWidth
        } ),
        numberDisplayOptions: merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS, {
          valuePattern: StringUtils.fillIn( pattern0Value1UnitsWithSpaceString, { units: unitsString } ),
          decimalPlaces: null,
          maxWidth: numberDisplayMaxWidth
        } ),
        sliderOptions: {
          constrainValue: value => Util.roundToInterval( value, round ), // two decimal place accuracy
          majorTickLength: 12,
          minorTickLength: 5,
          minorTickSpacing: round,
          tickLabelSpacing: 2,
          trackSize: new Dimension2( options.containerWidth - 2 * options.xMargin - 30, 0.5 ),
          thumbSize: new Dimension2( 13, 22 ),
          thumbTouchAreaXDilation: 6,
          thumbTouchAreaYDilation: 4, // smaller to prevent overlap with above number spinner buttons
          majorTicks: [
            { value: range.min, label: new Text( range.min, LABEL_OPTIONS ) },
            { value: range.max, label: new Text( range.max, LABEL_OPTIONS ) }
          ]
        },
        includeArrowButtons: false,
        layoutFunction: NumberControl.createLayoutFunction4( {
          sliderPadding: options.xMargin / 2
        } )
      }, options );

      super( labelString, valueProperty, range, options );
    }
  }

  return projectileMotion.register( 'ArrowlessNumberControl', ArrowlessNumberControl );
} );
```

</details>

**Comment by zepumph** [comment]
Thank you @pixelzoom for diving into this with me. I like your patch above and ended up committing it with a few additions. 

I really hate this line:
`      const textDisplayWidth = options.textDisplayWidth * 1.2;`

So I factored out usages of that "* 1.2" to be another constant in the constants file. This got rid of that line in `ArrowlessNumberControl`. we

In the above comment you mentioned this as a compromise, which I agree. After completing the changes above, I thought above taking it one step further toward the pattern outlined in https://github.com/phetsims/projectile-motion/issues/197#issuecomment-550553893 for the maxWidth, but because I didn't feel like it was best to do for options in the first block, it seemed to just complicate things:

<details>

```diff
Index: js/common/view/ArrowlessNumberControl.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/ArrowlessNumberControl.js	(revision 3cf03fffd29394518d31cdf2421143e9ecd22979)
+++ js/common/view/ArrowlessNumberControl.js	(date 1573676375769)
@@ -43,14 +43,9 @@
         xMargin: 8
       }, options );
 
-      // compute maxWidth for subcomponents
-      const titleMaxWidth = options.containerWidth - 3 * options.xMargin - options.numberDisplayMaxWidth;
-
       // now specify the rest of the options
       options = merge( {
-        titleNodeOptions: merge( {}, ProjectileMotionConstants.PANEL_LABEL_OPTIONS, {
-          maxWidth: titleMaxWidth
-        } ),
+        titleNodeOptions: ProjectileMotionConstants.PANEL_LABEL_OPTIONS,
         numberDisplayOptions: merge( {}, ProjectileMotionConstants.NUMBER_DISPLAY_OPTIONS, {
           valuePattern: StringUtils.fillIn( pattern0Value1UnitsWithSpaceString, { units: unitsString } ),
           decimalPlaces: null,
@@ -77,6 +72,10 @@
         } )
       }, options );
 
+      if ( options.titleNodeOptions.maxWidth === undefined ) {
+        options.titleNodeOptions.maxWidth = options.containerWidth - 3 * options.xMargin - options.numberDisplayMaxWidth;
+      }
+
       super( labelString, valueProperty, range, options );
     }
   }

<details>

@pixelzoom please review the commit, and recommend if you would like to see anything done further.

**Comment by pixelzoom** [comment]
Changes look very nice.  I really like that you got rid of `const textDisplayWidth`.  

One more suggestion... In `ProjectileMotionConstants.RIGHTSIDE_PANEL_OPTIONS`, rename `.numberControlTextDisplayWidth` to `numberControlMaxWidth`, since that's what it is, and all of its usages look like this:

```js
// VectorsProjectilePanel
89 numberDisplayMaxWidth: options.numberControlTextDisplayWidth,
```

**Comment by zepumph** [comment]
Right! Done. Leaving for @jbphet. Please close if `ArrowlessNumberControl` seems like a worth while refactor.

**Comment by jbphet** [comment]
Seems like a good refactor and the code looks clean to me.  Closing.
