### ISSUE TITLE
Normal is spelled "Nomal"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#2]
![nomal](https://cloud.githubusercontent.com/assets/5863899/5782955/26683078-9d7c-11e4-9d32-3983e950e632.png)

**Comment by pixelzoom** [comment]
This is no longer a problem in master, see screenshot below. Closing.

![screenshot_228](https://cloud.githubusercontent.com/assets/3046552/25366022/2e9fe998-292a-11e7-8353-66aef120f622.png)
