### ISSUE TITLE
Dashes on the road don't scale

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#202]

**Comment by zepumph** [comment]
@arouinfar, this is likely something that was talked about before, but the road doesn't scale in and out. Would you like me add this in? I think this is a pretty low pixel polish, and would be fine just closing, up to you.

**Comment by arouinfar** [comment]
@zepumph let's not bother with scaling the dashes. I think they might end up being a bit less clear when zoomed all the way out. I do appreciate the suggestion, though!
