### ISSUE TITLE
Apply PhET-iO featured

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#205]
I think we are ready to start thinking about adding PhET-iO featured for this, so I'm making an issue. 

* Likely we will want to hold off, at least until the state work is more complete in #198. There may be a few other issues to look into.
* Are we going to add phetio featured for clients on the initial instrumentation for this sim?

**Comment by zepumph** [comment]
@kathy-phet @arouinfar, we are now ready for another design audit/phetioFeatured implementation. Assigning over to you.

**Comment by zepumph** [comment]
It is likely that this issue is out of date, I'm not sure if phetioFeatured has been done yet for this sim.

**Comment by arouinfar** [comment]
While this sim has had significant PhET-iO design review/iteration, it was never fully completed. Designating `phetioFeatured` comes towards the end of the design process and should be tracked as a part of a new design review. When the time comes, we should open up fresh issues. Let's close this one.
