### ISSUE TITLE
PhET-iO Instrument transformProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#207]
From https://github.com/phetsims/projectile-motion/issues/198.

**Comment by zepumph** [comment]
To do this I looked at instrumenting ModelViewTransform2 as a data type for PhET-iO. Poking around, it seems like the only important items to transfer on state would be the `entries` in the matrix, and the `type` of the matrix. We can likely just use something like Matrix3IO to do all the heavy lifting for ModelViewTransform2IO.

I implemented that above, and things worked very well for us. I would like @jonathanolson to review. Especially the Matrix3 and Matrix3IO code. Is this a safe way to recreate a Matrix3? Our use case is that we would like to be able to create it new each time state is set, and we want to deserialize the state of of serialized Matrix3. In this case, the matrix is being used to create a ModelViewTransform2, see ModelViewTransform2IO.fromStateObject.

* Is there anything I should be worried about just setting `entries` and `type`?
* Also note that I wasn't worried about storing the state of Transform3 fields like `transposeValid` or `inverseValid` because the MVT is created fresh on `fromStateObject`. Another way of saying that is that MVT2 is using data type serialization (where fromStateObject instantiates a new type), instead of reference type serialization.

**Comment by zepumph** [comment]
After discussing this issue with @samreid and @chrisklus, we think it would be easier for this case to uninstrument transformProperty, and instrument the `zoomProperty`. We should also refactor the transformProperty as a DerivedProperty, as it is derived solely from the zoom. This way studio can change the MVT without needing to know how to serialize a matrix across the frame.

**Comment by zepumph** [comment]
We will still keep around the matrix IO types for future use.

**Comment by zepumph** [comment]
I like this quite a bit better because zoomProperty is a NumberProperty with a slider in studio, and you can actually get better granularity than in the sim. Totally a win.

I'm going to leave this open for @jonathanolson to review the changes above in `Matrix3.js`. Are there any concerns with how I am serializing the Matrix3 and deserializing it?

**Comment by jonathanolson** [comment]
The current approach to serializing Matrix3 looks good.
