### ISSUE TITLE
high-level review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#22]
@ariel-phet asked me to do a high-level review of Projectile Motion, to make sure that the implementation is on track wrt architecture and coding standards. 

I will not be doing a complete code review, where I attempt to identify all specific issues via the [code review checklist](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md).  That code review will come later.

To be completed before @andrea-phet resumes work on the sim this summer.

**Comment by pixelzoom** [comment]
Thought this is not technically a code review, I'm going to label related issues with "code-review".

**Comment by pixelzoom** [comment]
In general, the sim looks good - nice job so far @andrea-phet!

I created issues for some high-level topics - see the issues linked above.   @andrea-phet feel free to ask me to elaborate on any of these.

Going forward, I think a good plan would be:

(1) Review the "Code Style Guidelines" section of the [PhET Development Overview](https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit).

(2) Review the [PhET code-review checklist](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md).  This is the checklist that the sim will ultimately need to pass.  If there's anything that's unfamiliar or unclear on the checklist, best to find out more about it now.

(3) Start with issue #18 (convert from PropertySet to Property), since it's only going to get more difficult to do this later.

(4) Address the other code-review issues linked to this issue.

(5) Have a developer do another quick high-level review.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet and @andrea-phet to proceed.

**Comment by andrea-phet** [comment]
Thanks so much @pixelzoom! I'll let you know if I have any questions.

**Comment by ariel-phet** [comment]
Sounds like a good plan @pixelzoom thanks for going over the sim

**Comment by andrea-phet** [comment]
Most of the issues related here have been addressed, and the few remaining will be a working progress or delayed till later. At this point, I think the sim is ready for a developer to do another high level review. @ariel-phet is anyone open to do so?

**Comment by pixelzoom** [comment]
@andrea-phet I'm wondering if you really need another high-level view.  Your code is in good shape. You've addressed just about everything from this issue.  And the sim will go through an official code review after it's feature complete.  Is there something else that you'd like high-level feedback on?

**Comment by ariel-phet** [comment]
@andrea-phet agreed with @pixelzoom I think you are good to go for the moment, the main point of this review was to get everything up to standard since you had been doing a fair bit of work during the school year without anyone "looking over your shoulder".

At this point, I think you can just finishing addressing the remaining issues noted here, and lean on @jbphet for advice and quick looks at code as you move forward.

**Comment by andrea-phet** [comment]
I agree with both of you. Can this issue be closed?

**Comment by pixelzoom** [comment]
Yep. Closed!
