### ISSUE TITLE
this.trajectories is poorly named

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#221]
Noted while working on https://github.com/phetsims/beers-law-lab/issues/244,where this sim was recommended as an exemplar for PhetioGroup.

In ProjectileMotionModel.js:

```js
    // @public {PhetioGroup.<Trajectory>} a group of trajectories, limited to MAX_NUMBER_OF_TRAJECTORIES
    // Create this after model properties to support the PhetioGroup creating the prototype immediately
    this.trajectories = Trajectory.createGroup( this, tandem.createTandem( 'trajectoryGroup' ) );
```

The name `this.trajectories` is confusing.  It's not trajectories at all, its a group that's used to instantiate trajectories.   And it doesn't match the tandem name.  Recommended to rename to `this.trajectoriesGroup`.

**Comment by pixelzoom** [comment]
Ditto for `trajectories` parameter name here. It should be `trajectoriesGroup`.

```
  /**
   * @param {PhetioGroup.<Trajectory>} trajectories
   * @param {number} tracerX - x initial position of the tracer
   * @param {number} tracerY - y initial position of the tracer
   * @param {Tandem} tandem
   * @constructor
   */
  function Tracer( trajectories, tracerX, tracerY, tandem ) {
```

**Comment by zepumph** [comment]
Yes that was quite sloppy. Thanks for the issue. Closing
