### ISSUE TITLE
Rename Tracer to DataProbe

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#222]
From https://github.com/phetsims/projectile-motion/issues/219, @arouinfar had a review comment like:

>The probe that reads data from the points along the trajectory is simply called the `tracer`, but a more informative name would be something like `dataProbe` which is a name we've decided to use in Natural Selection. Would it take a lot of restructuring to call this a `dataProbe`?

I'll get on it!

**Comment by zepumph** [comment]
Implemented above. Please review.

**Comment by arouinfar** [comment]
Looks great, thanks @zepumph
