### ISSUE TITLE
Explain and improve model.trajectoryGroup in studio

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#223]
From https://github.com/phetsims/projectile-motion/issues/219, @arouinfar had a review comment like:

>The `projectileMotion.introScreen.model.trajectoryGroup` is a bit hard to understand. Could you walk us through it?

Yes it is a bit weird. Basically every blue line is a trajectory, and when you fire multiple projectiles on the same trajectory, then it doesn't create a new `Trajectory` group member. Instead information about individual projectiles are housed in the nested `projectileObjects` element. 

Potential pain points, confusions, and improvements:
* Note that when you fire two projectiles on the same trajectory, it doesn't add a new trajectory (like `trajectory_1`) for the second shot, but it does increment the count in the PhetioGroup, such that if you move the cannon and fire again, the next trajectory made is `trajectory_2`. Weird!!! 
* `projectileObjects` doesn't display anything useful in studio. It would be nice if it  updated its current state as projectile objects fired. Though that may be a bit hard.
* Please provide a list of the desired specs for this, and we can discuss making it happen.

**Comment by arouinfar** [comment]
Discussed with @kathy-phet and @zepumph as a part of #244 and change requests are logged in #241 #242 and #243.
