### ISSUE TITLE
How to instrument vectorVisibilityProperties 

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#224]
From #219, @arouinfar had the review comment like:

>It's not really clear why projectileMotion.introScreen.view.vectorVisibilityProperties is in the view. This seems analogous to gravityAndOrbits.modelScreen.model.showGravityForceProperty (both toggle the visibility of a vector in the play area), which is in the model.

I see.  I also see `graphingQuadratics.exploreScreen.view.viewProperties`, which makes me feel like it is a bit better to just go with how the sim has implemented these. I can see them fitting in either, if there is a strong preference, then we can probably refactor, but to be honest I would prefer to see them in the view. They have nothing to do with the projectiles' model, and instead only with how information is displayed (hence the view). This is not to say that the GAO instrumentation is incorrect, but perhaps the decision in GAO would be different if there were multiple (4 in PM and 7 in GQ).

What do you think @arouinfar @kathy-phet?

**Comment by zepumph** [comment]
While we are at it over here, we should discuss the name too, from this comment in #219:

>The "VisibilityProperties" ending to projectileMotion.introScreen.view.vectorVisibilityProperties seems pretty close to visibleProperty, which is a bit of a loaded meaning. Perhaps we should name it something different? @kathy-phet can't remember what we decided for this.

I personally think that these Properties are in fact controlling the visibility of items, and items that aren't instrumented, and so don't have their own `visibleProperty` (which I think is the right thing to do). Thus to me the name makes sense. What might you prefer instead?

**Comment by arouinfar** [comment]
@zepumph thanks for the explanation! I can see how the `vectorVisibilityProperties` makes more sense in the view. Since our initial review we've also seen other sims with similar view properties. I'm happy to leave things the way they are. I'll leave this open so I can double check with @kathy-phet the next time we review this sim.

**Comment by arouinfar** [comment]
Reviewed in #244 

@zepumph several sims collect view properties in a container called `viewProperties`, and we'd like to do the same here. Can you rename `vectorVisbilityProperties` to `viewProperties`? This would apply to all relevant screens.

**Comment by zepumph** [comment]
This issue should be reviewed at the next time Projectile Motion is worked on.

**Comment by zepumph** [comment]
Alright, classes and tandems have been renamed to `viewProperties`. We now have:

`projectileMotion.introScreen.view.viewProperties.`
`projectileMotion.vectorsScreen.view.viewProperties.`
`projectileMotion.dragScreen.view.viewProperties.`


Anything else here @arouinfar?

**Comment by arouinfar** [comment]
Looks good, thanks!
