### ISSUE TITLE
User request: values of vectors

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#227]
> I was wondering if there are any options to see the V(x) and V(y) components VALUES on the projectile motion lab for any given MOMENT in time during the projectile path?  This would help greatly in UAM equation verifications.

**Comment by arouinfar** [comment]
This feature has been discussed in https://github.com/phetsims/projectile-motion/issues/151, and we ultimately decided against adding V(x) and V(y) readouts. I've moved this comment to that issue, and will close this as a duplicate.
