### ISSUE TITLE
Support setting a partial instead of total state

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#230]
From phetsims/phet-io#1697: There is 1 or more call to phetioStateEngine.stateSetEmitter.addListener. There is now a 2nd argument to the listener, which is a predicate that tests Tandems and returns true if they are in scope. We should check these listeners and see if any of them need to check whether they are in scope of a partial state set.

**Comment by zepumph** [comment]
I confirmed that the stateSetEmitter listener in the lab screen was called when other screens' were reset. While this particular case ended up just doing work that acted as a no-op, it still feels best to guard it. Closing
