### ISSUE TITLE
TimeSpeedProperty valid values don't match Time Speed radio buttons

### ISSUE THREAD

**Issue by Denz1994** [phetsims/projectile-motion#232]
Discovered during phetsims/scenery-phet#607:

In the studio view of Projectile Motion, searching for "TimeSpeedProperty" shows `Valid Values: Fast, Normal, Slow`. However, the radio buttons are limited to only "Normal" and "Slow". Selecting the "Fast" option in the studio view will deselect both radio buttons in the sim view and doesn't seem to change the sim speed.

I would expect the "Fast" option to not be present in the studio view as a valid value. Assigning responsible dev to investigate.

See this [comment](https://github.com/phetsims/scenery-phet/issues/607#issuecomment-634230315) under the "Studio" content for more context and a potential solution.

**Comment by jbphet** [comment]
Good observation @Denz1994.  I've remedied the situation by using the `validValues` option.  Closing.
