### ISSUE TITLE
Use PhetColorScheme.VELOCITY and PhetColorScheme.ACCELERATION

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#233]
In https://github.com/phetsims/scenery-phet/issues/621 we modernized the colors used for velocity and acceleration.

This sim currently uses similar colors for the velocity and acceleration fills, but should be updated to use PhetColorScheme.
https://github.com/phetsims/projectile-motion/blob/master/js/common/ProjectileMotionConstants.js#L57-L58

Assigning @zepumph since this change should be included in the next release and he's currently serving as interim responsible-dev while iO work is ongoing.

**Comment by zepumph** [comment]
Sounds good. I used the constants (always love a constant!), but the values were already the same, so there is no change in output. Closing.
