### ISSUE TITLE
Add Trajectory.projectileCountProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#241]
From a design meeting with @arouinfar and @kathy-phet. Please note parent issue in https://github.com/phetsims/projectile-motion/issues/244.

This count should be the total number of projectiles that have been launched on this trajectory. Note that Trajectory.projectileObjects.lengthProperty is only an implementation detail, and it only tracks the current objects.

**Comment by zepumph** [comment]
Added above, you can test with something like `projectileMotion.introScreen.model.trajectoryGroup.trajectory_0.projectileCountProperty`

**Comment by arouinfar** [comment]
Looks good, thanks!
