### ISSUE TITLE
Change several properties to readOnly: false

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#247]
For #244 

This is a reversal of a request in #219 (sorry @zepumph!)

Several parameters are constant on early screens but adjustable on the Lab screen. We originally requested that these properties be made read-only, but this would prevent a client from adjusting the values using an API.

While @zepumph has mentioned that it's possible to make the properties ready only on a sub-set of screens, we thought it would be best to make these readOnly: false on all screens. This will allow the client greater control of customization. 

@zepumph please make the following readOnly: false on ALL screens.
- [x] model.gravityProperty
- [x] model.projectileDiameterProperty
- [x] model.projectileDragCoefficientProperty
- [x] model.projectileMassProperty

**Comment by arouinfar** [comment]
@zepumph not sure if making these readOnly: false will automatically add a slider to the studio interface or not. If so, please disable it. We don't want to add an slider to studio to adjust these properties.

**Comment by zepumph** [comment]
Done. Note that I took out the readOnly, but added in phetioStudioControl: false, so there is still no slider to adjust in studio.

![image](https://user-images.githubusercontent.com/6856943/127041620-89795be0-bad5-46ce-8732-9dcf23416501.png)


Anything else here?

**Comment by arouinfar** [comment]
Thanks @zepumph! Looks good in master.
