### ISSUE TITLE
Cursor changes to 'pointer' over Diameter and Mass number displays

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#249]
Noted in master 4ed46d3649ed4d5e041e2717eb13c13eb423744b, all browsers on macOS 11.2, did not test on other platforms.

On the _Vectors_ and _Drag_ screens, the cursor changes to 'pointer' when it's over the Diameter or Mass number displays (part of a NumberControl, I assume) in the control panel.   This led me to believe that pressing these number displays would open a keypad (I was testing Keypad.js when I discovered this.)  This does not happen with other NumberControls, and there is no such cursor change in the published version 1.0.15.  So this seems like a regression.

**Comment by jbphet** [comment]
@pixelzoom - is this a duplicate of #239?

**Comment by pixelzoom** [comment]
Yep. Silly me. Closing.
