### ISSUE TITLE
Tweaks to projectileControlPanel

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#250]
For #244 

- [ ] Instrument the separator lines in the projectileControlPanels to  avoid situations like the screenshot below. See `phScale.microScreen.view.beakerControlPanel.separator` for an example in action.  When there multiple separators in a panel call them `separator1` and `separator2`. 
![image](https://user-images.githubusercontent.com/8419308/108951207-cde26a80-7624-11eb-8c1a-280d779b5764.png)
- [x] In `projectileMotion.vectorsScreen.view.projectileControlPanel`, instrument the "Cannonball" title as `titleNode` with `visibleProperty` and `textProperty` children. The cannonball icon does not need to be separately instrumented, but its visibility should listen to `titleNode.visibleProperty`.
- [ ] On the Drag screen, the icon next to the "Drag Coefficient" should be hidden when `projectileMotion.dragScreen.view.projectileControlPanel.dragCoefficientNumberControl.titleNode.visibleProperty` is false.

**Comment by zepumph** [comment]
(1) See elements like `projectileMotion.labScreen.view.projectileControlPanel.separator2.visibleProperty`


(2) Done. 


(3) This is actually harder than I thought. We don't have access to NumberControl's titleNode from outside the type, so I can't toggle visibility of `dragObjectDisplay` based on it. I'll have to keep thinking about it.

@arouinfar please review. How important is (3)?

**Comment by zepumph** [comment]
Sorry for the late commit coming in for (2)

**Comment by arouinfar** [comment]
Items (1) & (2) look good!

> (3) This is actually harder than I thought. We don't have access to NumberControl's titleNode from outside the type, so I can't toggle visibility of dragObjectDisplay based on it. I'll have to keep thinking about it.
>
>@arouinfar please review. How important is (3)?

Listening to `dragCoefficientNumberControl.titleNode.visibleProperty` isn't necessary. However, it'd be really nice to be able to hide the dragObjectDisplay. Could it be separately instrumented?

**Comment by zepumph** [comment]
Instrumented above. We now have `projectileMotion.dragScreen.view.projectileControlPanel.dragObjectDisplay.visibleProperty`

**Comment by arouinfar** [comment]
Looks good in master, thanks @zepumph.
