### ISSUE TITLE
Renaming model properties related to target

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#251]
For #244 

The model properties related to the targetNode are housed under `model.score` which we don't find to be particularly intuitive.

| Model | View |
| --- | --- |
|![image](https://user-images.githubusercontent.com/8419308/109042446-71676580-768d-11eb-90c9-6f37e38bad6d.png) | ![image](https://user-images.githubusercontent.com/8419308/109042556-92c85180-768d-11eb-8c16-f668ce3962db.png) |

Things we'd like to rename:
- [x] Change `model.score` to `model.target`
- [x] Change `model.score.targetXProperty` to `model.target.positionProperty`

**Comment by zepumph** [comment]
All has been complete here, please review.

**Comment by arouinfar** [comment]
Looks good in master, thanks!
