### ISSUE TITLE
targetNode should have an inputEnabledProperty

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#252]
For #244 

Related to https://github.com/phetsims/scenery/issues/1116

The targetNode is draggable, but some clients may want to disable this, so it needs a pickableProperty (or interactiveProperty, but that doesn't exist yet).

**Comment by zepumph** [comment]
See `projectileMotion.introScreen.view.targetNode.inputEnabledProperty` on any screen.

**Comment by arouinfar** [comment]
Looks good!
