### ISSUE TITLE
Add titleNode to labScreen.view.initialValuesPanel

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#256]
For #244

This is labScreen.view.initialValuesPanel
<img width="161" alt="Screen Shot 2021-02-24 at 5 56 57 PM" src="https://user-images.githubusercontent.com/8419308/109086933-b9a47900-76c9-11eb-9a10-74fd1f3985df.png">

We'd like to instrument the "Initial Values" title and give it a visibleProperty and textProperty. The tree structure would look like this:
```
initialValuesPanel
    visibleProperty
  + angleReadout
  + heightReadout
  - titleNode
       textProperty
       visibleProperty
  + velocityReadout
```

**Comment by zepumph** [comment]
It seems like most of this happened two days after opening this issue in https://github.com/phetsims/projectile-motion/commit/b703492f325720fe833ba55e832ae225eddb4bb5, as part of #219, but I don't see a paper trail on that structure over there.  Added a titleNode, but that is all.

Anyways. . . .

Please review in master, the readout textProperties are `phetioReadOnly: true`, is that correct?

**Comment by arouinfar** [comment]
The new titleNode looks good in master.

> the readout textProperties are phetioReadOnly: true, is that correct?

Yes, that's correct. The readout text should match the actual data in the sim.
