### ISSUE TITLE
Issues with model.altitudeProperty

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#258]
For #244

- [x] The inital/current value of `model.altitudeProperty.rangeProperty` is always null, which seems wrong. @zepumph can you investigate?

- [ ] Remove the slider in the studio interface. It's not necessary and it's currently buggy, possibly because of the rangeProperty issue.

**Comment by zepumph** [comment]
I added a range to the altitudeProperty, and that fixed the studio control, I'm happy to remove the studio slider if you would like, but I thought I'd check since it isn't doing any harm anymore.

**Comment by arouinfar** [comment]
Thanks @zepumph. The altitudeProperty looks good.
