### ISSUE TITLE
subdivide velocityControlPanel on intro screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#259]
For #244 

On the Intro Screen, the vectorsControlPanel could benefit from some subdivision, somewhat similar to what we did with the airReistanceControl in #225.

![image](https://user-images.githubusercontent.com/8419308/109107517-18301e00-76ef-11eb-9e6f-798e8d83b998.png)

Here's a proposed tree structure:

```
vectorsControlPanel
    visibleProperty
  - accelerationVectors
        visibleProperty
      - titleNode 
             visibleProperty
             textProperty
        (checkboxes & their children)
  - velocityVectors
        visibleProperty
      - titleNode 
             visibleProperty
             textProperty
        (checkboxes & their children)
```

* Create containers for velocity vectors and acceleration vectors
* Give each container a visibleProperty so all velocity-related or acceleration-related content can be hidden in one go
* Instrument the titles and add them to their respective containers.
* Make vector icons listen to the visibility of the corresponding label, so hiding the label also hides the icon.

**Comment by zepumph** [comment]
That should do it, please review. Please note, that this panel is custom only for the intro screen, so any other screen will not pick up these changes. Let me know if there is more to do.

**Comment by arouinfar** [comment]
Looks good in master, thanks!
