### ISSUE TITLE
Should we do anything about the "hello" keypad easter egg?

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#266]
Discovered in #265, the keypad will say hello using 43110 (lowercase ll) but not 43770 (uppercase L):

![image](https://user-images.githubusercontent.com/679486/122771073-51bf0300-d263-11eb-9a7d-5972cf677802.png)

@jbphet is listed as the responsible dev in the spreadsheet, but I (mis?)recalled @zepumph was working on this sim.  I'll assign both just in case.

**Comment by jbphet** [comment]
@samreid - I just took a look at this functionality in the sim, and I'm not sure why it exists.  It might be something that @andrealin was experimenting with, perhaps as she was learning about how to write PhET sims.  The functionality doesn't seem particularly important to me, so I'm wondering why it you've logged a bug about it not supporting upper case 'L' values.  Can you please clarify why you think this is worth spending time on?

**Comment by samreid** [comment]
It's probably just an easter egg, I was surprised to see it and it caused a minor complication (which I've already corrected) in https://github.com/phetsims/projectile-motion/issues/265.  Just wanted to raise awareness, the easter egg adds a little bit of code that needs to be maintained, and didn't work like I expected.  Up to you how to proceed, if at all.

**Comment by samreid** [comment]
I updated the title to make it clearer how we might proceed.

**Comment by jbphet** [comment]
It sounds like the problem has been corrected, and I don't mind the occasional, small, non-obtrusive Easter egg.  Let's just leave it as is.  Closing.
