### ISSUE TITLE
Tandem number being incremented in trajectory every time new projectile is added, even when no new Trajectory is created

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-motion#287]
Example: Fire two projectiles on the same trajectory, then change the launch values and fire another. New trajectory will be named 'trajectory_02' instead of 'trajectory_01'

**Comment by zepumph** [comment]
I think the gross code is here. Note that we need to create a new Trajectory just to decide if it is equal to the current one (then disposing the newly created one). Can we clean this up so that we can test for equality without creating a whole new Trajectory instance?
