### ISSUE TITLE
use descriptive names for panels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#29]
Related to #22 (high-level review).

`IntroVectorsPanel` and `DragVectorsPanel` are good names for those panels - I can run the sim and immediately know which panels those names refer to.

`IntroSecondPanel` and `LabSecondPanel` are not good names. "Second" is not descriptive enough to tell me what the panel contains, what its responsibilities are.  

In general, avoid names like "SecondPanel", "TopPanel", "BottomPanel".   If can't come up with a word or phrase that describes what's in the panel, then that panel likely doesn't contain things that are logically related, and that may be a sign of a larger design/usability problem.

**Comment by andrea-phet** [comment]
I named the top right control panel in each screen ProjectilePanel, as many of the properties are related to the projectile. Some are not, such as air resistance and altitude, but I think this naming convention will work for now.
