### ISSUE TITLE
Send 'projectile hit target' data to CODAP wrapper

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-motion#294]
@catherinecarter asked for boolean data in the CODAP wrapper for whether or not the projectile hit the target. This will allow for plotting binomial distributions / categorical data / law of large numbers.

Future discussion: Would it be useful to have data as the 'number of stars' (0, 1, 2, 3)? This could be processed within CODAP to a boolean, but would require an additional step.

**Comment by zepumph** [comment]
From co-review with @matthew-blackman:

- [ ] Why do we need to pass the entire target into the Trajectory? What about instead just a bound function (or arrow function) like `scoreTrajectory( position, trajectory )`. Not sure we need the trajectory instance, but just a thought!
- [ ] It makes more sense for Trajectory.ts to serialize a value that is the same numerical system that Target is making, so my preference would be for Trajectory to have a score of `null` (not landed yet) or 0-3. Then it can be up to the wrapper to put that into the Boolean that CODAP wants.
- [ ] We want to refactor Trajectory to make sure that the score data has been stored before we emit to the wrapper that we have a landed projectile. This could be done in a few ways that @matthew-blackman and I talked through, but I won't iterate through them now. Let me know if you want to discuss further!

**Comment by catherinecarter** [comment]
It doesn't matter to me how (or when) the marker for whether the trajectory has hit the target is passed into CODAP, just whether the projectile has hit it, even when the target has moved. 
A bonus would be to track how close the trajectory got to the target (the 0-3 rating), and it sounds like this is easier, so great!
It's ok if the rest (e.g., boolean) is done in the CODAP table by the user, although having both the boolean and the 0-3 rating would be extra bonus :) The categorical data would be useful for lessons where the learning goal was to differentiate between categorical vs quantitative data, as well as estimating probabilities from the proportion of successes. 
But the method of getting that data should definitely go the route of whatever is best for the now and future code.

**Comment by matthew-blackman** [comment]
Are we okay to close this issue?

**Comment by zepumph** [comment]
Who are you asking? Please assign if looking for comment from me.

**Comment by matthew-blackman** [comment]
The boolean data for whether the projectile has hit the target is now being sent into the CODAP wrapper.
