### ISSUE TITLE
Explore 'Cluster size' feature for Stats screen

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-motion#295]
Looking at ways to add controls for the number of simultaneous projectiles launched in the 'Stats' screen.

**Comment by matthew-blackman** [comment]
Just added a first prototype to bayes: [https://phet-dev.colorado.edu/html/projectile-motion/1.1.0-dev.21/phet/projectile-motion_en_phet.html](url)

**Comment by catherinecarter** [comment]
I love how the number of projectiles can be changed - super neat. I have a couple of comments to open for discussion:

1.    The word, "cluster," is the name of a random sampling method in statistics and might confuse statistics students who are looking for "sample size." I will do some research about statistics language, and I'll also lean on you science people for vocab/language conventions about what "cluster" means from your end and how we can meet the needs of both communities.
2.   The spinner is cool, but changing by 1 might get tedious if wanting to go from the number of projectiles being launched from 2 to 30. Wondering if we can combine something to change the number of projectiles more quickly. I like how you can change the number of projectiles by 1's and wouldn't want to remove this. I wonder if we could include an "increment" button (or pull-down menu, radio button, or whatever works there) as well so the spinner would go by 2's, or 5's, or 10's? 
<img width="697" alt="image" src="https://user-images.githubusercontent.com/109630002/197018800-91f20344-6d16-4260-b22d-b8a05e0fa06d.png"> (not exactly what I have in mind, but you get the idea)
3.   Is the number of projectiles launched at a time being captured in the table in CODAP already? If so - great! If not, we need to make sure it's being sent along with the other data.

**Comment by matthew-blackman** [comment]
1. We can workshop the name, but I think we should be looking for a neutral term to convey "the number of simultaneously launched projectiles". Sample size doesn't make sense to me - science teachers would not consider launching a cannon to be "sampling" anything, it's just launching a cannon.

**Comment by matthew-blackman** [comment]
2. Let's try to avoid adding additional UI for what should be a single control. Perhaps a dropdown menu would work better? Groups of 5, 10, 15, 20, 25?

**Comment by matthew-blackman** [comment]
3. This is very tricky because we are capturing the projectiles as they land, not as they are launched. How do you see this working?

**Comment by catherinecarter** [comment]
For #1 and 2, I like the idea of a slider (and neutral language as well):
![image](https://user-images.githubusercontent.com/109630002/197027141-c6ac64ec-9b32-4b59-941a-433e7de289e3.png)

A question for you: is it possible for a slider to snap at 1, 2, 5, and then by 5's after that? Or does it have to be a set increment? I don't know how that code works.

For #3, I'm not 100% sure how it would work, but I'm envisioning something similar to the user-set parameters of the speed/SD and angle/SD that's being sent to the table. Not sure how you made that happen, but it seems plausible as an option. As I said above, though, I don't know how to code works :)

**Comment by matthew-blackman** [comment]
We found that projectile group size was best to implement as a slider bar with increments of 5. This has been fully explored and tested in the stats screen. We have also found no performance issues for groups of less than ~50 projectiles launched simultaneously.
