### ISSUE TITLE
When to delete landed projectiles?

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-motion#296]
When should we be deleting landed projectiles? It is relevant that deleting large numbers of projectiles at the same time can cause performance slowdowns.

**Comment by matthew-blackman** [comment]
Yes that's right. I think the current version is okay, but if the user keeps clicking the blue 'fire multiple' button very quickly, the results can be a bit strange. Thoughts on this?

**Comment by catherinecarter** [comment]
Well, when I pressed the blue button multiple times (as quickly as I could), I definitely noticed some of the projectiles being deleted, but I was ok with it. I think we could include it as an interview question and see if users mention it as an awkward interaction (if we have interviews with students on this one, I don't know).

**Comment by matthew-blackman** [comment]
When a new projectile (or group of projectiles) is fired, the sim checks to see if the total number of projectiles exceeds a limit (right now set to 150). If the total number (including landed projectiles) is over this limit, the sim will delete landed projectiles at random until the total number (including the newly launched projectiles) is under the limit. This seems like a good behavior to me. We can revisit this in the final design phase as part of the data fluency design process.
