### ISSUE TITLE
Words Occasionally Flash After Loading

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#3]
More often than not, "Score!", "Collision!", "Slow-Mo", and "Paused" flash on the screen when the sim is loaded or refreshed.

![projmoti](https://cloud.githubusercontent.com/assets/5863899/5783379/9fe5d5a6-9d7f-11e4-8d69-e198152b861d.gif)

Seen on Win 8.1 browsers and Chromebook
Version: 2.03.14 (72977)
Build Date: May 14, 2013
Flash Version: WIN 16,0,0,257
OS: Windows 8.1

**Comment by pixelzoom** [comment]
@phet-steele Looks like this report is for the Flash version, so I'm labeling with "legacy-bug".  Correct me if I got that wrong.

**Comment by ariel-phet** [comment]
Shouldn't be in an issue in HTML5 version, closing
