### ISSUE TITLE
CODAP layout shift and sizing of embedded PhET sim

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-motion#303]
1. The embedded Projectile Motion sim in CODAP is experiencing layout issues on initial load.
2. We need to decide on the initial size/position of all embedded components, including the embedded sim.

**Comment by zepumph** [comment]
Seems reasonable to me! Let me know how it goes.

**Comment by catherinecarter** [comment]
I'm wondering what it would look like if we made it a little taller and little less wide, just in case someone is on an iPad or something, the sim would be just a bit smaller, but not diminish from the sim being prominent. Maybe 45% wide? I don't know what the height currently is set to, or if it's set at all. Can we try about 10% taller? Not sure if it's doable. Thanks!

**Comment by zepumph** [comment]
I wonder if you  can ask codap for their current available layout space.

**Comment by catherinecarter** [comment]
Good idea. I'll put it on the list of things to include when we meet with the CODAP folks next.

**Comment by matthew-blackman** [comment]
Unassigning as we will resume CODAP issues on the next wrapper sprint.
