### ISSUE TITLE
Cannon flash animation looks a bit off

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-motion#304]
The animation of the cannon flash in the previous version looks a little off. The graphic grows at a constant rate and then instantly disappears. We can make it look more like a real cannon flash by adjusting the lerping.

**Comment by matthew-blackman** [comment]
I updated the animation using an ease-out function to make it look more like a real muzzle flash - [](https://phet-dev.colorado.edu/html/projectile-motion/1.1.0-dev.37/phet/projectile-motion_en_phet.html)

**Comment by arouinfar** [comment]
@matthew-blackman the updated flash looks nice. It's an improvement over the original animation -- still whimsical and functional, but less harsh/distracting. I think it's a keeper.

I took a few quick clips in case we ever want to compare it side-by-side in the future.

https://user-images.githubusercontent.com/8419308/197886022-4c479342-603d-4708-b01d-22c6c4b2854b.mov

https://user-images.githubusercontent.com/8419308/197886023-687a829f-74b2-46af-bae4-e9d90f451f2f.mov
