### ISSUE TITLE
conventions for naming model and view types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#31]
Related to #22 (high-level review).

A quick tutorial on PhET naming conventions for model and view types, and variables of those types...

If I have a "measuringTape" abstraction, then the model element will typically be named `MeasuringTape` and the view element will be `MeasuringTapeNode`.   Variables of those types would be `measuringTape` and `measuringTapeNode` respectively.   The take-away here is that the model type and variable name don't typically have a "Model" suffix, while the view types and variables names have a "Node" suffix.

Model and view type names in this sim are following this convention.  Variable names are mostly following this convention.  I noticed a couple of violations in `ProjectileMotionModel`: `this.scoreModel` and `this.traceModel`, which should be `this.score` and `this.trace` respectively.

**Comment by pixelzoom** [comment]
I should mention that the exception to this convention is the top-level model "container", whose top-level type and variable name always has a "Model" suffix.  E.g. `IntroModel` and `var introModel`.

**Comment by andrea-phet** [comment]
Ignore above reference
