### ISSUE TITLE
Improve accuracy of apex y-position calculation

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-motion#312]
The previous way that the apex of a trajectory is calculated is using the linear interpolation of the old and new y-coordinates. This is only accurate if the object has a constant velocity, so will not correctly model the y-position of the apex. We can improve this by using a quadratic function with the dtToApex value. 

Note: This will an approximation if air resistance is turned on, just like all of the other calculations in the step function.

**Comment by zepumph** [comment]
Looks great. Anything else here?

**Comment by matthew-blackman** [comment]
@zepumph and I confirmed that this improves calculation of the apex height. Any further improvements require integration. Closing this issue.
