### ISSUE TITLE
use visibility annotations for fields

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#32]
Related to #22 (high-level review).

All fields and functions that are part of a types publicly accessible API must have a visibility annotation.

In the [PhET Development Overview](https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit#heading=h.1oxr3ptyo50w), read the section on visibility annotations. It starts with "Because JavaScript lacks visibility modifiers".

Let me know if you want to collaborate on adding these, because there are some shortcuts that are not obvious in the Google doc.

**Comment by andrea-phet** [comment]
@pixelzoom can we collaborate on adding these?

**Comment by pixelzoom** [comment]
Yes.  Can't collaborate today, but ping me tomorrow.

**Comment by pixelzoom** [comment]
@andrea-phet and I collaborated on this.

**Comment by andrea-phet** [comment]
Assigning to @pixelzoom to review. Could you look over everything except for CustomizeDialog? I will be deleting that when I start working on the lab screen.

**Comment by pixelzoom** [comment]
I won't be able to get to this until Monday, June 12.

**Comment by pixelzoom** [comment]
Annotations look like they are in good shape, nice job @andrea-phet!  It looks like you know what to do going forward, but feel free to ask if you have future questions.   Annotations will be reviewed again by whoever does code review, so I'll close this issue.
