### ISSUE TITLE
Commented out fill

### ISSUE THREAD

**Issue by zepumph** [phetsims/projectile-motion#321]
I'm not sure why this fill was commented out in https://github.com/phetsims/projectile-motion/commit/cd31d599d11d63b4c081aaa9a80a82388bb1904f#diff-4d3815a80bd73740931e387e7d9233b843e4c5c0c9acfdbaad565219ba8db5bdR454

https://github.com/phetsims/projectile-motion/blob/master/js/common/view/ProjectileMotionScreenView.ts#L435

Any thoughts @matthew-blackman?

**Comment by matthew-blackman** [comment]
Good find! I uncommented the line and updated the property to iconFill. Tested and it's propagating into the step button. If all looks good this can be closed.
