### ISSUE TITLE
Review code for reuse

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#324]
For an up-coming new sim, PhET may want to reuse code from Projectile Motion, possibly creating a shared repository.  To that end, @kathy-phet asked me to do a review of the projectile-motion code base.

**Comment by pixelzoom** [comment]
Noting that the projectile-motion repo was created on 1/7/15, over 8 years ago.  And 1.0.0 was pubished on 8/23/2017.  So this is some relatively old code.

**Comment by pixelzoom** [comment]
In the simplest case (firing 2 projectiles on the Intro screen) the sim is in an incorrect state when the Standard wrapper is launched from Studio. The indicators on the field that show where the projectiles landed are missing.  This does not bode well for the PhET-iO implementation.

**Comment by pixelzoom** [comment]
Evaluation of major PhET features:

**PhET-iO**: Instrumentation is incomplete. The sim definitely has problems in the Standard and State wrappers. The Studio tree structure looks like a good start, but needs work.

**Alt Input**: Not currently supported. No evidence of pdomOrder being set, and "supportsInteractiveDescription" is not being set in package.json.

**UI Sound**: Not currently supported. "supportsSound" is not set in package.json.

**Dynamic Locale**: Not currently supported.  Only 4 uses of StringProperty in the entire code base. Almost exclusively static strings passed to Text and RichText.

**Comment by pixelzoom** [comment]
TypeScript: Partially converted. 62% of the sim is TypeScript, with 3599 lines of JavaScript that still needs to be converted.  All of projectile-motions/js/common/ has been converted, so the remaining work is in screen-specific code.

**Comment by pixelzoom** [comment]
## Evaluation of potential for code reuse

PM = Projectile Motion
PM:DL = Projectile Motion: Data Lab

## View:

Since the view requirements of PM:DL will be different, I didn’t spend a lot of time evaluating the reusability of view components. We can certainly appropriate view components if they happen to be the same in both sims.  But that can be evaluated “on the fly” as PM:DL is being implemented.  I see no reasons (or opportunity) to eagerly factor out view components for reuse.   And given the age of this code, reuse is highly likely to involve bring old code up to new standards.

## Model:

Here’s a list of the model classes in PM, and their suitabiltiy for reuse in PM:DL:

* DataPoint — Not reusable. PMDL shows no data points on a projectile’s trajectory.
* DataProbe - Not reusable. PMDL has no data probe
* ProjectileMotionMeasuringTape - Unlikely to be reusable. PMDL appears to have very different requirements/constraints for the measuring tape
* ProjectileMotionModel - Not reusable. This is a flat structure of dozens for properties, very specific to PM.
* ProjectileObjectType - Unlikely to be reusable. PMDL has fewer projectiles, and different data that those projectiles need to carry.
* Target - Not reusable. PMDL has a more sophisticated, resizable target.
* Trajectory - Unlikey to be reusable. PM has multiple projectiles on 1 trajectory.
* EditableProjectileObjectType - Not reusable, specific to the Lab screen of PM. This is an editable version of ProjectileObjectType, but none of it is currently stateful. And PMDL does not have editable projectiles.

## Conclusions

There is nothing obvious in the PM code base that provides a reason to eagerly create a shared repository. Creating such a repository will not reduce the time required to develop PM:DL. On the contrary, it will likely increase the time required, and destabilize PM.
 
My recommendation regarding shared code is:
* Developers should be familiar with the PM code base.
* Proceed with developing a new code base for PM:DL.
* Use what we know about the PM code base to identify potential reuse as PM:DL implementation proceeds.
* If opportinities for reuse arise, evaluate whether the amount of potential reuse, and condition of the code to be reused, warrants creation of a shared repository.

**Comment by pixelzoom** [comment]
@kathy-phet @matthew-blackman @AgustinVallejo @catherinecarter This is ready for your review. And I'm happy to discuss further.   The last person assigned may close this issue.

**Comment by catherinecarter** [comment]
Thanks for doing such a thorough review of the PM code, @pixelzoom. It sounds like starting fresh is the best path. 

I do wonder if keeping reusable components from PM:DL on our radar for future sims might be useful. I don't know what next sims will look like, but if there's structure built into the code from PM:DL that are challenging to implement but important to reuse, would it be valuable to create a new repo as we go? Or better to identify later?

**Comment by pixelzoom** [comment]
> I do wonder if keeping reusable components from PM:DL on our radar for future sims might be useful. ...

I certainly try to do make things general/reusable where I think they might be reusable in future sims.  But there's an additional cost to do that, which must be balanced against milestones.   Also, PhET generally does not create common-code when it's only needed by one sim. The policy is that the 2nd sim to need something is responsible for migrating sim-specific code to common code, and generalizing it appropriately.
