### ISSUE TITLE
use phet.joist.random

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#33]
Related to #22 (high-level review).

From the [PhET code-review checklist](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md): 

> - [ ] Check that random numbers are generated using phet.joist.random, and are doing so after modules are declared (non-statically). For instance, the following methods (and perhaps others) should not be used:

For reproducibility of PhET-iO playback, sims should not create their own instances of `dot.Random`, or use lodash functions related to randomization (e.g. `_.shuffle`).  

`RandomIconFactory` will need to be fixed.

**Comment by andrea-phet** [comment]
Will not be using RandomIconFactory for actual implementation.

**Comment by pixelzoom** [comment]
FYI, RandomIconFactory is really no longer necessary. Joist now provides a default screen icon, see https://github.com/phetsims/joist/issues/339.

**Comment by andrea-phet** [comment]
Deleted only use of random, closing.
