### ISSUE TITLE
Decrease coupling between model and view

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#36]
Related to #22 (high-level review).

Unnecessary coupling is created by passing large objects to constructors, or exposing unnecessary properties/functions.   For example, consider the `IntroVectorsPanel` constructor:

```js
/**
 * @param {ProjectileMotionIntroModel} projectileMotionIntroModel
 * @constructor
 */
function IntroVectorsPanel( projectileMotionIntroModel, options )
```

`projectileMotionIntroModel` has a big public API, with many Properties. IntroVectorsPanel requires access to only 3 of those Properties.  By passing the entire model into the panel, you've given the panel access to things that it doesn't need.  

This revised constructor provides `IntroVectorsPanel` with exactly what it needs, nothing more, nothing less:

```js
/**
 * @param {Property.<boolean>} totalVelocityVectorOnProperty
 * @param {Property.<boolean>} componentsVelocityVectorsOnProperty
 * @param {Property.<boolean>} componentsAccelerationVectorsOnProperty
 * @param {Object} [options]
 * @constructor
 */
function IntroVectorsPanel( totalVelocityVectorOnProperty, componentsVelocityVectorsOnProperty, componentsAccelerationVectorsOnProperty, options )
```

The call site in `ProjectileMotionIntroScreenView` would change from this:

```js
      vectorsPanel: new IntroVectorsPanel( model )
```

to this:

```js
      vectorsPanel: new IntroVectorsPanel( model. totalVelocityVectorOnProperty, 
         model.componentsVelocityVectorsOnProperty, 
         model.componentsAccelerationVectorsOnProperty )
```

Other places where this principal should be applied (not a complete list):

CustomDialog
LabSecondPanel
IntroSecondPanel
ProjectilePanel
DragVectorsPanel

In a case like `ProjectileNode`, you might consider restructuring the model so that all of the Properties that control visibility of vectors (`componentsForceVectorsOnProperty`, etc.) are part of a sub-object, perhaps `model.vectorVisibilityProperties`.

**Comment by andrea-phet** [comment]
@pixelzoom Since CustomizeDialog affects almost ten properties within the model, would it be okay to just pass the model in, instead of individual properties? The point of the customize dialog is to be able to set up everything.

**Comment by pixelzoom** [comment]
Yes, that seems reasonable for CustomizeDialog.

**Comment by andrea-phet** [comment]
I checked every js file and it looks good, closing.
