### ISSUE TITLE
move view-specific Properties out of model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#37]
Related to #22 (high-level review).

Several Properties in ProjectileMotionModel have nothing to do with the model.  They are purely view. Those Properties are:

```js
      // vectors visibility
      totalVelocityVectorOn: false,
      componentsVelocityVectorsOn: false,
      totalForceVectorOn: false,
      componentsForceVectorsOn: false,
      componentsAccelerationVectorsOn: false,
```

These should be moved out of the model, and encapsulated in the view.  

For a similar example, see `hookes-law.IntroViewProperties`.

**Comment by andrea-phet** [comment]
Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
Overall looks good.  

But there is a problem with `ProjectileMotionScreenView`.   It's constructor starts like this:

```js
  function ProjectileMotionScreenView( model, options ) {

    options = options || {};
    var self = this;
    ScreenView.call( this, options );

    var vectorVisibilityProperties = options.vectorVisibilityProperties;
```

In general, you shouldn't access an option that doesn't have a default value -- in this case `options.vectorVisibilityProperties`.   

Two options for correcting this:

(1) Pass `vectorVisibilityProperties` as a constructor parameter to `ProjectileMotionScreenView`.

(2) Have `ProjectileMotionScreenView` instantiate the  `VectorVisibilityProperties`.

 Option (1) looks more straightforward.  Option 2 is messy because you'd have to all the `ProjectileMotionScreenView`  constructor sooner in the subtype constructors.

**Comment by pixelzoom** [comment]
Ah, there is also a problem in DragScreenView.  You're adding Properties and redefining `reset` like this:

```js
    // contains properties about vector visibility, used in super class
    var visibilityProperties = new VectorVisibilityProperties();

    // vectors visibility for velocity and force, total or component
    visibilityProperties.velocityVectorsOnProperty = new Property( false );
    visibilityProperties.forceVectorsOnProperty = new Property( false );
    visibilityProperties.totalOrComponentsProperty = new Property( 'total' ); // or 'components'

...

    // reset for vectorVisibilityProperties needs to be updated with the new properties
    visibilityProperties.reset = function() {
      VectorVisibilityProperties.prototype.reset.call( this );
      this.velocityVectorsOnProperty.reset();
      this.forceVectorsOnProperty.reset();
      this.totalOrComponentsProperty.reset();
    };
```

Extension should be done through inheritance. Create a subtype of `VectorVisibilityProperties`, call it something like `DragScreenVectorVisibilityProperties`, implemented something like this (not tested):

```js
function DragScreenVectorVisibilityProperties() {
  VectorVisibilityProperties.call( this );
  
    // vectors visibility for velocity and force, total or component
    this.velocityVectorsOnProperty = new Property( false );
    this.forceVectorsOnProperty = new Property( false );
    this.totalOrComponentsProperty = new Property( 'total' ); // or 'components'
}

  projectileMotion.register( 'DragScreenVectorVisibilityProperties', DragScreenVectorVisibilityProperties );

  return inherit( VectorVisibilityProperties, DragScreenVectorVisibilityProperties, {

    // @public @override
    reset: function() {
      VectorVisibilityProperties.prototype.reset.call( this );
      this.velocityVectorsOnProperty.reset();
      this.forceVectorsOnProperty.reset();
      this.totalOrComponentsProperty.reset();
    }
  } );
```

**Comment by andrea-phet** [comment]
@pixelzoom Could you take a look at the above commit?

**Comment by pixelzoom** [comment]
Ah, I hadn't noticed that there were other options to ProjectileMotionScreenView that should also be constructor parameters -- good catch!   I reviewed the commit, looks good, feel free to close if there's nothing else to do here.

**Comment by andrea-phet** [comment]
Awesome, closing.
