### ISSUE TITLE
use assert

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#39]
Related to #22 (high-level review).

With the exception of `ToolboxNode`, this implementation does not contain any assertions.

Learn where and when to use `assert`.  Typically it's used to check for programming errors, including (but not limited to):

• Verifying that the value or type of a function argument is valid.
• Verifying that the result of a computation is what you expected.

Do not use `assert` to validate user inputs.  Use `throw Error` in that case.

**Comment by pixelzoom** [comment]
```js
// General form
assert && assert( expression, message );

// Example
assert && assert( y >= 0, 'invalid y: ' + y );
```

**Comment by andrea-phet** [comment]
I have been adding a couple asserts as I update the code. Will keep this in mind, and assigning @pixelzoom to review.

**Comment by pixelzoom** [comment]
I reviewed the current uses of `assert`, looks like you have the idea. 

LabIconNode and VectorIconNode have an assertion like this:

```js
assert && assert( type === 'nav' || type === 'screen', 'argument type should be nav or screen' );
```

In general, it's useful to include the value of `type` in the message, and not duplicate the valid values in the message (since they already appear in the expression).   So something like:

```js
assert && assert( type === 'nav' || type === 'screen', 'invalid value for type: ' + type );
```

The general idea is that if an assertion fails, the message will tell you what the bad value was, and you can inspect the assertion's expression to see specifically what condition was violated.

**Comment by pixelzoom** [comment]
@andrea-phet feel free to close this after reviewing the above comment.

**Comment by andrea-phet** [comment]
Reviewed, closing.
