### ISSUE TITLE
Cannon Platform can Detach

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#4]
If the cannon is dragged to change the height, and the mouse goes out of the sim boundaries before releasing the cannon, the cannon's platform will jump to the height of the mouse leaving the raised cylinder behind. Also notice in the video how the platform can slightly detach during the parts when it's being dragged quicker.

![projmoti2](https://cloud.githubusercontent.com/assets/5863899/5783657/387e2b68-9d82-11e4-869e-fbf7786f5815.gif)

Seen on Win 8.1 browsers and Chromebook
Version: 2.03.14 (72977)
Build Date: May 14, 2013
Flash Version: WIN 16,0,0,257
OS: Windows 8.1

**Comment by pixelzoom** [comment]
@phet-steele Looks like this report is for the Flash version, so I'm labeling with "legacy-bug".  Correct me if I got that wrong.

**Comment by ariel-phet** [comment]
Will be addressed in HTML5, closing
