### ISSUE TITLE
implement dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#42]
Related to #22 (high-level review).

Is there anything in this simulation that is dynamically create, then later thrown away?  If so, you'll need to learn how to handle memory management by implementing `dispose`.  And you should read the "Memory Leaks" section of the [PhET code-review checklist](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md).

If this is relevant for this sim, ask me or one of the other developers for more info.

**Comment by andrea-phet** [comment]
Disposes have been implemented and documentation has been made where dispose was not needed. @pixelzoom can you either review this, or close this issue if you would like to wait until code review to do it.

**Comment by pixelzoom** [comment]
Looks like you understand the `dispose` pattern.

One question:  In Trajectory.dispose, why did you choose to clean up `this.dataPoints` in `dispose` rather than in `this.disposeTrajectory`?  Typically all of the type-specific disposal would be encapsulated in `this.disposeTrajectory`.

**Comment by pixelzoom** [comment]
I see you commented out this line:

`83       // this.dataPoints.clear();`

So perhaps you were on the fence about where to handle this.

**Comment by andrea-phet** [comment]
Yes, I couldn't think of a specific reason to choose this.disposeTrajectory or Trajectory.dispose. But I'll go with what is more typical, then.

**Comment by pixelzoom** [comment]
@andrea-phet I made one change in Trajectory.dispose.  Unless there's a reason to reuse a loop variable (`i` in this case), the variable is typically defined in the `for` statement.   You had it defined outside the statement, and it looks like a common pattern that you're using.

E.g, you're doing:

``js
var i;
for ( i = 0; i < this.dataPoints.length; i++ ) {
  ... 
}
```

This is preferred:

``js
for (var  i = 0; i < this.dataPoints.length; i++ ) { 
   ... 
}
```

Looks like you're doing this throughout your code, recommends to change.

**Comment by pixelzoom** [comment]
To be clear... Here's an example where defining the loop variable outside the `for` statement is useful. 

```js
function someThing( array ) {

  var i;

  // do something in first pass
  for ( i = 0; i < array.length; i++ ) {
  }

  // do something in second pass that couldn't be done in first pass
  for ( i = 0; i < array.length; i++ ) {
  }
}
```

You could also get away with this in JavaScript:

```js
function someThing( array ) {

  // do something in first pass
  for ( var i = 0; i < array.length; i++ ) {
  }

  // do something in second pass that couldn't be done in first pass
  for ( i = 0; i < array.length; i++ ) {
  }
}
```

In other languages, the scope of `var i` would be limited to the `for` statement.  But JavaScript has very non-standard scoping rules. It "hoists" variables - it automatically moves their declarations to the top of the enclosing function.   So (after JavaScript gets done with them) the above 2 examples are equivalent.   The first example, where `var i` is at the top of the function, is (I think preferred).  In general, handle the hoisting yourself, don't leave it to Javascript.

**Comment by pixelzoom** [comment]
Also note that you can't do this:

```js
function someThing( array ) {

  // do something in first pass
  for ( var i = 0; i < array.length; i++ ) {
  }

  // do something in second pass that couldn't be done in first pass
  for ( var i = 0; i < array.length; i++ ) {
  }
}
```

Because there are two `var i` declarations in the function scope, JavaScript treats the second one as a duplicate.  In other languages this would be just fine, since the scope of the loop variable is limited to the `for` statement block.

**Comment by andrea-phet** [comment]
Okay, I made changes everywhere else as well. @pixelzoom could you review and close?

**Comment by pixelzoom** [comment]
Looks great.  You've moved loop variable declarations into for statements, and I also see some examples where you've made good use of explicit hoisting (e.g. `i` in `ProjectileMotionModel.updateTrajectoriesWithMovingProjectiles`).  

Closing.
