### ISSUE TITLE
move functions out of constructor when possible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#43]
Related to #22 (high-level review).

If you create a function inside of a constructor, every instance of that type will have a copy of that function.  

For example, inside `ZoomControl` constructor, `createZoomControlButton` is defined:

```js
    function createZoomControlButton( contentNode, marginOptions, listener ) {
      return new RectangularPushButton( {
        content: contentNode,
        cornerRadius: 2,
        xMargin: marginOptions.xMargin,
        yMargin: marginOptions.yMargin,
        baseColor: 'white',
        listener: listener
      } );
    }
```

Every instance of `ZoomControl` will create its own copy of this function. Not a big deal if there are only a few instances  of `ZoomControl`.  But if there are a lot of instances, it can eat up memory.

Since `createZoomControlButton` has no need to access properties of `ZoomControl`, it should be defined _outside_ of the constructor.  By doing so, there will be 1 instance of `createZoomControlButton`, used by all instances of `ZoomControl`.

**Comment by andrea-phet** [comment]
Where should createZoomControlButton be defined instead? Right before the constructor? In the inherit?

**Comment by pixelzoom** [comment]
I typically define private functions immediate after the namespace `register` call.  In this case, immediate after:

```js 
projectileMotion.register( 'ZoomControl', ZoomControl );
```

**Comment by pixelzoom** [comment]
More info...  We want the constructor to appear as early as possible in the file, so we don't put private functions before the constructor.  And we don't put private function in the `inherit` call, because that would make them part of the public interface.

**Comment by andrea-phet** [comment]
@pixelzoom Could you give me an example of putting a helper function outside both the constructor and the inherit block? Tagging @jbphet as well.

**Comment by pixelzoom** [comment]
The easiest way is to demonstrate, so I made `createZoomControlButton` a private function in `ZoomControl`.  See the first commit immediately above.  (The second commit is some cleanup to `createZoomControlButton`, let me know if you have questions about that.) 

The general idea here is that the function's scope is limited to the `define(...)` function that wraps the contents of the file.  So it's private because it's not visible outside of the file.   In contrast, anything attached to `this` in the constructor, or defined in the `inherit` call, is publicly visible.  

Make sense?

**Comment by pixelzoom** [comment]
Also note that `createZoomControlButton` could be defined using either of these syntaxes:

```js
// named function
function createZoomControlButton( options ) { ... }

// var
var createZoomControlButton = function( options ) { ... }
```

The main advantage of named functions is that their names will appear when you inspect them in the debugger, which can aid in debugging.  Functions defined using the `var` syntax are anonymous.

**Comment by andrea-phet** [comment]
@pixelzoom like the above commit?

**Comment by pixelzoom** [comment]
Yep, that's the idea.

**Comment by andrea-phet** [comment]
I couldn't find other instances to take out of the constructor besides the one above, so assigning back to @pixelzoom to review.

**Comment by pixelzoom** [comment]
I'll take your word for it :)   If there are any others, they'll likely be identified during final code review. If not, no big deal.  Closing.
