### ISSUE TITLE
Create screen icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#44]

**Comment by arouinfar** [comment]
Discussed screen icons with @ariel-phet today. Here's a draft based on the discussion. Can you take a look at these @ariel-phet?
![image](https://user-images.githubusercontent.com/8419308/27503427-303e5f26-5839-11e7-8fe9-ae37ca6a6b0e.png)

**Comment by ariel-phet** [comment]
@arouinfar I think those are all looking good. I might do the following to make the navbar icons a bit more "readable"

1. Intro - Increase the size of PhET girl as much as can be tolerated
2. Vectors, again just increase the size of the picture to fill a bit more of the negative space
3. Lab, I think I would take artistic license and remove the pedestal (or just have a smaller vertical slice of it) and increase the size of the cannon.

**Comment by arouinfar** [comment]
Thanks @ariel-phet! I've edited the navbar icons. If we want to keep PhET girl's trajectory, I'd recommend the 2nd option. I think the cannon needs some of the pedestal to avoid a floaty look, but I've also tried removing the longer crosshairs and angle arc from the cannon. 

![image](https://user-images.githubusercontent.com/8419308/27563909-8f0cf18e-5a91-11e7-8bea-21fecc03479d.png)

**Comment by ariel-phet** [comment]
I feel like the second navbar option you have shown works pretty well in each case (larger girl still having trajectory, larger vectors, and larger cannon but still with cross haris)

**Comment by arouinfar** [comment]
Thanks @ariel-phet! I also like the 2nd icons.  

@andrea-phet @jbphet are these icons something that would be done in code, or should I send asset files?

**Comment by jbphet** [comment]
It's more versatile and consistent to do them in code, using the artwork we already have for the cannon and for PhET girl.  I would recommend that.

**Comment by arouinfar** [comment]
Sounds good @jbphet! Here are some reference images for the screen icons.

[intro](https://user-images.githubusercontent.com/8419308/27600405-10d1ff38-5b29-11e7-8629-8637e924aa3a.png)
[intro_nav](https://user-images.githubusercontent.com/8419308/27600408-10d36328-5b29-11e7-8ff1-5cb430cf41af.png)
[drag](https://user-images.githubusercontent.com/8419308/27600404-10d19d90-5b29-11e7-89c6-bbd997520619.png)
[vectors](https://user-images.githubusercontent.com/8419308/27600410-10e5d83c-5b29-11e7-9894-7a0802f94c74.png)
[vectors_nav](https://user-images.githubusercontent.com/8419308/27600407-10d30a9a-5b29-11e7-99e3-471ab100eddc.png)
[lab](https://user-images.githubusercontent.com/8419308/27600406-10d222c4-5b29-11e7-9da4-ace470957f24.png)
[lab_nav](https://user-images.githubusercontent.com/8419308/27600409-10d641ba-5b29-11e7-85fa-ce9d360d5896.png)

**Comment by andrea-phet** [comment]
The icons have been drawn in code and added to the sim. Assigning back to @arouinfar to review and close.

**Comment by arouinfar** [comment]
Looks great @andrea-phet!!
