### ISSUE TITLE
Review benchmark properties/ranges

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#45]
Review Flash defaults for benchmark projectiles and recommend ranges for the lab screen.

**Comment by arouinfar** [comment]
Flash Benchmark Items

| Item | Mass (kg) | Diameter (m) | Drag Coefficient | 
| --- | --- | --- | --- |
| Tank shell | 150 | 0.15 | 0.05|
| Golf ball | 0.046 | 0.043 | 0.24 |
| Baseball | 0.145 | 0.074 | 0.4 |
| Bowling ball | 7.3 | 0.25 | 0.46 |
| Football | 0.41 | 0.17 | 0.15 |
| Pumpkin | 5 | 0.37 | 0.6 |
| Human | 70 | 0.5 | 1.3 |
| Piano | 400 | 2 | 1.2 |
| Buick | 1000 | 2.5 | 1.3 |


HTML5 Benchmark Items - Bold denotes change from Flash.

| Item | Mass (kg) | Diameter (m) | Cd | Reference |
| --- | --- | --- | --- | --- |
| Tank shell | **41.9** | **0.15** | **0.06** | http://www.dtic.mil/dtic/tr/fulltext/u2/209134.pdf https://en.wikipedia.org/wiki/M107_projectile|
| Golf ball | 0.046 | 0.043 | **0.25** | http://www.usga.org/rules/equipment-rules.html#!rule-14611 http://baseball.physics.illinois.edu/DragTPTMay2014.pdf  |
| Baseball | 0.145 | 0.074 | **0.35** | http://mlb.mlb.com/mlb/downloads/y2014/official_baseball_rules.pdf http://baseball.physics.illinois.edu/DragTPTMay2014.pdf |
| Football | 0.41 | 0.17 | **0.05** | http://static.nfl.com/static/content/public/image/rulebook/pdfs/5_2013_Ball.pdf http://aapt.scitation.org/doi/pdf/10.1119/1.1578065 |
| Pumpkin | 5 | 0.37 | 0.6 | Couldn't find a source for Cd. |
| Human | 70 | 0.5 | **0.6** | https://www.scientificamerican.com/article/the-aerodynamics-of-human-powered-l/ http://www.zzipper.com/documents/HPV_Paper.pdf |
| Piano | **480** | **2.2** | 1.2 | Couldn't find a source for Cd. http://www.steinwayshowrooms.com/instruments/steinway/grand |
| Buick | **2000** | **2** | **0.55** | http://www.automobile-catalog.com/car/1955/292745/buick_series_70_roadmaster_riviera_coupe_dynaflow.html |
| **Cannonball** | 5.44 | 0.11 | 0.47 | http://www.arc.id.au/Cannonballs.html |
| **Arrow** | ~0.05 | ~0.01 | 1.6-2.65 | Couldn't find a source for the weight/diameter. https://link.springer.com/article/10.1007%2Fs12283-012-0102-y |

During last week's design meeting we discussed the possibility of replacing the tank shell with something less war-like, such as an arrow. The nice thing about the tank shell is that it is not deflected when air resistance is turned on (low drag coefficient and sufficiently large mass). It's the only benchmark projectile with a path that is not perceivably affected by air resistance (with otherwise default settings). For example, compare the football and the tank shell (same Cd):
<img src="https://user-images.githubusercontent.com/8419308/27398839-4358bb8c-5678-11e7-9824-7b9882b02003.png" width=400>

An arrow, on the other hand, has a large drag coefficient (1.6-2.65) so its path will be very obviously different when air resistance is turned on. What's interesting about the arrow is that due to its low weight and diameter, it goes about as far as football at Cd=2.6 (and further if Cd=1.6), despite the football having a much lower Cd. 
<img src="https://user-images.githubusercontent.com/8419308/27399925-aabdd822-567b-11e7-8eee-c0ab51a0dc42.png" width=400>

Final thoughts/questions for design meeting:
* The tank shell is a pedagogically useful example, so I think we should consider keeping it.
* The arrow is an interesting example, but should not replace the tank shell.
* Do we need to be so precise with the golfball and baseball?

**Comment by arouinfar** [comment]
I was able to find a few sources for an arrow's weight and diameter, which I've added to the table in https://github.com/phetsims/projectile-motion/issues/45#issuecomment-310167847.  Looks like the arrow would be similar to the football or golfball, depending on the drag coefficient.

<img src="https://user-images.githubusercontent.com/8419308/27562547-37d14bb0-5a8a-11e7-959c-53c0b81617fe.png" width=400>

**Comment by andrea-phet** [comment]
Could we make the cannonball bigger? Just because it is the default on each screen, and it would be nice to see the projectile at the end of the path.

Current (5.4 kg in mass, 0.11 m in diameter):
![image](https://user-images.githubusercontent.com/7988696/27660286-e6625810-5c13-11e7-8c8f-762367adb0a3.png)

I suggest something around 16.2 kg in mass, 0.33 m in diameter:
![image](https://user-images.githubusercontent.com/7988696/27660303-f3517484-5c13-11e7-8dd0-b757a2449cb0.png)

**Comment by arouinfar** [comment]
Great suggestion @andrea-phet. A diameter of 0.33 m is a bit unrealistic for a cannonball, but it otherwise blends in with the timing dots. I agree that it would be nice to have a more visible default projectile, so we should talk about this issue more when discussing the benchmarks in design meeting.

**Comment by andrea-phet** [comment]
We could also start with a slightly bigger default zoom, which would increase the size of the projectile but not the timing dots. We could also make the path and timing dots just a bit smaller. These in combination with perhaps a diameter of 0.22 or something might work.

**Comment by andrea-phet** [comment]
With 1.2x bigger zoom, no change to path and timing dots, and a cannonball with 10.88 kg and 0.22 m, it looks like this:

![image](https://user-images.githubusercontent.com/7988696/27697275-fb488518-5cb0-11e7-9265-d41e133189cd.png)


What do you think?

**Comment by arouinfar** [comment]
Notes from today's discussion
* Keeping the tank shell because it is a pedagogically useful example.
* Add the arrow.
* PhET girl's defaults can be adult values.
* Smaller items (football and smaller) will have two decimal places in the mass and diameter. 
* Larger items (pumpkin and larger) will not have any decimal places in the mass, and will have one decimal place in the diameter.


@andrea-phet I've updated the benchmark properties spreadsheet. You can find the values in the HTML5 tab.
https://docs.google.com/spreadsheets/d/1SP9ccBbFgyLM7hbKIqyrb_2e0flVFHYCvmxgbSrHZII/edit#gid=1094924042

![image](https://user-images.githubusercontent.com/8419308/27715176-96262f5e-5cf2-11e7-9c50-01c3ee9915b0.png)

**Comment by arouinfar** [comment]
Just realized the grouping into "small" and "large" items isn't as clean-cut as I had thought. For example, the tank shell is heavy, but small.

Mass with 2 decimals: arrow, golf ball, baseball, football, cannonball
Mass with 0 decimals: pumpkin, tank shell, human, piano, Buick

Diameter with 2 decimals: arrow, golf ball, baseball, football, cannonball, pumpkin, tank shell
Diameter with 0 decimals: human, piano, Buick

**Comment by andrea-phet** [comment]
For the human, piano, and Buick, their diameter can go as low as 0.5, but 0 decimals can be shown. How does one show the minimum?

**Comment by andrea-phet** [comment]
Assigning to @arouinfar to review.

**Comment by arouinfar** [comment]
Looks pretty good @andrea-phet. 

Here are a few observations:
* Cannonball: I'd really like to use a realistic diameter as the default, but I think we could Hollywood the scaling a bit. Can you leave the size as-is, but change the diameter and mass values back to the defaults in the spreadsheet (5.44 kg, 0.11 m)?
* Baseball: The baseball looks quite a bit smaller than the cannonball at a diameter of 1 m. Since they are both spheres, I think they should match. I suspect the original baseball artwork wasn't large enough, so I'll  export a higher quality asset.
* Golfball: At the max diameter, the golfball is very obviously a white circle. I wonder if I should make a more realistic looking asset.
* Tank shell: I'll create artwork to make the shell look a bit more realistic at large sizes.

@andrea-phet here are some things you can update white I work on the artwork
- [ ] Re-order the items in the combo box to match the order in the spreadsheet.
- [ ] Drag coefficient: display two decimal places for all items
- [ ] Cannonball: Hollywood the scaling a bit. Change mass and diameter values to match spreadsheet, but leave default size as-is.
- [ ] Piano: Drag coefficient should be 1.2 to match Flash (unless you have a source for 0.9).
- [ ] Golfball: Minimum diameter should be 0.01 m
- [ ] Custom: Match defaults and allowable range to the spreadsheet

**Comment by arouinfar** [comment]
Relevant artwork tweaks tracked in #61, so unassigning myself.

**Comment by andrea-phet** [comment]
Assigning to @arouinfar to review.

**Comment by arouinfar** [comment]
Looks great! Thanks @andrea-phet.
