### ISSUE TITLE
Fire button image

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/projectile-motion#46]
I see the fire button image in the mockups, is that and its .ai file somewhere I could access?

**Comment by arouinfar** [comment]
@andrea-phet the fire button is a wireframe. I've been working on alternative designs that we can discuss in design meeting today.

![image](https://user-images.githubusercontent.com/8419308/27443999-1abc9846-5732-11e7-88df-1e762edb52b3.png)

**Comment by ariel-phet** [comment]
I like option 1 or 3 currently (3 definitely conveys some motion)

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet! We've been using option 3 in the mockups. I think it does a good job of conveying motion, but I worry that it looks a bit off, so I've tried to come up with some alternatives.

I'd like to use a cannon (or at least part of it) in the button because I think it will make the button's purpose really clear. Originally, I tried a grayscale cannon in the button, but I thought that was way too busy -- which is why there are a few options with a grayscale barrel.

I played with the button a bit more, and I think a silhouette of the cannon may work nicely.
![image](https://user-images.githubusercontent.com/8419308/27562376-8a0a7f10-5a89-11e7-9f41-f878d6028a7e.png)

When you get the chance, can you take a look @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar that also works for me...I might make the "boom" a bit more symmetric about the barrel, but otherwise that seems like a good option

**Comment by arouinfar** [comment]
Will do @ariel-phet. Thanks!

**Comment by arouinfar** [comment]
I tweaked the boom a bit, and have sent the asset off to @andrea-phet.

![image](https://user-images.githubusercontent.com/8419308/27600822-63e67144-5b2a-11e7-9829-674e4959580f.png)

**Comment by arouinfar** [comment]
We discussed the fire button artwork in design meeting today, and decided to go with a black-and-white version of the cannon instead. Reviewed this artwork with @ariel-phet and will email the updated asset to @andrea-phet.

![image](https://user-images.githubusercontent.com/8419308/27712416-26dbc4a0-5ce4-11e7-9a10-821bfbee409d.png)

**Comment by andrea-phet** [comment]
The updated artwork is in.

**Comment by arouinfar** [comment]
Thanks @andrea-phet. I think this is an improvement over the silhouette, but I wonder if we should add a gray stroke around the black part of the cannon barrel too. @ariel-phet can you take a look?
![image](https://user-images.githubusercontent.com/8419308/27805145-0e28dcb8-5ff0-11e7-8a9d-ca1e31af2281.png)

**Comment by ariel-phet** [comment]
@arouinfar a few tweaks I would try:

1. Make the cannon in the button as large as possible (I think the boom could be "squashed a little" if necessary. I think on an iPad it will be a little tough to make out. I think this tweak should definitely be done

2. I agree that an outline on the barrel might help things stand out well

3. Perhaps add a slighlty smaller grey or white matching "boom" to give a bit of a "shockwave" effect. I think if you drew a white line right near the boom black line it would help it pop a bit more. But perhaps not necessary

4. The cannon angle could be slightly shallower to allow more space for a larger cannon and boom.

**Comment by arouinfar** [comment]
@ariel-phet thanks for your suggestions. I've mocked up two alternatives that include a larger cannon, outlined barrel, and double stroked boom.

Comparison to the original:
![image](https://user-images.githubusercontent.com/8419308/28041205-beffa4c8-6585-11e7-9f0b-cd058e62ca23.png)

At iPad resolution:
![screen shot 2017-07-10 at 3 37 11 pm](https://user-images.githubusercontent.com/8419308/28041187-abcc863c-6585-11e7-9a37-e5fe36a14e7b.png)

I like the bottom option, but I think that there's still room for improvement.

**Comment by ariel-phet** [comment]
I like the bottom option as well. Lets go with that

**Comment by arouinfar** [comment]
Ok, sounds good @ariel-phet! I'll send an updated asset to @andrea-phet.

**Comment by arouinfar** [comment]
Updated assets have been delivered to @andrea-phet.

**Comment by andrea-phet** [comment]
The updated image has been incorporated.

**Comment by arouinfar** [comment]
I like it @andrea-phet. 

@ariel-phet would you also like to review it?
![image](https://user-images.githubusercontent.com/8419308/28288894-f03b5ed8-6afd-11e7-9ef4-913451242f6c.png)

**Comment by ariel-phet** [comment]
Looks great, closing
