### ISSUE TITLE
Items for teacher tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#47]
We should start considering items for teacher tips, assigning myself and @arouinfar to start filling in possibilities

**Comment by arouinfar** [comment]
From Legacy Tips
- [ ] The cannon has crosshairs to mark the initial location of the projectile.
- [ ] We used quadratic drag (Fdrag ~ v^2) which is valid in the high Reynold’s number limit appropriate for macroscopic objects like baseballs. Linear drag (Stoke's Law) is only valid in the very low Reynold's number limit (like micron-sized droplets in air).

Other things we'll need to document
- [ ] The drag coefficient depends on the Reynolds number, which we have assumed to be a constant.

**Comment by arouinfar** [comment]
I'll add to the list in the comment above as I think of things.

**Comment by arouinfar** [comment]
The items in https://github.com/phetsims/projectile-motion/issues/47#issuecomment-311190480 have all been documented in the Tips, so closing.
