### ISSUE TITLE
Timeline for trying to get sim published

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#48]
### Idealized timeline as of June 24 2017

| Week | Goals|
| ------------- | ------------- |
| `June 26- 30` | Performance optimization & working towards feature complete |
| `July 3-7 ` | initial dev testing and bug fixes  |
| `July 10-14`  | interviews & pixel polishing  |
| `July 17-21`  | AL goes over code review checklist & addresses issues|
| `July 22-Aug 2`  | AL unavailable, formal code review  |
| `Aug 3-11`  |  address code review issues |
| `Aug 14-18`  |  Get sim into RC phase |

**Comment by ariel-phet** [comment]
@andrea-phet above is our idealized timeline. It seems a good goal would be to have the sim optimized, interviewed, dev tested, major bugs addressed, and ready for formal code review before you go on your trip on July 22nd. If that is the case, I think we will have a very good shot of publishing before you go back to school. 

Obviously, some of this timeline will depend on how much work optimization takes, as well as how many issues are found during dev testing. However, the sim appears to be in good shape, so although this timeline is "aggressive" I do not currently feel it is unreasonable. Let's make notes in this issue so we can keep on track after each week.

**Comment by ariel-phet** [comment]
Tagging @arouinfar so that she is aware that we should look to schedule interviews soon (the sim is getting close to interviews on desktop, so I think the week of July 10th is reasonable to expect interviews, so long as iPad optimization goes smoothly)

Tagging @phet-steele so he is aware that we will want some initial dev testing the week of July 3rd

**Comment by arouinfar** [comment]
Sounds good @ariel-phet. Any thoughts about the interview recruitment pool? Looks like the last time we recruited students from gen chem or physics was spring 2016, so I'll need to reach out to some professors this week.

**Comment by arouinfar** [comment]
I was thinking gen chem may be a good class to recruit from. It looks like PHYS 2010 students will have seen Projectile Motion, Masses & Springs, and Pendulum Lab, according to the [course schedule](http://www.colorado.edu/physics/phys2010/phys2010_sm17/schedule.pdf). We will also need to interview students on CCK and (possibly) Coulomb's Law soon, so recruiting students from the PHYS courses may not be a great idea.

**Comment by arouinfar** [comment]
I've contacted the CHEM 1113 professor to recruit students from her class.

**Comment by pixelzoom** [comment]
Looks like milestones were met, and the sim was in RC on 8/15/17. 

@arouinfar @andrea-phet Any reason not to close this issue?

**Comment by arouinfar** [comment]
Let's go ahead and close it. Nice work @andrea-phet!
