### ISSUE TITLE
why is projectile-motion in active-repos?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#5]
This sim is in chipper/data/active-repos, but not in active-sims. As of 03799e85e83e528e1f2f7ae66e7d2e900fb48ce1, it will not run in development mode and will not build.

Here's the console output in development mode:

![screenshot_521](https://cloud.githubusercontent.com/assets/3046552/7663001/f94123f4-fb20-11e4-8dc8-84fc4b4132b4.png)

Here's the output of `grunt`:

```
...
Running "requirejs:build" (requirejs) task
>> Error: Error: /Users/cmalley/PhET/GitHub/projectile-motion/js/projectile-motion-config.js does not exist.
>>     at /Users/cmalley/PhET/GitHub/projectile-motion/node_modules/requirejs/bin/r.js:27604:27
Warning: Task "requirejs:build" failed. Use --force to continue.
```

**Comment by samreid** [comment]
This repo was created by @jbphet in early 2015.  I'll assign it to @jbphet to find out what is happening here.

**Comment by jbphet** [comment]
This sim now has the basic infrastructure set up, builds, and is listed in active sims.  Closing.
