### ISSUE TITLE
Add transparent rectangle behind angle and height readouts

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#50]
@andrea-phet I've noticed that the cannon height and angle are a bit hard to read when lowered into the ground.
<img width="200" alt="screen shot 2017-06-27 at 2 40 35 pm" src="https://user-images.githubusercontent.com/8419308/27609021-b71b8c0c-5b46-11e7-8577-bb18c272cc78.png">

Adding a transparent white rectangle behind the readouts will improve the contrast quite a bit. 
![screen shot 2017-06-27 at 3 37 02 pm](https://user-images.githubusercontent.com/8419308/27611201-7ead6a0e-5b4e-11e7-86f7-c9321a8829f9.png)

**Comment by andrea-phet** [comment]
Thanks for pointing that out. I've added those in, assigning back to you to take a look.

**Comment by arouinfar** [comment]
👍
