### ISSUE TITLE
Layer projectile + path above cannon

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#51]
In Flash, the projectile and its path are both layered above the cannon.
![image](https://user-images.githubusercontent.com/8419308/27613017-89229f56-5b56-11e7-9c04-81a6e004a9d8.png)

This makes the starting position of the projectile clearer, and is critical for seeing the path of slow projectiles, which can easily get obscured by the cannon.

@andrea-phet please adjust the layering so that the projectile+path are above the cannon and pedestal.

**Comment by arouinfar** [comment]
Before addressing #52, I'd like to see how things look after the layering is corrected.

**Comment by andrea-phet** [comment]
The layering has been corrected, would you like to take a look?

**Comment by arouinfar** [comment]
Thanks @andrea-phet! I'll take a look on master.

**Comment by arouinfar** [comment]
Looks great! Closing.
