### ISSUE TITLE
Change cannon and pedestal colors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#52]
Once the layering of the projectile and path are adjusted for #51, the red/blue paths will contrast poorly with the cannon and pedestal. Self-assigning to find more suitable colors.

**Comment by andrea-phet** [comment]
Perhaps it would be easier to change path colors rather than changing the cannon and pedestal colors? Just because the cannon artwork looks so nice as it is.

**Comment by arouinfar** [comment]
@andrea-phet I'm also a fan of the cannon/pedestal colors. However, we usually use red to represent friction/heat, so I think it would make sense to keep the trajectories with air resistance red. Unfortunately, a red trajectory won't look so great on top of the red cannon. 

I will try playing with the trajectory colors, but ultimately I think I may have to adjust the artwork.

**Comment by arouinfar** [comment]
Not really a fan of any of these options... but here are a few color combinations I've tried.
![image](https://user-images.githubusercontent.com/8419308/27653422-39bb7996-5bfc-11e7-8f3f-e150a73b4cf4.png)

**Comment by andrea-phet** [comment]
The second cannon and the fourth pedestal are my favorites, not sure if they would go well together.

**Comment by arouinfar** [comment]
Welcome to my struggle @andrea-phet! :)

Now that I see the paths layered on top, it may not be as bad as I think. Let's discuss at design meeting.
![image](https://user-images.githubusercontent.com/8419308/27655599-29ca7878-5c03-11e7-9e9c-012908960f90.png)

**Comment by andrea-phet** [comment]
Yeah, the black dots help.

**Comment by arouinfar** [comment]
During design meeting, we experimented with a magenta cannon and gray pedestal. @ariel-phet suggested keeping the cannon red, and instead using a magenta trajectory. I think the magenta trajectory looks quite nice, so let's try that instead @andrea-phet. 

![image](https://user-images.githubusercontent.com/8419308/27715375-e59ad6ce-5cf3-11e7-8c1c-93407b20aea0.png)

**Comment by andrea-phet** [comment]
Here we go:
![image](https://user-images.githubusercontent.com/7988696/27804940-e331dc4a-5fee-11e7-8c79-ce273caba1a2.png)

**Comment by arouinfar** [comment]
Thanks @andrea-phet! Looks good. We'll need to update the screen/navbar icons for the Lab screen to include the gray panel.

**Comment by andrea-phet** [comment]
Updated the screen/navbar icons.

**Comment by arouinfar** [comment]
👍
