### ISSUE TITLE
DataPoint should contain Vector2 instead of inherit from it

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#55]
I noticed that DataPoint inherits from Vector2.  This means that DataPoint inherits many methods from the Vector2 API like `copy`, `blend`, etc which are incorrect or misleading.  It would be better to store the x, y attributes of Data Point as independent {number} values or possibly as a {Vector2}.

**Comment by samreid** [comment]
@andrea-phet as I mentioned in https://github.com/phetsims/projectile-motion/issues/15

> the convention for PhET GitHub issues is that after the developer addresses the issue, the issue should be reassigned back to the original reporter (with a ready-for-review label) so the original reporter can double check everything or see if any related issues come to mind. This process works nicely for design team issues as well as code review issues.

I noticed you have been closing issues from commit messages like "fixes #55".  For issues opened by another team member it is better to use a commit message like "see #55" then comment in the issue and reassign.

**Comment by andrea-phet** [comment]
Will do. Assigning back to @samreid to review.

**Comment by samreid** [comment]
Looks great @andrea-phet, thanks!  Closing.
