### ISSUE TITLE
Height label out of dev

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#59]
@andrea-phet I noticed that the height label is out of bounds, but if you move the height marker to the right a few pixels, it should be fine.
![image](https://user-images.githubusercontent.com/8419308/27698459-6ab51634-5cb4-11e7-898e-64cdd24856e6.png)

**Comment by andrea-phet** [comment]
Thanks for pointing that out. It was a small fix, so I'll go ahead and close this issue.
