### ISSUE TITLE
User suggestion: add a tool to record range, height, and time

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#6]
Awesome website.  I got my PhD from JILA, btw.  Long time ago.  I made a small contribution to your efforts.
I am trying to get Altitude and Range vs. Time from your simulator.  It is not obvious how to pull that out of the tool, and maybe isn’t available.

**Comment by amanda-phet** [comment]
This is definitely part of the redesign! 

Right now, the only way to determine this information at a given point is to pause the projectile at that point. We are planning to make a tool that allows you to view this at any point even after the projectile has landed.

**Comment by ariel-phet** [comment]
This tool now exists, closing
