### ISSUE TITLE
use named placeholders in strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#60]
Since this sim hasn't been published yet, it should be converted from "numbered" to "named" placeholders.

These strings use numbered placeholders:

```js
  "pattern0Value1Units": {
     "value": "{0}{1}"
  },
  "pattern0Value1UnitsWithSpace": {
    "value": "{0} {1}"
  },
```

This is what is looks like with named placeholders, note the double curly braces:

```js
  "pattern0Value1Units": {
     "value": "{{value}}{{units]}"
  },
  "pattern0Value1UnitsWithSpace": {
    "value": "{{value}} {{units}}"
  },
```

Then replace `StringUtils.format` with `StringUtils.fillIn` (see examples in JSdoc).  

Ask me if you have questions.

**Comment by pixelzoom** [comment]
Ah... You're using NumberControl.  You might be stuck with numbered placeholders.   Follow the discussion in https://github.com/phetsims/circuit-construction-kit-common/issues/380#issuecomment-312019135, where we're considering changing NumberControl.

**Comment by andrea-phet** [comment]
It seems like that issue was closed, but I am still confused. Are we using named or numbered placeholders for NumberControl?

**Comment by pixelzoom** [comment]
The issues specific to CCK was closed.  A more general issue was opened, see https://github.com/phetsims/scenery-phet/issues/317.  I'll label it for discussion at developer meeting.

**Comment by andrea-phet** [comment]
The strings and fill in code have been updated. Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
👍  Closing.
