### ISSUE TITLE
Artwork pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#61]
During yesterday's design meeting we discussed making a few tweaks to the artwork
- [x] Move wheel in crashed Buick closer to its body
- [x] Lighten the green in the Flatirons to improve contrast of projectile path
- [x] Increase height of cannon leg (do not otherwise change pivot) to increase the grab area when h=0.

**Comment by arouinfar** [comment]
After reviewing #45, a few more items to tweak
- [ ] Re-export baseball (looks small and pixelated at max diameter)
- [ ] Create a tank shell with a simple gradient

**Comment by arouinfar** [comment]
@andrea-phet I've sent you the updated artwork for most of the items listed above. I'm deferring the golfball until after design meeting discussion.

**Comment by arouinfar** [comment]
Vetoed the golfball in today's design meeting.

**Comment by andrea-phet** [comment]
Incorporated the new artwork, and at design we decided golfball as is is fine.

**Comment by arouinfar** [comment]
@andrea-phet looks pretty good, with the exception of the cannon base. The area above the horizontal line looks shifted a bit to the right.
![image](https://user-images.githubusercontent.com/8419308/27972969-7183b512-6315-11e7-8a3f-ff7a6a5455b6.png)

The latest asset looks okay, so I'm not sure what's causing the issue.
![cannon_base](https://user-images.githubusercontent.com/8419308/27973104-0e03e10a-6316-11e7-9e33-921f279bdad3.png)

**Comment by andrea-phet** [comment]
I was dividing the part above the pivot and the part below the pivot a pixel off. Should be fixed now.

**Comment by arouinfar** [comment]
All fixed!
