### ISSUE TITLE
Add gravity slider to Lab screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#62]
As discussed in yesterday's design meeting, we'd like to keep the gravity slider. Here are the specs @andrea-phet:

* Lab screen only
* Between Diameter and Air Resistance
* Horizontal separating line above and below the gravity slider
* Smooth track, no end labels
* Range 5-20 m/s^2
* Default 9.81 m/s^2
* Tweaker step of 0.01 m/s^2
* No label for Earth/9.81 or snapping behavior necessary

**Comment by andrea-phet** [comment]
Assigning to @arouinfar to review.

**Comment by arouinfar** [comment]
Looks great @andrea-phet!! I think we'll need to tighten up some space in the panels to avoid overlapping the road, but I will open up a separate issue for that.

The smaller tweakers look good too!
