### ISSUE TITLE
Cannon height hard to control when zoomed out

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#63]
During yesterday's design meeting, we discussed some changes that could be made to the cannon to improve the height adjustment, particularly when in the ground. Namely, increasing the height of the cannon's leg and making the height label draggable (artwork tracked in #61).

These changes will improve the the height control at the standard zoom level, but when zoomed out, the height may still be difficult to control. Some options to consider:
* Allow the pedestal to be dragged up and down to change the height
* Include the base of the cannon barrel (roughly lowest 1/3) to the area used to control height, rather than angle

If we make these changes, the tweaks to the cannon artwork may not be necessary.

**Comment by andrea-phet** [comment]
The entire pedestal and the part of the cannon barrel that is before the pivot can be dragged to control height. Assigning to @arouinfar to review.

**Comment by arouinfar** [comment]
This is a huge improvement @andrea-phet! The cannon still seems a little hard to pull out of the ground when zoomed all the way out, but I'm not sure that the artwork changes proposed in #61 will make much of a difference there. 

@phet-steele when the dev test rolls around, can you review this and let @andrea-phet if you have any further suggestions.

**Comment by arouinfar** [comment]
@andrea-phet can you also make the height label draggable?

**Comment by andrea-phet** [comment]
Yup. Assigning back to @arouinfar to review.

**Comment by arouinfar** [comment]
👍

**Comment by phet-steele** [comment]
@andrea-phet my last suggestion is to enable touch-to-snag on the cannon and height display. (Probably also need it on every slider, including the target, and both tools)

**Comment by andrea-phet** [comment]
@phet-steele and I looked at it, and the touch to snag looks good.
