### ISSUE TITLE
Review slider properties

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#64]
Self-assigning to review slider ranges, decimals, and defaults.

**Comment by arouinfar** [comment]
**Global**
- [ ] Reduce slider thumb to roughly the height of the tweakers (will help #66)
- [ ] Initial speed: change max to 30 m/s (helps to increase size of max drag force)

**Drag**
- [ ] Diameter: one decimal, snap to tick marks (steps of 0.1), no tweakers, default 0.8 m
- [ ] Mass: range 1-10, no decimals, snap to tick marks (steps of 1), no tweakers, default 5 kg
- [ ] Altitude: match Lab screen

**Vectors**
- [ ] Diameter: same as Drag screen
- [ ] Mass: same as Drag screen


**Lab**
- [ ] Mass: add min/max labels (Benchmarks vary a lot, so adding labels to the ends may make the range more obvious to the user. Reducing thumb size will help buy back some of the needed vertical space.)
- [ ] Diameter: add min/max labels
- [ ] Altitude: remove tick marks from ends of track
- [ ] Implement desired number of decimals as described in https://github.com/phetsims/projectile-motion/issues/45#issuecomment-312381655

**Comment by andrea-phet** [comment]
I checked off things above to help me keep track of my progress, but feel free to uncheck if needed. Assigning to @arouinfar to review.

**Comment by arouinfar** [comment]
Looks great @andrea-phet!! Now that I see the smaller thumb, I think it should be slightly larger. Can you increase the size by 10%?

**Comment by arouinfar** [comment]
If 10% ends up being a huge jump, a 5% increase may work instead.

**Comment by andrea-phet** [comment]
Done.
