### ISSUE TITLE
Scaling of force vectors

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#65]
As we discussed in design meeting, it would be ideal to adjust the scaling of force vectors such that the drag force is visible for a decent amount of the range.

One thing we can definitely do is decrease the mass range of the cannonball to help with the scaling issue. I think we could make the mass range go from 1 to 10 kg and that would buy us a bit more room if we set the default mass at 5 kg. With 1 to 10 we can still easily double and half the mass and such.

**Comment by arouinfar** [comment]
Agreed @ariel-phet. If the max mass is reduced to 10 kg, the force vectors can be scaled up a bit. I've also recommended defaults in https://github.com/phetsims/projectile-motion/issues/64 to make sure the vectors are all visible at the default settings.

**Comment by arouinfar** [comment]
@andrea-phet after you address the ranges in #64, can you increase the size of the force vectors?

**Comment by andrea-phet** [comment]
Increased, assigning to @arouinfar to check.

**Comment by arouinfar** [comment]
@andrea-phet the scaling looks really nice. At the default settings, the vector sizes look good. Adjusting one parameter (mass, diameter, velocity, or drag force) while holding the other parameters at the default value also shows a nice range of vector sizes, so I don't have any further recommendations.
