### ISSUE TITLE
Tighten up panels on lab screen to avoid overlapping road

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#66]
After adding the gravity slider to the lab screen (#62), the panel overlaps the road a little bit. With a little pixel polishing, I think the issue can be fixed. Self-assigning to further review and make recommendations.

**Comment by arouinfar** [comment]
By reducing the amount of negative space in the Initial Values panel and reducing the height of the combo box, the panel no longer overlaps the road.
<img width="542" alt="screen shot 2017-07-06 at 12 12 31 am" src="https://user-images.githubusercontent.com/8419308/27897867-07f26642-61e0-11e7-86a7-e08e43b6423c.png">

@andrea-phet here's what I did to free up the space.
- [ ] Move "Initial Values" up 5 px
- [ ] Move "Height" up 10 px
- [ ] Move "Angle" up 15 px
- [ ] Move "Initial Speed" up 20 px
- [ ] Decrease height of combo box by 10 px, and shift all other contents up by 10 px.

**Comment by andrea-phet** [comment]
I think that worked.

![image](https://user-images.githubusercontent.com/7988696/27920621-77205716-6232-11e7-9294-a399b0dd32e6.png)

**Comment by arouinfar** [comment]
Looks awesome!
