### ISSUE TITLE
Add arrow to Intro and Lab screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#67]
The arrow and its specs are discussed more in https://github.com/phetsims/projectile-motion/issues/45. Self-assigning to send arrow artwork to @andrea-phet.

**Comment by arouinfar** [comment]
Assets sent to @andrea-phet!

**Comment by andrea-phet** [comment]
The arrow has been added to Intro and Lab.

**Comment by arouinfar** [comment]
On the Lab screen, I've noticed that an arrow with a diameter of 0.1 m looks exactly the same as one with a diameter of 0.2 m. Is this a limitation of the image size @andrea-phet? Should I export a larger image for you?

**Comment by arouinfar** [comment]
Actually, I've noticed some other scaling issues, so I'll be creating a new issue. Closing.
