### ISSUE TITLE
Why are trajectory dots every  0.048s instead of a round number like 0.05 s?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#68]
@arouinfar @andrea-phet is there a reason we couldn't make the trajectory dots occur every 0.05 s? Is it related to the dt of the sim or such? It just seems a round number would be easier for many classroom uses.

**Comment by arouinfar** [comment]
@ariel-phet I wasn't aware that the dots were being drawn every 0.048 s. I had measured 0.05 s when using the path tracing tool, but it doesn't have enough decimal places to show a difference of 0.048 s. I think 0.05 s is nicer number to work with, and given the precision of the path tracing tool, I think it's a better choice of time step. 

@andrea-phet are there limitations in the model that would prevent us from using 0.05 s steps instead?

**Comment by ariel-phet** [comment]
@arouinfar I wasn't either, but I saw it in the teacher tips issue https://github.com/phetsims/projectile-motion/issues/47

**Comment by andrea-phet** [comment]
I changed it to be 0.05s and updated the teacher tips accordingly. If you're curious, the only reason for 0.048 is because that is 0.048 s is three times the 16 millisecond time step, which corresponds to the normal 60 frames per second.

**Comment by arouinfar** [comment]
Reviewed in design meeting, and everything looked good!
