### ISSUE TITLE
Panel pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#69]
To make the panels looks a bit more consistent across screens, I have a few suggested changes:

**Intro**
- [x] Remove gray box around non-editable values and format like "variableName: value" (like Initial Values on Lab)
- [x] Add horizontal line between Air Resistance and Diameter

**Vectors**
- [x] Remove gray box around drag coefficient and format like "Drag Coefficient: 0.47"
- [x] Add horizontal line between Air Resistance and Mass

**Comment by andrea-phet** [comment]
Assigning to @arouinfar to review.

**Comment by arouinfar** [comment]
Looks good @andrea-phet! One more request -- on the Intro and Vectors screens, can you gray out the Drag Coefficient when Air Resistance is off, like it is in the Lab screen?

**Comment by andrea-phet** [comment]
Yes, done.

**Comment by arouinfar** [comment]
👍
