### ISSUE TITLE
How is drag implemented?

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#7]
I received a question from a Physics teacher asking about how the drag is implemented (for the flash version):

> I'm going to do an activity with my AP Physics class using the Projectile Motion Simulator. I want them to see the effect that air resistance has on a projectile. My idea was to set a projectile at 45 degrees with a speed of 18 m/s or so, and then vary the drag coefficient to see the effect on range. 
> 
> In AP, they like the students to have experience linearizing data, so I was going to have them graph the original data of Range vs drag coefficient. This shows some sort of inverse relationship. When they manipulate the x data to graph Range vs 1/drag, you then get a graph that shows a root relationship. The problem is, I can never linearize it from there. I would think it should be a 1/squareroot(drag) relationship, but that doesn't do it. Any ideas for me? I'm guessing the simulation is written with some parameters that are affecting my results.

I'm having trouble reading the FLA file for the original flash code.  @ariel-phet @phetsims/dubson  @pixelzoom @jonathanolson @jbphet can you help out here?

**Comment by pixelzoom** [comment]
Sorry, can't help you. This is one of those Flash sims where the ActionScript isn't factored out into .as files.  So you'll need to poke around in the Flash IDE to find where the relevant code is attached. Probably best to ask @dubson.

**Comment by jonathanolson** [comment]
B: combination of drag parameters, seems to be (0.5 * dragC * area * rho / mass)
this.v: speed
dt: how much time has elapsed
this.vX: horizontal component of velocity
this.vY: vertical component of velocity
this.x: horizontal position
this.y: vertical position

```as3
//if airResistance so large that results are unphysical, then reduce time step
if(B*this.v*dt > 0.25){
  dt = dt/(B*this.v*dt/0.25);
}
this.t += dt;
this.v = Math.sqrt(this.vX*this.vX + this.vY*this.vY);
this.aX = -B*this.v*this.vX;
this.aY = -g - B*this.v*this.vY;
this.x = this.x + this.vX*dt + (0.5)*this.aX*dt*dt;
this.y = this.y + this.vY*dt + (0.5)*this.aY*dt*dt;
this.vX = this.vX + this.aX*dt;
this.vY = this.vY + this.aY*dt;
```

I didn't see anything immediately wrong, seems like constant acceleration per timestep proportional to v^2.

**Comment by ariel-phet** [comment]
The drag model is correct for the HTML5 version, closing

**Comment by samreid** [comment]
In Sept 2015, the teacher replied:

Thank you for your help. I can see the website; based on what I see there, I think that what I’m trying to do I probably impossible. Because of the way drag depends on both the horizontal and vertical speed, the range-drag relationship is not an easy one to describe. I think I would be best to vary the horizontal speed with constant drag and analyze that relationship instead.
