### ISSUE TITLE
Add vector/path icons next to checkboxes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#71]
Self-assigning to mock up.

**Comment by arouinfar** [comment]
Here's a mockup of the Intro screen, and discrepancies between the appearance of the icons and the vectors in the latest dev are unintentional. 
![image](https://user-images.githubusercontent.com/8419308/28041028-13efe2b4-6585-11e7-9a9d-2c7f61bdd0c9.png)



The Drag and Vector screens are less straightforward, because of the radio options for total and components. We could change the icons when flipping between total and components, but I don't know if the icons are actually needed on these screens.

<img src="https://user-images.githubusercontent.com/8419308/28040881-89526870-6584-11e7-92ab-d03d3859493b.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/28040937-c40582cc-6584-11e7-9809-0c1d90bc5a22.png" width=300>

Thoughts @ariel-phet? Should we have vector icons on the Intro screen only, or should they appear on all relevant screens?

**Comment by arouinfar** [comment]
Here's a few options for the Air Resistance icon.

<img src="https://user-images.githubusercontent.com/8419308/28042708-aed5c39c-658b-11e7-8abe-a67fc1834478.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/28042739-d26e99f0-658b-11e7-9120-c46f7bd11545.png" width=300>

<img src="https://user-images.githubusercontent.com/8419308/28042767-ef8cb81e-658b-11e7-83c5-b3138dc79808.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/28042729-c1f0b0ae-658b-11e7-89ef-ca79653a9655.png" width=300>

<img src="https://user-images.githubusercontent.com/8419308/28042811-36c7c624-658c-11e7-8843-acc02e041fee.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/28042841-5811023c-658c-11e7-90c1-b29eab468517.png" width=300>

I think the curved icon is a better iconic representation of the path, and it works better with the tracking dots (flat line implied constant v). I would go with either the middle or bottom curved icon.

**Comment by ariel-phet** [comment]
@arouinfar I vote middle curved. Clean and clear.

**Comment by arouinfar** [comment]
Thanks @ariel-phet! Do you have any thoughts about the vector icons in https://github.com/phetsims/projectile-motion/issues/71#issuecomment-314256396?

**Comment by ariel-phet** [comment]
@arouinfar for drag and vector screens, yes, I think we should still have the icons.

Since they are an icon, I think you can just use the smaller arrows, or split the difference. No need to change the icons when hitting the radio buttons.

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet. I'll try splitting the difference.

**Comment by arouinfar** [comment]
Splitting the difference looks about right to me.
<img src="https://user-images.githubusercontent.com/8419308/28043778-bb786fb4-6590-11e7-82c3-6c32ef3a09b1.png" width=300>


We could also go down this route for the Intro screen, and show the icon next to the title
<img src="https://user-images.githubusercontent.com/8419308/28043739-94300412-6590-11e7-9018-ac7b9f248525.png" width=300>

**Comment by arouinfar** [comment]
I prefer the icons next to the "Velocity Vectors" and "Acceleration Vectors" titles. I think it looks a bit cleaner, and it allows us to use a single icon across the sim. I think total vs. components will be pretty obvious once they are turned on.

**Comment by ariel-phet** [comment]
@arouinfar, nice improvement, I agree. Let's go with what you have in the last comment

**Comment by arouinfar** [comment]
Great! Thanks, @ariel-phet.

@andrea-phet can you get these icons added? See https://github.com/phetsims/projectile-motion/issues/71#issuecomment-314273318 for the vector icons, and here's the icon for the Air Resistance.
![image](https://user-images.githubusercontent.com/8419308/28043967-c674191c-6591-11e7-8dad-20b6aac5b7a9.png)

**Comment by andrea-phet** [comment]
Assigning @arouinfar to review.

**Comment by arouinfar** [comment]
👍
