### ISSUE TITLE
Change angle step size to 1* on Lab Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#72]
For the lab screen, the cannon angle should be adjustable to the nearest 1*.  

A 1* step size could be tricky on the iPad, so we may have to make further adjustments, but for now, please go ahead and update the step size @andrea-phet.

**Comment by andrea-phet** [comment]
Okay, it's a 1* step on Lab now.

**Comment by arouinfar** [comment]
Looks good on my laptop, but I'll also need to review it on an iPad.

**Comment by arouinfar** [comment]
The student didn't appear to have any issues adjusting the angle on the iPad, but he also wasn't trying to precisely set the angle.

**Comment by arouinfar** [comment]
@phet-steele and I have both tested this out on the iPad, and found the angle to be easy to control at 1* increments. I don't have any further recommendations to make. Thanks @andrea-phet!
