### ISSUE TITLE
Layer path above projectile?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#74]
Using the path tracing tool can be difficult for large projectiles such as the Buick, because the artwork obscures the path. 
![image](https://user-images.githubusercontent.com/8419308/27978490-ef49ca2e-632c-11e7-8d1a-115ca2a40720.png)

In Flash, crashed projectiles would shatter, so the ending of the path was never obscured
![image](https://user-images.githubusercontent.com/8419308/27979986-6a892ebe-6337-11e7-8f6e-d6693446c1a1.png)

A few options: 
(1) When the projectile lands, re-layer the path above the projectile. 
(2) Always layer the path above the projectile.

Option (1) may look really odd when a projectile lands, but option (2) may obscure small projectiles or generally look a bit odd while in motion. For consistency, I would go with (2).

@ariel-phet can you take a look? What would you recommend?

**Comment by ariel-phet** [comment]
@arouinfar I think (2) could look OK, and since that is simplest, lets go with that to begin with.

**Comment by arouinfar** [comment]
Sounds good @ariel-phet.

@andrea-phet can you update the layering so that the path is above the projectile?

**Comment by andrea-phet** [comment]
Done.

**Comment by arouinfar** [comment]
Thanks @andrea-phet! In general, I think this looks pretty good. My one concern is that smaller projectiles are a bit obscured. @ariel-phet can you take a look?

**Comment by ariel-phet** [comment]
@arouinfar I think this is a definite improvement.

To me the obscuring issue is minor, and I think will be ameliorated if we lighten the "dots" on the trajectory. Perhaps instead of using grey dots, we should just turn down the opacity of the dots?

**Comment by arouinfar** [comment]
@ariel-phet if we make the dots gray, the contrast against the pedestal will be diminished. I would be in favor of reducing the opacity, but drawing hundreds of reduced-opacity objects probably has negative effects on the performance.

**Comment by ariel-phet** [comment]
@arouinfar I don't think opacity is a problem for performance (but gradients are), I could be wrong however.

**Comment by arouinfar** [comment]
Thanks for the clarification @ariel-phet! I would definitely like to see reduced-opacity tracking dots. I'll work with @andrea-phet on this in real-time.

**Comment by ariel-phet** [comment]
@arouinfar if possible just check on an iPad2 to see if there is any significant performance impact

**Comment by arouinfar** [comment]
Will do @ariel-phet!

**Comment by arouinfar** [comment]
Worked with @andrea-phet to reduce the size of the dots a little bit, as well as reduce their opacity. 

@ariel-phet here's what a set of 5 paths looks like now:
![image](https://user-images.githubusercontent.com/8419308/28040102-e19c6484-6581-11e7-8d39-c563566635a3.png)

We did some quick testing on iPad2, and shooting out several projectiles at a time reduced the frame rate similarly with and without the added opacity.

**Comment by ariel-phet** [comment]
I played with master, looks good to me. Closing.
