### ISSUE TITLE
Move zoom buttons down a few pixels

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#76]
The zoom buttons are pretty close to the top of the window. When using the zoom buttons on iPad, it's very easily to accidentally navigate to another browser tab. @andrea-phet can you move the zoom buttons down ~3 pixels and give their touch areas a bit of extra padding on the bottom?

![image](https://user-images.githubusercontent.com/8419308/28030453-10391aba-6561-11e7-89bc-eaf1deced930.png)

**Comment by andrea-phet** [comment]
Yes, done.

**Comment by arouinfar** [comment]
Thanks @andrea-phet! The placement looks good on my laptop, but kicking this one over to @phet-steele to check on the iPad.

**Comment by phet-steele** [comment]
It's good!
