### ISSUE TITLE
Number of decimals on target?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#79]
By default, the target is located at 15 m (no decimals). Once the target is moved, two decimal places appear (only 15 has the decimals suppressed). I find it very hard to drag the target to a precise location. Given that the target itself is 3 m wide, it seems odd to assign such a precise value to the target's center. Instead, I would recommend snapping the target to 0.1 m steps along the road. 

![image](https://user-images.githubusercontent.com/8419308/28031019-324e7b3e-6563-11e7-9ec2-c1245096df20.png) ![image](https://user-images.githubusercontent.com/8419308/28031089-7223917c-6563-11e7-95ff-de9013a9bafc.png)

@ariel-phet can you think of a reason why we should keep 2 decimals on the target?

**Comment by ariel-phet** [comment]
@arouinfar no, I cannot, 2 decimals seems inappropriately precise.

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet. 

@andrea-phet please update the target so that it snaps to 0.1 m increments along the road. I'm also not sure why 15 m has its decimals suppressed, but while you're at it, please change it to 15.0 m.

**Comment by andrea-phet** [comment]
Done.

**Comment by arouinfar** [comment]
Love it!
