### ISSUE TITLE
Scale Flatirons with zoom

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#80]
As discussed in the last design meeting, it seems a bit odd that the Flatirons are not affected by the zoom level. 

- [x] Move David 2 m closer to the crosshairs. (Currently 9 m away.)
- [x] Scale default size of Flatirons down a bit (try 10%) but keep right side the same distance away from the control panels.

With these changes the flatirons should mostly be hidden by the control panels when zoomed all the way in (at iPad aspect ratio) and there will be less overlap with David.

**Comment by andrea-phet** [comment]
Okay, those two changes were made.

**Comment by arouinfar** [comment]
Reviewed in design meeting, and the shifting flatirons look good. No need to scale the image with the zoom.
