### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#81]
I've noticed a few scaling issues in reviewing dev.5

(1) Round items should be consistently sized with one another. At max zoom and 1 m diameter, the golfball, baseball, and cannonball have radically different sizes
![image](https://user-images.githubusercontent.com/8419308/28035232-24827a4c-6571-11e7-947d-38c86408b216.png)
(2) Diameter of of items should scale with zoom level. Default zoom vs. max zoom
<img width="112" alt="screen shot 2017-07-10 at 1 11 58 pm" src="https://user-images.githubusercontent.com/8419308/28035364-a68285c8-6571-11e7-824f-c68c4faf8f45.png"> <img width="125" alt="screen shot 2017-07-10 at 1 13 37 pm" src="https://user-images.githubusercontent.com/8419308/28035365-a683ac96-6571-11e7-9a63-fed0c2916696.png"> 

The golfball seems to be appropriately scaled. I suspect the cannonball is too large because it's been Hollywooded so that its default size is more visible, and the baseball is running into the max image size too early, so it no longer increases in size. 

I will review the assets and re-scale them so that the image size is 2x the resolution needed for the max diameter at max zoom on an iPad.

**Comment by arouinfar** [comment]
@andrea-phet I have adjusted the artwork for the benchmarks and will email them to you. All .png files are now sized to be 2x the resolution of the max diameter at the max zoom level on an iPad. 

For example, on an iPad at max zoom, the 1m baseball should be 1/2 the size of baseball.png.

I also ended up revising some of the benchmark defaults/ranges for for more reasonable scaling. The values can be found in the "HTML5-Revised" tab of the Benchmark Properties google doc. Values in red have been updated.
![image](https://user-images.githubusercontent.com/8419308/28138896-94f96192-670f-11e7-912d-f8ca49c5d9b8.png)

I haven't included any artwork for the arrow, because I'm thinking about removing it (we'll discuss at design). It scales very poorly and requires a lot of Hollywooding to look reasonable at the default values.

**Comment by andrea-phet** [comment]
The new artwork and updated benchmark info have been incorporated. Assigning to @arouinfar to review.

**Comment by arouinfar** [comment]
Looks pretty good @andrea-phet. A few more requests...
- [ ] Scale down Buick by 10%
- [ ] Scale down Tank shell by 50% (seems to be 2x too large)
![image](https://user-images.githubusercontent.com/8419308/28432173-304baea4-6d44-11e7-920a-e33f6060ad4c.png)
- [ ] Crashed pumpkin is obviously larger than the original. I double checked the assets, and they are sized properly.
<img src="https://user-images.githubusercontent.com/8419308/28431517-d8bdfdc4-6d41-11e7-9036-692a813e5c97.png" width=300>

- [ ]  "Crashed" PhET girl is waaaaay too big. The problem appears to be the asset, so I've updated it.
<img src="https://user-images.githubusercontent.com/8419308/28431569-fe417666-6d41-11e7-9387-976575b5a641.png" width=300>

**Comment by andrea-phet** [comment]
Updated on master. @arouinfar , how does it look?

**Comment by arouinfar** [comment]
@andrea-phet the 3m pumpkin looks a bit large
![image](https://user-images.githubusercontent.com/8419308/29047192-d7f4d936-7b87-11e7-8e07-632b43243abe.png)

Are you scaling it differently than the others?

**Comment by andrea-phet** [comment]
Everything is scaled empirically, so I went in and tweaked the scaling for pumpkin. How does it look now?

**Comment by arouinfar** [comment]
Looks much better @andrea-phet! 

> Everything is scaled empirically, so I went in and tweaked the scaling for pumpkin.

Does this mean that some assets are actually more than 2x the max size on iPad? If so, let me know in #119. I'm going to go ahead and close this issue.
