### ISSUE TITLE
Time step does not play nicely with tracking dots

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/projectile-motion#82]
Related to https://github.com/phetsims/QA/issues/20
Seen on Win 10: Chrome

The tracking dots that the tracer reads for in-flight data don't like the step system, it seems. If a projectile in flight is paused in flight, and the simulation stepped instead of unpaused, the tracking dots will no longer appear. This means that the tracer cannot read the flight path data past the point the dots disappear. Further projectiles on the same path will not create the missing dots (and will speed up and slow down a bit strangely as well).

To do it:
1.) Fire any projectile, any settings
2.) Pause sim in flight.
3.) Step sim once or multiple times. Tracking dots will not appear no matter how many times the sim is stepped.
4.) Unpause sim. Tracking dots still will not appear.

Relevant Picture;
![image](https://user-images.githubusercontent.com/22551096/28092805-f3f973c6-6651-11e7-8e5c-05265fedc443.png)

I feel like the step button is breaking the dots as they (from what I could gather) are meant to appear every 50 milliseconds, but stepping the sim throws off the timer and/or disables the timer and causes them to refuse to appear further. 

Debug info;
Name: ‪Projectile Motion‬
URL: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.5/projectile-motion_en.html
Version: 1.0.0-dev.5 2017-07-06 23:06:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Language: en-US
Window: 1920x960
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"fd28f6a0","branch":"master"},"babel":{"sha":"418f6759","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"c4c9c3ef","branch":"master"},"dot":{"sha":"3d9d2f3d","branch":"master"},"joist":{"sha":"aad930be","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"projectile-motion":{"sha":"c7df9dbf","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"7ee4afe3","branch":"master"},"scenery-phet":{"sha":"f95f098f","branch":"master"},"sherpa":{"sha":"b0dd5fe8","branch":"master"},"sun":{"sha":"baf827e3","branch":"master"},"tandem":{"sha":"f3949f64","branch":"master"}}

**Comment by phet-steele** [comment]
@EthanWJohnson this should be fixed (I think by 0dad930b6ca363356ce42caf5a9bf15e12ebac63). Feel free to verify in master or wait until next release.

**Comment by EthanWJohnson** [comment]
I never saw any further issues (I know, a bit late for that) so this can be considered solved.
