### ISSUE TITLE
Keypad rounding error?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#83]
Typing `0.35` into the keypad on the lab screen reveals what is probably some floating point errors:
<img width="831" alt="screen shot 2017-07-12 at 11 06 13 am" src="https://user-images.githubusercontent.com/5863899/28129864-31e081d4-66f2-11e7-81b3-1a6ea16c8044.png">

Seen on Win 10 Chrome and macOS 10.12.5 Chrome. For phetsims/QA/issues/20.

URL: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.5/projectile-motion_en.html
Version: 1.0.0-dev.5 2017-07-06 23:06:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"fd28f6a0","branch":"master"},"babel":{"sha":"418f6759","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"c4c9c3ef","branch":"master"},"dot":{"sha":"3d9d2f3d","branch":"master"},"joist":{"sha":"aad930be","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"projectile-motion":{"sha":"c7df9dbf","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"7ee4afe3","branch":"master"},"scenery-phet":{"sha":"f95f098f","branch":"master"},"sherpa":{"sha":"b0dd5fe8","branch":"master"},"sun":{"sha":"baf827e3","branch":"master"},"tandem":{"sha":"f3949f64","branch":"master"}}

Side note, this is my 1000th github issue. Yay me! I didn't know how to celebrate so here is a picture of Darth Cat. Thanks for being awesome @ariel-phet @kathy-phet @samreid @jonathanolson @jbphet @pixelzoom @Denz1994 @amanda-phet @arouinfar @andrea-phet @oliver-phet @emily-phet @zepumph @jessegreenberg @EthanWJohnson @ayeemdee @brroberts1231 @BryceAG @arnabp @mattpen @mbarlow12 @terracoda @veillette (Don't worry, only time I'll bug everyone, sorry if I missed you! [github could really use an "at everyone"])

![image](https://user-images.githubusercontent.com/5863899/28129988-b5e10a3a-66f2-11e7-9d8b-9612eca76ea7.png)

**Comment by andrea-phet** [comment]
Should be good now.

**Comment by phet-steele** [comment]
@andrea-phet, I cannot test this due to #95.

**Comment by andrea-phet** [comment]
Should be good now.

**Comment by phet-steele** [comment]
Working well now. Let's hope there are no other numbers that cause this!
