### ISSUE TITLE
Have tools float to edge of screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#85]
@andrea-phet, tools should be allowed to float to the edge of the screen. Since projectile can go anywhere on the screen, as is I cannot measure anything outside of dev bounds:

![prmo01](https://user-images.githubusercontent.com/5863899/28135924-2c7884e0-6705-11e7-98de-5165e02a3c33.gif)

Constraining to screen bounds should keep tools on the screen on an iPad, so there should be no problem there.

Additionally, I'd recommend using the middle of the blue section of the tracer tool to calculate bounds instead of the center of the crosshairs. Since the crosshairs cannot be grabbed, the tool can be lost off the right side of the screen on an iPad:

1. Zoom out
2. Place the tracer tool along the right of the screen
3. Zoom in, the crosshairs are the only thing visible and cannot be grabbed

For phetsims/QA/issues/20.

**Comment by andrea-phet** [comment]
Assigning to @phet-steele to check.

**Comment by phet-steele** [comment]
This is great @andrea-phet. Thanks.
