### ISSUE TITLE
1.0.0-dev.5 memory leak

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#86]
@andrea-phet you may want to look into #42 if needed. This should also help with iPad 2 performance. Ran the test with this link in macOS 10.12.5 Chrome: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.5/projectile-motion_en.html?fuzzMouse

Heap snapshots are recorded once every minute. Target MB usage over 5 minutes is between 20 - 70 MB (simply due to how other sims perform). However, as long as the sim plateaus in memory usage at some amount below 100 MB (after a good amount of work in trying to lower memory), then the sim will pass. For comparison with another image heavy sim, look at function-builder's memory.

| min | MB |
| --- | --- |
| 0 | 37.9 |
| 1 | 93.1 |
| 2 | 144 |
| 3 | 191 |
| 4 | 236 |
| 5 | 300 |

For phetsims/QA/issues/20.

**Comment by andrea-phet** [comment]
Now, for master, heap snapshots are at:

| min | MB |
| --- | --- |
| 0 | 41.2 |
| 1 | 48.6 |
| 2 | 49.7 |
| 3 | 50.3 |
| 4 | 51.0 |
| 5 | 53.2 |
| 10 | 54.5 |
| 15 | 52.8 |
| 20 | 53.3 |
| 25 | 53.0 |
| 30 | 55.6 |

**Comment by andrea-phet** [comment]
Assigning to @phet-steele to review.

**Comment by phet-steele** [comment]
Not leaking on master! Great job!

**Comment by pixelzoom** [comment]
In code review #103, I'm seeing similar numbers to https://github.com/phetsims/projectile-motion/issues/86#issuecomment-316216774, so no memory leaks.
