### ISSUE TITLE
Tracer tool enters the tool box agressively

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#87]
@arouinfar @andrea-phet you may already have seen this in interviews (bummer), dev.6 and master return the tracer tool to the toolbox if it is placed anywhere along the right half of the screen:

NOT an issue in dev.5, also tape measurer is NOT affected.
![prmo02](https://user-images.githubusercontent.com/5863899/28141192-c0cfdef0-6718-11e7-93df-78b965f51601.gif)

Seen on macOS 10.12.5 Chrome.

**Comment by arouinfar** [comment]
Observed this in interviews too. Sometimes students would drag the tool out and it would immediately snap back into the toolbox.

**Comment by andrea-phet** [comment]
Assigning back to @phet-steele to check.

**Comment by phet-steele** [comment]
The tracer tool has calmed down, thanks!
