### ISSUE TITLE
Add cueing arrows to height

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#88]
In interviews, neither student adjusted the height of the cannon. When asked to change the cannon height at the end of the interview, the students were able to figure out how to drag the cannon up. Seems like we should add a cueing arrow to the cannon. Self-assigning to mock up some options.

**Comment by arouinfar** [comment]
In today's design meeting, we discussed several options to cue that the height is adjustable (summarized in the meeting notes). We decided to pursue lightweight cueing arrows on both the cannon's height label and barrel, similar in style to the arrows used to cue the switch in Capacitor Lab: Basics. The placement will roughly be like this, with the arrows on the barrel being arc-shaped.
![image](https://user-images.githubusercontent.com/8419308/28193474-445f61c8-67fa-11e7-8ee7-51ea40e6d815.png)

@andrea-phet has implemented a rough cueing arrow in dev7 for testing in tomorrow's interviews.
![image](https://user-images.githubusercontent.com/8419308/28193496-71ec6730-67fa-11e7-8931-2b73877ae864.png)

I'll report back with how it goes tomorrow, and will create some updated mockups more in line with the CL:B style.

**Comment by arouinfar** [comment]
Even with the cueing arrow in dev.7, the student didn't adjust the height of the cannon until prompted. That said, he was much quicker to adjust the height than previous students.

In the next interview, I'm going to try raising the cannon and leveling the angle on the Intro screen to see how it affects the flow. 
![image](https://user-images.githubusercontent.com/8419308/28228296-2937b9bc-689b-11e7-8066-aa1dcaea0720.png)

Students usually fire the cannon a few times before making comparisons between the paths. My hope is that seeing an elevated cannon will make it clearer to the students that the height is adjustable.

**Comment by phet-steele** [comment]
@arouinfar @andrea-phet, if we keep these cueing arrows, they need to reappear after a Reset All! (they currently do not)

**Comment by arouinfar** [comment]
After conducting 3 more interviews and further discussion at design meeting, we've decided to ditch the cueing arrows on the barrel and proceed with the following changes:

- [ ] On Intro, the cannon's default state is: height = 10 m, angle = 0 *, initial speed = 15 m/s (all screens)
- [ ] Light blue cueing arrows above and below the height label (intro screen only)
- [ ] When visible, cueing arrows should be included in the height's click/touch area
- [ ] Cueing arrows return on reset all

**Comment by arouinfar** [comment]
👍

**Comment by arouinfar** [comment]
@andrea-phet looks like you forgot to change the cannon's default speed to 15 m/s.

**Comment by andrea-phet** [comment]
Oops, my bad. Should be changed now.

**Comment by ariel-phet** [comment]
Looks good, closing!
