### ISSUE TITLE
Layer vectors over path

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#89]
<img width="217" alt="screen shot 2017-07-13 at 10 09 29 am" src="https://user-images.githubusercontent.com/5863899/28176214-cdde593c-67b3-11e7-9e7c-8debbe56ea15.png">

Mostly for the sake of acceleration vectors that are hard to see behind the path. The x component is generally very small (it is there, but can't really be seen in the above screenshot). @arouinfar is okay with this change. So the layering goes (top) Vectors > Path > Projectile (bottom)

For phetsims/QA/issues/20, sort of.

**Comment by andrea-phet** [comment]
Good idea. Assigning to @arouinfar to review, also @phet-steele feel free to take a look.

**Comment by arouinfar** [comment]
Definitely an improvement @andrea-phet!
![image](https://user-images.githubusercontent.com/8419308/28198022-3550dc20-6818-11e7-9cb0-53af410471c9.png)
