### ISSUE TITLE
strokeWidth in DragProjectilePanel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/projectile-motion#90]
Noticed this in TEXT_BACKGROUND_OPTIONS. First, it would be `lineWidth` instead of `strokeWidth`, and second, `lineWidth: 1` is the default, so generally doesn't need to be specified. Should be safe to remove it?

**Comment by andrea-phet** [comment]
Good catch, it is not necessary so I removed it.

**Comment by andrea-phet** [comment]
Assigning to @jonathanolson to review and close.

**Comment by jonathanolson** [comment]
Looks good, thanks!
