### ISSUE TITLE
Shift center of mass of morphing drag projectile

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#91]
Related to #78, the COM of the morphing drag projectile is centered in the shape. At times, the center point is noticeably shifted from the COM.
![image](https://user-images.githubusercontent.com/8419308/28197101-e4a0a982-6811-11e7-9e60-259c546ed9c8.png)

During design meeting, the team discussed a options
(1) Manually define the COM for each shape (similar to Balancing Act)
(2) Dynamically calculate the COM for each shape
(3) Use the circle's COM as a reference point, and align the rounded side of the shape to the circle. This should look about right for most shapes.
<img src="https://user-images.githubusercontent.com/8419308/28197309-3449a56e-6813-11e7-91d1-3fad8d2a78ef.png" width=300>

We decided that option (3) seemed the most straightforward.

**Comment by andrea-phet** [comment]
Assigned to @arouinfar to take a look.

**Comment by arouinfar** [comment]
Looks great!
