### ISSUE TITLE
Tracer tool pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#92]
As discussed in design meeting, the tracer tool has a lot of empty space between the strings and readouts. This can be reduced a bit and the tool shortened overall. For grabbability, the tool extends for 20 px beyond the readouts.
<img src="https://user-images.githubusercontent.com/8419308/28197753-342a4018-6816-11e7-9051-4da0cd1e82ca.png" width=300>

**Comment by arouinfar** [comment]
Looks pretty good @andrea-phet, but I think there's a little bit too much padding to the right of the readouts. Can you reduce the padding by 15%?

**Comment by andrea-phet** [comment]
Yes, I tried that and reduced it by a bit more, I think 20%.

**Comment by arouinfar** [comment]
@andrea-phet I pulled master and the tool looks really similar to me. If anything, the padding to the right of the readouts grew...
![image](https://user-images.githubusercontent.com/8419308/28392425-232112be-6c9f-11e7-8387-c96d6d4a9d8e.png)

**Comment by andrea-phet** [comment]
Oops, you're right. How about now:
![image](https://user-images.githubusercontent.com/7988696/28427262-d0ff10f0-6d32-11e7-968d-e2951fac029f.png)

**Comment by arouinfar** [comment]
Looks good @andrea-phet!
