### ISSUE TITLE
5/8 reset methods are missing JSDoc

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#93]
While reviewing https://github.com/phetsims/projectile-motion/issues/57 I noticed that 3 of the 8 reset methods have JSDoc but the others are missing JSDoc.  The JSDoc should be added where it is missing.

**Comment by andrea-phet** [comment]
The missing doc has been added, assigning to @samreid to review.

**Comment by samreid** [comment]
Looks great, thanks!
