### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/projectile-motion#98]
This is to track credits, to ensure they are correct before publication.

Assigning to @ariel-phet.

**Comment by andrea-phet** [comment]
The latest version has:
![image](https://user-images.githubusercontent.com/7988696/28390308-b3047ff0-6c96-11e7-90b5-09c8596f7022.png)

**Comment by ariel-phet** [comment]
@andrea-phet please add "Wendy Adams" to the Team section (we have a policy of copying over original team members to ports)

You might also want to ask @jbphet if he wants to be included in the credits as he has been part of many of the design meetings now.

**Comment by ariel-phet** [comment]
Oh, and please move Michael Dubson up to the Lead Design section, and remove him from software

**Comment by amanda-phet** [comment]
You should move me from lead to team.

**Comment by andrea-phet** [comment]
Off to QA land...

**Comment by phet-steele** [comment]
I finalized the QA credits.
