### ISSUE TITLE
Include readout in click/touch area to open number pad

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#99]
@andrea-phet we generally include the readout next to the edit button in the click/touch area to open the number pad. Can you please adjust?
<img src="https://user-images.githubusercontent.com/8419308/28430372-938839b2-6d3d-11e7-98a1-d7c6b049691d.png" width=300>

**Comment by andrea-phet** [comment]
The readout can now be clicked on to open the keyboard as well.

**Comment by arouinfar** [comment]
👍
